#![allow(dead_code)]
#![allow(nonstandard_style)]
#![allow(unused_variables)]

/* automatically generated by rust-bindgen 0.70.1 */

pub const RAYLIB_VERSION_MAJOR: u32 = 5;
pub const RAYLIB_VERSION_MINOR: u32 = 0;
pub const RAYLIB_VERSION_PATCH: u32 = 0;
pub const RAYLIB_VERSION: &[u8; 4] = b"5.0\0";
pub type va_list = __builtin_va_list;
pub type __gnuc_va_list = __builtin_va_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Vector2 {
    pub x: f32,
    pub y: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Vector3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Vector4 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}
pub type Quaternion = Vector4;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Matrix {
    pub m0: f32,
    pub m4: f32,
    pub m8: f32,
    pub m12: f32,
    pub m1: f32,
    pub m5: f32,
    pub m9: f32,
    pub m13: f32,
    pub m2: f32,
    pub m6: f32,
    pub m10: f32,
    pub m14: f32,
    pub m3: f32,
    pub m7: f32,
    pub m11: f32,
    pub m15: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Color {
    pub r: ::std::os::raw::c_uchar,
    pub g: ::std::os::raw::c_uchar,
    pub b: ::std::os::raw::c_uchar,
    pub a: ::std::os::raw::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Rectangle {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Image {
    pub data: *mut ::std::os::raw::c_void,
    pub width: ::std::os::raw::c_int,
    pub height: ::std::os::raw::c_int,
    pub mipmaps: ::std::os::raw::c_int,
    pub format: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Texture {
    pub id: ::std::os::raw::c_uint,
    pub width: ::std::os::raw::c_int,
    pub height: ::std::os::raw::c_int,
    pub mipmaps: ::std::os::raw::c_int,
    pub format: ::std::os::raw::c_int,
}
pub type Texture2D = Texture;
pub type TextureCubemap = Texture;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RenderTexture {
    pub id: ::std::os::raw::c_uint,
    pub texture: Texture,
    pub depth: Texture,
}
pub type RenderTexture2D = RenderTexture;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NPatchInfo {
    pub source: Rectangle,
    pub left: ::std::os::raw::c_int,
    pub top: ::std::os::raw::c_int,
    pub right: ::std::os::raw::c_int,
    pub bottom: ::std::os::raw::c_int,
    pub layout: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GlyphInfo {
    pub value: ::std::os::raw::c_int,
    pub offsetX: ::std::os::raw::c_int,
    pub offsetY: ::std::os::raw::c_int,
    pub advanceX: ::std::os::raw::c_int,
    pub image: Image,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Font {
    pub baseSize: ::std::os::raw::c_int,
    pub glyphCount: ::std::os::raw::c_int,
    pub glyphPadding: ::std::os::raw::c_int,
    pub texture: Texture2D,
    pub recs: *mut Rectangle,
    pub glyphs: *mut GlyphInfo,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera3D {
    pub position: Vector3,
    pub target: Vector3,
    pub up: Vector3,
    pub fovy: f32,
    pub projection: ::std::os::raw::c_int,
}
pub type Camera = Camera3D;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera2D {
    pub offset: Vector2,
    pub target: Vector2,
    pub rotation: f32,
    pub zoom: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Mesh {
    pub vertexCount: ::std::os::raw::c_int,
    pub triangleCount: ::std::os::raw::c_int,
    pub vertices: *mut f32,
    pub texcoords: *mut f32,
    pub texcoords2: *mut f32,
    pub normals: *mut f32,
    pub tangents: *mut f32,
    pub colors: *mut ::std::os::raw::c_uchar,
    pub indices: *mut ::std::os::raw::c_ushort,
    pub animVertices: *mut f32,
    pub animNormals: *mut f32,
    pub boneIds: *mut ::std::os::raw::c_uchar,
    pub boneWeights: *mut f32,
    pub vaoId: ::std::os::raw::c_uint,
    pub vboId: *mut ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Shader {
    pub id: ::std::os::raw::c_uint,
    pub locs: *mut ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MaterialMap {
    pub texture: Texture2D,
    pub color: Color,
    pub value: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Material {
    pub shader: Shader,
    pub maps: *mut MaterialMap,
    pub params: [f32; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Transform {
    pub translation: Vector3,
    pub rotation: Quaternion,
    pub scale: Vector3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BoneInfo {
    pub name: [::std::os::raw::c_char; 32usize],
    pub parent: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Model {
    pub transform: Matrix,
    pub meshCount: ::std::os::raw::c_int,
    pub materialCount: ::std::os::raw::c_int,
    pub meshes: *mut Mesh,
    pub materials: *mut Material,
    pub meshMaterial: *mut ::std::os::raw::c_int,
    pub boneCount: ::std::os::raw::c_int,
    pub bones: *mut BoneInfo,
    pub bindPose: *mut Transform,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ModelAnimation {
    pub boneCount: ::std::os::raw::c_int,
    pub frameCount: ::std::os::raw::c_int,
    pub bones: *mut BoneInfo,
    pub framePoses: *mut *mut Transform,
    pub name: [::std::os::raw::c_char; 32usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Ray {
    pub position: Vector3,
    pub direction: Vector3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RayCollision {
    pub hit: bool,
    pub distance: f32,
    pub point: Vector3,
    pub normal: Vector3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BoundingBox {
    pub min: Vector3,
    pub max: Vector3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Wave {
    pub frameCount: ::std::os::raw::c_uint,
    pub sampleRate: ::std::os::raw::c_uint,
    pub sampleSize: ::std::os::raw::c_uint,
    pub channels: ::std::os::raw::c_uint,
    pub data: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rAudioBuffer {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rAudioProcessor {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioStream {
    pub buffer: *mut rAudioBuffer,
    pub processor: *mut rAudioProcessor,
    pub sampleRate: ::std::os::raw::c_uint,
    pub sampleSize: ::std::os::raw::c_uint,
    pub channels: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Sound {
    pub stream: AudioStream,
    pub frameCount: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Music {
    pub stream: AudioStream,
    pub frameCount: ::std::os::raw::c_uint,
    pub looping: bool,
    pub ctxType: ::std::os::raw::c_int,
    pub ctxData: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VrDeviceInfo {
    pub hResolution: ::std::os::raw::c_int,
    pub vResolution: ::std::os::raw::c_int,
    pub hScreenSize: f32,
    pub vScreenSize: f32,
    pub vScreenCenter: f32,
    pub eyeToScreenDistance: f32,
    pub lensSeparationDistance: f32,
    pub interpupillaryDistance: f32,
    pub lensDistortionValues: [f32; 4usize],
    pub chromaAbCorrection: [f32; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VrStereoConfig {
    pub projection: [Matrix; 2usize],
    pub viewOffset: [Matrix; 2usize],
    pub leftLensCenter: [f32; 2usize],
    pub rightLensCenter: [f32; 2usize],
    pub leftScreenCenter: [f32; 2usize],
    pub rightScreenCenter: [f32; 2usize],
    pub scale: [f32; 2usize],
    pub scaleIn: [f32; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FilePathList {
    pub capacity: ::std::os::raw::c_uint,
    pub count: ::std::os::raw::c_uint,
    pub paths: *mut *mut ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AutomationEvent {
    pub frame: ::std::os::raw::c_uint,
    pub type_: ::std::os::raw::c_uint,
    pub params: [::std::os::raw::c_int; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AutomationEventList {
    pub capacity: ::std::os::raw::c_uint,
    pub count: ::std::os::raw::c_uint,
    pub events: *mut AutomationEvent,
}
pub const ConfigFlags_FLAG_VSYNC_HINT: ConfigFlags = 64;
pub const ConfigFlags_FLAG_FULLSCREEN_MODE: ConfigFlags = 2;
pub const ConfigFlags_FLAG_WINDOW_RESIZABLE: ConfigFlags = 4;
pub const ConfigFlags_FLAG_WINDOW_UNDECORATED: ConfigFlags = 8;
pub const ConfigFlags_FLAG_WINDOW_HIDDEN: ConfigFlags = 128;
pub const ConfigFlags_FLAG_WINDOW_MINIMIZED: ConfigFlags = 512;
pub const ConfigFlags_FLAG_WINDOW_MAXIMIZED: ConfigFlags = 1024;
pub const ConfigFlags_FLAG_WINDOW_UNFOCUSED: ConfigFlags = 2048;
pub const ConfigFlags_FLAG_WINDOW_TOPMOST: ConfigFlags = 4096;
pub const ConfigFlags_FLAG_WINDOW_ALWAYS_RUN: ConfigFlags = 256;
pub const ConfigFlags_FLAG_WINDOW_TRANSPARENT: ConfigFlags = 16;
pub const ConfigFlags_FLAG_WINDOW_HIGHDPI: ConfigFlags = 8192;
pub const ConfigFlags_FLAG_WINDOW_MOUSE_PASSTHROUGH: ConfigFlags = 16384;
pub const ConfigFlags_FLAG_BORDERLESS_WINDOWED_MODE: ConfigFlags = 32768;
pub const ConfigFlags_FLAG_MSAA_4X_HINT: ConfigFlags = 32;
pub const ConfigFlags_FLAG_INTERLACED_HINT: ConfigFlags = 65536;
pub type ConfigFlags = ::std::os::raw::c_uint;
pub const TraceLogLevel_LOG_ALL: TraceLogLevel = 0;
pub const TraceLogLevel_LOG_TRACE: TraceLogLevel = 1;
pub const TraceLogLevel_LOG_DEBUG: TraceLogLevel = 2;
pub const TraceLogLevel_LOG_INFO: TraceLogLevel = 3;
pub const TraceLogLevel_LOG_WARNING: TraceLogLevel = 4;
pub const TraceLogLevel_LOG_ERROR: TraceLogLevel = 5;
pub const TraceLogLevel_LOG_FATAL: TraceLogLevel = 6;
pub const TraceLogLevel_LOG_NONE: TraceLogLevel = 7;
pub type TraceLogLevel = ::std::os::raw::c_uint;
pub const KeyboardKey_KEY_NULL: KeyboardKey = 0;
pub const KeyboardKey_KEY_APOSTROPHE: KeyboardKey = 39;
pub const KeyboardKey_KEY_COMMA: KeyboardKey = 44;
pub const KeyboardKey_KEY_MINUS: KeyboardKey = 45;
pub const KeyboardKey_KEY_PERIOD: KeyboardKey = 46;
pub const KeyboardKey_KEY_SLASH: KeyboardKey = 47;
pub const KeyboardKey_KEY_ZERO: KeyboardKey = 48;
pub const KeyboardKey_KEY_ONE: KeyboardKey = 49;
pub const KeyboardKey_KEY_TWO: KeyboardKey = 50;
pub const KeyboardKey_KEY_THREE: KeyboardKey = 51;
pub const KeyboardKey_KEY_FOUR: KeyboardKey = 52;
pub const KeyboardKey_KEY_FIVE: KeyboardKey = 53;
pub const KeyboardKey_KEY_SIX: KeyboardKey = 54;
pub const KeyboardKey_KEY_SEVEN: KeyboardKey = 55;
pub const KeyboardKey_KEY_EIGHT: KeyboardKey = 56;
pub const KeyboardKey_KEY_NINE: KeyboardKey = 57;
pub const KeyboardKey_KEY_SEMICOLON: KeyboardKey = 59;
pub const KeyboardKey_KEY_EQUAL: KeyboardKey = 61;
pub const KeyboardKey_KEY_A: KeyboardKey = 65;
pub const KeyboardKey_KEY_B: KeyboardKey = 66;
pub const KeyboardKey_KEY_C: KeyboardKey = 67;
pub const KeyboardKey_KEY_D: KeyboardKey = 68;
pub const KeyboardKey_KEY_E: KeyboardKey = 69;
pub const KeyboardKey_KEY_F: KeyboardKey = 70;
pub const KeyboardKey_KEY_G: KeyboardKey = 71;
pub const KeyboardKey_KEY_H: KeyboardKey = 72;
pub const KeyboardKey_KEY_I: KeyboardKey = 73;
pub const KeyboardKey_KEY_J: KeyboardKey = 74;
pub const KeyboardKey_KEY_K: KeyboardKey = 75;
pub const KeyboardKey_KEY_L: KeyboardKey = 76;
pub const KeyboardKey_KEY_M: KeyboardKey = 77;
pub const KeyboardKey_KEY_N: KeyboardKey = 78;
pub const KeyboardKey_KEY_O: KeyboardKey = 79;
pub const KeyboardKey_KEY_P: KeyboardKey = 80;
pub const KeyboardKey_KEY_Q: KeyboardKey = 81;
pub const KeyboardKey_KEY_R: KeyboardKey = 82;
pub const KeyboardKey_KEY_S: KeyboardKey = 83;
pub const KeyboardKey_KEY_T: KeyboardKey = 84;
pub const KeyboardKey_KEY_U: KeyboardKey = 85;
pub const KeyboardKey_KEY_V: KeyboardKey = 86;
pub const KeyboardKey_KEY_W: KeyboardKey = 87;
pub const KeyboardKey_KEY_X: KeyboardKey = 88;
pub const KeyboardKey_KEY_Y: KeyboardKey = 89;
pub const KeyboardKey_KEY_Z: KeyboardKey = 90;
pub const KeyboardKey_KEY_LEFT_BRACKET: KeyboardKey = 91;
pub const KeyboardKey_KEY_BACKSLASH: KeyboardKey = 92;
pub const KeyboardKey_KEY_RIGHT_BRACKET: KeyboardKey = 93;
pub const KeyboardKey_KEY_GRAVE: KeyboardKey = 96;
pub const KeyboardKey_KEY_SPACE: KeyboardKey = 32;
pub const KeyboardKey_KEY_ESCAPE: KeyboardKey = 256;
pub const KeyboardKey_KEY_ENTER: KeyboardKey = 257;
pub const KeyboardKey_KEY_TAB: KeyboardKey = 258;
pub const KeyboardKey_KEY_BACKSPACE: KeyboardKey = 259;
pub const KeyboardKey_KEY_INSERT: KeyboardKey = 260;
pub const KeyboardKey_KEY_DELETE: KeyboardKey = 261;
pub const KeyboardKey_KEY_RIGHT: KeyboardKey = 262;
pub const KeyboardKey_KEY_LEFT: KeyboardKey = 263;
pub const KeyboardKey_KEY_DOWN: KeyboardKey = 264;
pub const KeyboardKey_KEY_UP: KeyboardKey = 265;
pub const KeyboardKey_KEY_PAGE_UP: KeyboardKey = 266;
pub const KeyboardKey_KEY_PAGE_DOWN: KeyboardKey = 267;
pub const KeyboardKey_KEY_HOME: KeyboardKey = 268;
pub const KeyboardKey_KEY_END: KeyboardKey = 269;
pub const KeyboardKey_KEY_CAPS_LOCK: KeyboardKey = 280;
pub const KeyboardKey_KEY_SCROLL_LOCK: KeyboardKey = 281;
pub const KeyboardKey_KEY_NUM_LOCK: KeyboardKey = 282;
pub const KeyboardKey_KEY_PRINT_SCREEN: KeyboardKey = 283;
pub const KeyboardKey_KEY_PAUSE: KeyboardKey = 284;
pub const KeyboardKey_KEY_F1: KeyboardKey = 290;
pub const KeyboardKey_KEY_F2: KeyboardKey = 291;
pub const KeyboardKey_KEY_F3: KeyboardKey = 292;
pub const KeyboardKey_KEY_F4: KeyboardKey = 293;
pub const KeyboardKey_KEY_F5: KeyboardKey = 294;
pub const KeyboardKey_KEY_F6: KeyboardKey = 295;
pub const KeyboardKey_KEY_F7: KeyboardKey = 296;
pub const KeyboardKey_KEY_F8: KeyboardKey = 297;
pub const KeyboardKey_KEY_F9: KeyboardKey = 298;
pub const KeyboardKey_KEY_F10: KeyboardKey = 299;
pub const KeyboardKey_KEY_F11: KeyboardKey = 300;
pub const KeyboardKey_KEY_F12: KeyboardKey = 301;
pub const KeyboardKey_KEY_LEFT_SHIFT: KeyboardKey = 340;
pub const KeyboardKey_KEY_LEFT_CONTROL: KeyboardKey = 341;
pub const KeyboardKey_KEY_LEFT_ALT: KeyboardKey = 342;
pub const KeyboardKey_KEY_LEFT_SUPER: KeyboardKey = 343;
pub const KeyboardKey_KEY_RIGHT_SHIFT: KeyboardKey = 344;
pub const KeyboardKey_KEY_RIGHT_CONTROL: KeyboardKey = 345;
pub const KeyboardKey_KEY_RIGHT_ALT: KeyboardKey = 346;
pub const KeyboardKey_KEY_RIGHT_SUPER: KeyboardKey = 347;
pub const KeyboardKey_KEY_KB_MENU: KeyboardKey = 348;
pub const KeyboardKey_KEY_KP_0: KeyboardKey = 320;
pub const KeyboardKey_KEY_KP_1: KeyboardKey = 321;
pub const KeyboardKey_KEY_KP_2: KeyboardKey = 322;
pub const KeyboardKey_KEY_KP_3: KeyboardKey = 323;
pub const KeyboardKey_KEY_KP_4: KeyboardKey = 324;
pub const KeyboardKey_KEY_KP_5: KeyboardKey = 325;
pub const KeyboardKey_KEY_KP_6: KeyboardKey = 326;
pub const KeyboardKey_KEY_KP_7: KeyboardKey = 327;
pub const KeyboardKey_KEY_KP_8: KeyboardKey = 328;
pub const KeyboardKey_KEY_KP_9: KeyboardKey = 329;
pub const KeyboardKey_KEY_KP_DECIMAL: KeyboardKey = 330;
pub const KeyboardKey_KEY_KP_DIVIDE: KeyboardKey = 331;
pub const KeyboardKey_KEY_KP_MULTIPLY: KeyboardKey = 332;
pub const KeyboardKey_KEY_KP_SUBTRACT: KeyboardKey = 333;
pub const KeyboardKey_KEY_KP_ADD: KeyboardKey = 334;
pub const KeyboardKey_KEY_KP_ENTER: KeyboardKey = 335;
pub const KeyboardKey_KEY_KP_EQUAL: KeyboardKey = 336;
pub const KeyboardKey_KEY_BACK: KeyboardKey = 4;
pub const KeyboardKey_KEY_MENU: KeyboardKey = 82;
pub const KeyboardKey_KEY_VOLUME_UP: KeyboardKey = 24;
pub const KeyboardKey_KEY_VOLUME_DOWN: KeyboardKey = 25;
pub type KeyboardKey = ::std::os::raw::c_uint;
pub const MouseButton_MOUSE_BUTTON_LEFT: MouseButton = 0;
pub const MouseButton_MOUSE_BUTTON_RIGHT: MouseButton = 1;
pub const MouseButton_MOUSE_BUTTON_MIDDLE: MouseButton = 2;
pub const MouseButton_MOUSE_BUTTON_SIDE: MouseButton = 3;
pub const MouseButton_MOUSE_BUTTON_EXTRA: MouseButton = 4;
pub const MouseButton_MOUSE_BUTTON_FORWARD: MouseButton = 5;
pub const MouseButton_MOUSE_BUTTON_BACK: MouseButton = 6;
pub type MouseButton = ::std::os::raw::c_uint;
pub const MouseCursor_MOUSE_CURSOR_DEFAULT: MouseCursor = 0;
pub const MouseCursor_MOUSE_CURSOR_ARROW: MouseCursor = 1;
pub const MouseCursor_MOUSE_CURSOR_IBEAM: MouseCursor = 2;
pub const MouseCursor_MOUSE_CURSOR_CROSSHAIR: MouseCursor = 3;
pub const MouseCursor_MOUSE_CURSOR_POINTING_HAND: MouseCursor = 4;
pub const MouseCursor_MOUSE_CURSOR_RESIZE_EW: MouseCursor = 5;
pub const MouseCursor_MOUSE_CURSOR_RESIZE_NS: MouseCursor = 6;
pub const MouseCursor_MOUSE_CURSOR_RESIZE_NWSE: MouseCursor = 7;
pub const MouseCursor_MOUSE_CURSOR_RESIZE_NESW: MouseCursor = 8;
pub const MouseCursor_MOUSE_CURSOR_RESIZE_ALL: MouseCursor = 9;
pub const MouseCursor_MOUSE_CURSOR_NOT_ALLOWED: MouseCursor = 10;
pub type MouseCursor = ::std::os::raw::c_uint;
pub const GamepadButton_GAMEPAD_BUTTON_UNKNOWN: GamepadButton = 0;
pub const GamepadButton_GAMEPAD_BUTTON_LEFT_FACE_UP: GamepadButton = 1;
pub const GamepadButton_GAMEPAD_BUTTON_LEFT_FACE_RIGHT: GamepadButton = 2;
pub const GamepadButton_GAMEPAD_BUTTON_LEFT_FACE_DOWN: GamepadButton = 3;
pub const GamepadButton_GAMEPAD_BUTTON_LEFT_FACE_LEFT: GamepadButton = 4;
pub const GamepadButton_GAMEPAD_BUTTON_RIGHT_FACE_UP: GamepadButton = 5;
pub const GamepadButton_GAMEPAD_BUTTON_RIGHT_FACE_RIGHT: GamepadButton = 6;
pub const GamepadButton_GAMEPAD_BUTTON_RIGHT_FACE_DOWN: GamepadButton = 7;
pub const GamepadButton_GAMEPAD_BUTTON_RIGHT_FACE_LEFT: GamepadButton = 8;
pub const GamepadButton_GAMEPAD_BUTTON_LEFT_TRIGGER_1: GamepadButton = 9;
pub const GamepadButton_GAMEPAD_BUTTON_LEFT_TRIGGER_2: GamepadButton = 10;
pub const GamepadButton_GAMEPAD_BUTTON_RIGHT_TRIGGER_1: GamepadButton = 11;
pub const GamepadButton_GAMEPAD_BUTTON_RIGHT_TRIGGER_2: GamepadButton = 12;
pub const GamepadButton_GAMEPAD_BUTTON_MIDDLE_LEFT: GamepadButton = 13;
pub const GamepadButton_GAMEPAD_BUTTON_MIDDLE: GamepadButton = 14;
pub const GamepadButton_GAMEPAD_BUTTON_MIDDLE_RIGHT: GamepadButton = 15;
pub const GamepadButton_GAMEPAD_BUTTON_LEFT_THUMB: GamepadButton = 16;
pub const GamepadButton_GAMEPAD_BUTTON_RIGHT_THUMB: GamepadButton = 17;
pub type GamepadButton = ::std::os::raw::c_uint;
pub const GamepadAxis_GAMEPAD_AXIS_LEFT_X: GamepadAxis = 0;
pub const GamepadAxis_GAMEPAD_AXIS_LEFT_Y: GamepadAxis = 1;
pub const GamepadAxis_GAMEPAD_AXIS_RIGHT_X: GamepadAxis = 2;
pub const GamepadAxis_GAMEPAD_AXIS_RIGHT_Y: GamepadAxis = 3;
pub const GamepadAxis_GAMEPAD_AXIS_LEFT_TRIGGER: GamepadAxis = 4;
pub const GamepadAxis_GAMEPAD_AXIS_RIGHT_TRIGGER: GamepadAxis = 5;
pub type GamepadAxis = ::std::os::raw::c_uint;
pub const MaterialMapIndex_MATERIAL_MAP_ALBEDO: MaterialMapIndex = 0;
pub const MaterialMapIndex_MATERIAL_MAP_METALNESS: MaterialMapIndex = 1;
pub const MaterialMapIndex_MATERIAL_MAP_NORMAL: MaterialMapIndex = 2;
pub const MaterialMapIndex_MATERIAL_MAP_ROUGHNESS: MaterialMapIndex = 3;
pub const MaterialMapIndex_MATERIAL_MAP_OCCLUSION: MaterialMapIndex = 4;
pub const MaterialMapIndex_MATERIAL_MAP_EMISSION: MaterialMapIndex = 5;
pub const MaterialMapIndex_MATERIAL_MAP_HEIGHT: MaterialMapIndex = 6;
pub const MaterialMapIndex_MATERIAL_MAP_CUBEMAP: MaterialMapIndex = 7;
pub const MaterialMapIndex_MATERIAL_MAP_IRRADIANCE: MaterialMapIndex = 8;
pub const MaterialMapIndex_MATERIAL_MAP_PREFILTER: MaterialMapIndex = 9;
pub const MaterialMapIndex_MATERIAL_MAP_BRDF: MaterialMapIndex = 10;
pub type MaterialMapIndex = ::std::os::raw::c_uint;
pub const ShaderLocationIndex_SHADER_LOC_VERTEX_POSITION: ShaderLocationIndex = 0;
pub const ShaderLocationIndex_SHADER_LOC_VERTEX_TEXCOORD01: ShaderLocationIndex = 1;
pub const ShaderLocationIndex_SHADER_LOC_VERTEX_TEXCOORD02: ShaderLocationIndex = 2;
pub const ShaderLocationIndex_SHADER_LOC_VERTEX_NORMAL: ShaderLocationIndex = 3;
pub const ShaderLocationIndex_SHADER_LOC_VERTEX_TANGENT: ShaderLocationIndex = 4;
pub const ShaderLocationIndex_SHADER_LOC_VERTEX_COLOR: ShaderLocationIndex = 5;
pub const ShaderLocationIndex_SHADER_LOC_MATRIX_MVP: ShaderLocationIndex = 6;
pub const ShaderLocationIndex_SHADER_LOC_MATRIX_VIEW: ShaderLocationIndex = 7;
pub const ShaderLocationIndex_SHADER_LOC_MATRIX_PROJECTION: ShaderLocationIndex = 8;
pub const ShaderLocationIndex_SHADER_LOC_MATRIX_MODEL: ShaderLocationIndex = 9;
pub const ShaderLocationIndex_SHADER_LOC_MATRIX_NORMAL: ShaderLocationIndex = 10;
pub const ShaderLocationIndex_SHADER_LOC_VECTOR_VIEW: ShaderLocationIndex = 11;
pub const ShaderLocationIndex_SHADER_LOC_COLOR_DIFFUSE: ShaderLocationIndex = 12;
pub const ShaderLocationIndex_SHADER_LOC_COLOR_SPECULAR: ShaderLocationIndex = 13;
pub const ShaderLocationIndex_SHADER_LOC_COLOR_AMBIENT: ShaderLocationIndex = 14;
pub const ShaderLocationIndex_SHADER_LOC_MAP_ALBEDO: ShaderLocationIndex = 15;
pub const ShaderLocationIndex_SHADER_LOC_MAP_METALNESS: ShaderLocationIndex = 16;
pub const ShaderLocationIndex_SHADER_LOC_MAP_NORMAL: ShaderLocationIndex = 17;
pub const ShaderLocationIndex_SHADER_LOC_MAP_ROUGHNESS: ShaderLocationIndex = 18;
pub const ShaderLocationIndex_SHADER_LOC_MAP_OCCLUSION: ShaderLocationIndex = 19;
pub const ShaderLocationIndex_SHADER_LOC_MAP_EMISSION: ShaderLocationIndex = 20;
pub const ShaderLocationIndex_SHADER_LOC_MAP_HEIGHT: ShaderLocationIndex = 21;
pub const ShaderLocationIndex_SHADER_LOC_MAP_CUBEMAP: ShaderLocationIndex = 22;
pub const ShaderLocationIndex_SHADER_LOC_MAP_IRRADIANCE: ShaderLocationIndex = 23;
pub const ShaderLocationIndex_SHADER_LOC_MAP_PREFILTER: ShaderLocationIndex = 24;
pub const ShaderLocationIndex_SHADER_LOC_MAP_BRDF: ShaderLocationIndex = 25;
pub type ShaderLocationIndex = ::std::os::raw::c_uint;
pub const ShaderUniformDataType_SHADER_UNIFORM_FLOAT: ShaderUniformDataType = 0;
pub const ShaderUniformDataType_SHADER_UNIFORM_VEC2: ShaderUniformDataType = 1;
pub const ShaderUniformDataType_SHADER_UNIFORM_VEC3: ShaderUniformDataType = 2;
pub const ShaderUniformDataType_SHADER_UNIFORM_VEC4: ShaderUniformDataType = 3;
pub const ShaderUniformDataType_SHADER_UNIFORM_INT: ShaderUniformDataType = 4;
pub const ShaderUniformDataType_SHADER_UNIFORM_IVEC2: ShaderUniformDataType = 5;
pub const ShaderUniformDataType_SHADER_UNIFORM_IVEC3: ShaderUniformDataType = 6;
pub const ShaderUniformDataType_SHADER_UNIFORM_IVEC4: ShaderUniformDataType = 7;
pub const ShaderUniformDataType_SHADER_UNIFORM_SAMPLER2D: ShaderUniformDataType = 8;
pub type ShaderUniformDataType = ::std::os::raw::c_uint;
pub const ShaderAttributeDataType_SHADER_ATTRIB_FLOAT: ShaderAttributeDataType = 0;
pub const ShaderAttributeDataType_SHADER_ATTRIB_VEC2: ShaderAttributeDataType = 1;
pub const ShaderAttributeDataType_SHADER_ATTRIB_VEC3: ShaderAttributeDataType = 2;
pub const ShaderAttributeDataType_SHADER_ATTRIB_VEC4: ShaderAttributeDataType = 3;
pub type ShaderAttributeDataType = ::std::os::raw::c_uint;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE: PixelFormat = 1;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA: PixelFormat = 2;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R5G6B5: PixelFormat = 3;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R8G8B8: PixelFormat = 4;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1: PixelFormat = 5;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4: PixelFormat = 6;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8: PixelFormat = 7;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R32: PixelFormat = 8;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R32G32B32: PixelFormat = 9;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32: PixelFormat = 10;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R16: PixelFormat = 11;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R16G16B16: PixelFormat = 12;
pub const PixelFormat_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16: PixelFormat = 13;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_DXT1_RGB: PixelFormat = 14;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_DXT1_RGBA: PixelFormat = 15;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_DXT3_RGBA: PixelFormat = 16;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_DXT5_RGBA: PixelFormat = 17;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_ETC1_RGB: PixelFormat = 18;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_ETC2_RGB: PixelFormat = 19;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA: PixelFormat = 20;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_PVRT_RGB: PixelFormat = 21;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_PVRT_RGBA: PixelFormat = 22;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA: PixelFormat = 23;
pub const PixelFormat_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA: PixelFormat = 24;
pub type PixelFormat = ::std::os::raw::c_uint;
pub const TextureFilter_TEXTURE_FILTER_POINT: TextureFilter = 0;
pub const TextureFilter_TEXTURE_FILTER_BILINEAR: TextureFilter = 1;
pub const TextureFilter_TEXTURE_FILTER_TRILINEAR: TextureFilter = 2;
pub const TextureFilter_TEXTURE_FILTER_ANISOTROPIC_4X: TextureFilter = 3;
pub const TextureFilter_TEXTURE_FILTER_ANISOTROPIC_8X: TextureFilter = 4;
pub const TextureFilter_TEXTURE_FILTER_ANISOTROPIC_16X: TextureFilter = 5;
pub type TextureFilter = ::std::os::raw::c_uint;
pub const TextureWrap_TEXTURE_WRAP_REPEAT: TextureWrap = 0;
pub const TextureWrap_TEXTURE_WRAP_CLAMP: TextureWrap = 1;
pub const TextureWrap_TEXTURE_WRAP_MIRROR_REPEAT: TextureWrap = 2;
pub const TextureWrap_TEXTURE_WRAP_MIRROR_CLAMP: TextureWrap = 3;
pub type TextureWrap = ::std::os::raw::c_uint;
pub const CubemapLayout_CUBEMAP_LAYOUT_AUTO_DETECT: CubemapLayout = 0;
pub const CubemapLayout_CUBEMAP_LAYOUT_LINE_VERTICAL: CubemapLayout = 1;
pub const CubemapLayout_CUBEMAP_LAYOUT_LINE_HORIZONTAL: CubemapLayout = 2;
pub const CubemapLayout_CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR: CubemapLayout = 3;
pub const CubemapLayout_CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE: CubemapLayout = 4;
pub const CubemapLayout_CUBEMAP_LAYOUT_PANORAMA: CubemapLayout = 5;
pub type CubemapLayout = ::std::os::raw::c_uint;
pub const FontType_FONT_DEFAULT: FontType = 0;
pub const FontType_FONT_BITMAP: FontType = 1;
pub const FontType_FONT_SDF: FontType = 2;
pub type FontType = ::std::os::raw::c_uint;
pub const BlendMode_BLEND_ALPHA: BlendMode = 0;
pub const BlendMode_BLEND_ADDITIVE: BlendMode = 1;
pub const BlendMode_BLEND_MULTIPLIED: BlendMode = 2;
pub const BlendMode_BLEND_ADD_COLORS: BlendMode = 3;
pub const BlendMode_BLEND_SUBTRACT_COLORS: BlendMode = 4;
pub const BlendMode_BLEND_ALPHA_PREMULTIPLY: BlendMode = 5;
pub const BlendMode_BLEND_CUSTOM: BlendMode = 6;
pub const BlendMode_BLEND_CUSTOM_SEPARATE: BlendMode = 7;
pub type BlendMode = ::std::os::raw::c_uint;
pub const Gesture_GESTURE_NONE: Gesture = 0;
pub const Gesture_GESTURE_TAP: Gesture = 1;
pub const Gesture_GESTURE_DOUBLETAP: Gesture = 2;
pub const Gesture_GESTURE_HOLD: Gesture = 4;
pub const Gesture_GESTURE_DRAG: Gesture = 8;
pub const Gesture_GESTURE_SWIPE_RIGHT: Gesture = 16;
pub const Gesture_GESTURE_SWIPE_LEFT: Gesture = 32;
pub const Gesture_GESTURE_SWIPE_UP: Gesture = 64;
pub const Gesture_GESTURE_SWIPE_DOWN: Gesture = 128;
pub const Gesture_GESTURE_PINCH_IN: Gesture = 256;
pub const Gesture_GESTURE_PINCH_OUT: Gesture = 512;
pub type Gesture = ::std::os::raw::c_uint;
pub const CameraMode_CAMERA_CUSTOM: CameraMode = 0;
pub const CameraMode_CAMERA_FREE: CameraMode = 1;
pub const CameraMode_CAMERA_ORBITAL: CameraMode = 2;
pub const CameraMode_CAMERA_FIRST_PERSON: CameraMode = 3;
pub const CameraMode_CAMERA_THIRD_PERSON: CameraMode = 4;
pub type CameraMode = ::std::os::raw::c_uint;
pub const CameraProjection_CAMERA_PERSPECTIVE: CameraProjection = 0;
pub const CameraProjection_CAMERA_ORTHOGRAPHIC: CameraProjection = 1;
pub type CameraProjection = ::std::os::raw::c_uint;
pub const NPatchLayout_NPATCH_NINE_PATCH: NPatchLayout = 0;
pub const NPatchLayout_NPATCH_THREE_PATCH_VERTICAL: NPatchLayout = 1;
pub const NPatchLayout_NPATCH_THREE_PATCH_HORIZONTAL: NPatchLayout = 2;
pub type NPatchLayout = ::std::os::raw::c_uint;
pub type TraceLogCallback = ::std::option::Option<
    unsafe extern "C" fn(
        logLevel: ::std::os::raw::c_int,
        text: *const ::std::os::raw::c_char,
        args: va_list,
    ),
>;
pub type LoadFileDataCallback = ::std::option::Option<
    unsafe extern "C" fn(
        fileName: *const ::std::os::raw::c_char,
        dataSize: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_uchar,
>;
pub type SaveFileDataCallback = ::std::option::Option<
    unsafe extern "C" fn(
        fileName: *const ::std::os::raw::c_char,
        data: *mut ::std::os::raw::c_void,
        dataSize: ::std::os::raw::c_int,
    ) -> bool,
>;
pub type LoadFileTextCallback = ::std::option::Option<
    unsafe extern "C" fn(fileName: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char,
>;
pub type SaveFileTextCallback = ::std::option::Option<
    unsafe extern "C" fn(
        fileName: *const ::std::os::raw::c_char,
        text: *mut ::std::os::raw::c_char,
    ) -> bool,
>;
pub type AudioCallback = ::std::option::Option<
    unsafe extern "C" fn(bufferData: *mut ::std::os::raw::c_void, frames: ::std::os::raw::c_uint),
>;
pub type __builtin_va_list = *mut ::std::os::raw::c_char;

#[link(name = "raylib")]
extern "C" {
    pub fn InitWindow(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        title: *const ::std::os::raw::c_char,
    );
    pub fn CloseWindow();
    pub fn WindowShouldClose() -> bool;
    pub fn IsWindowReady() -> bool;
    pub fn IsWindowFullscreen() -> bool;
    pub fn IsWindowHidden() -> bool;
    pub fn IsWindowMinimized() -> bool;
    pub fn IsWindowMaximized() -> bool;
    pub fn IsWindowFocused() -> bool;
    pub fn IsWindowResized() -> bool;
    pub fn IsWindowState(flag: ::std::os::raw::c_uint) -> bool;
    pub fn SetWindowState(flags: ::std::os::raw::c_uint);
    pub fn ClearWindowState(flags: ::std::os::raw::c_uint);
    pub fn ToggleFullscreen();
    pub fn ToggleBorderlessWindowed();
    pub fn MaximizeWindow();
    pub fn MinimizeWindow();
    pub fn RestoreWindow();
    pub fn SetWindowIcon(image: Image);
    pub fn SetWindowIcons(images: *mut Image, count: ::std::os::raw::c_int);
    pub fn SetWindowTitle(title: *const ::std::os::raw::c_char);
    pub fn SetWindowPosition(x: ::std::os::raw::c_int, y: ::std::os::raw::c_int);
    pub fn SetWindowMonitor(monitor: ::std::os::raw::c_int);
    pub fn SetWindowMinSize(width: ::std::os::raw::c_int, height: ::std::os::raw::c_int);
    pub fn SetWindowMaxSize(width: ::std::os::raw::c_int, height: ::std::os::raw::c_int);
    pub fn SetWindowSize(width: ::std::os::raw::c_int, height: ::std::os::raw::c_int);
    pub fn SetWindowOpacity(opacity: f32);
    pub fn SetWindowFocused();
    pub fn GetWindowHandle() -> *mut ::std::os::raw::c_void;
    pub fn GetScreenWidth() -> ::std::os::raw::c_int;
    pub fn GetScreenHeight() -> ::std::os::raw::c_int;
    pub fn GetRenderWidth() -> ::std::os::raw::c_int;
    pub fn GetRenderHeight() -> ::std::os::raw::c_int;
    pub fn GetMonitorCount() -> ::std::os::raw::c_int;
    pub fn GetCurrentMonitor() -> ::std::os::raw::c_int;
    pub fn GetMonitorPosition(monitor: ::std::os::raw::c_int) -> Vector2;
    pub fn GetMonitorWidth(monitor: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn GetMonitorHeight(monitor: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn GetMonitorPhysicalWidth(monitor: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn GetMonitorPhysicalHeight(monitor: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn GetMonitorRefreshRate(monitor: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn GetWindowPosition() -> Vector2;
    pub fn GetWindowScaleDPI() -> Vector2;
    pub fn GetMonitorName(monitor: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
    pub fn SetClipboardText(text: *const ::std::os::raw::c_char);
    pub fn GetClipboardText() -> *const ::std::os::raw::c_char;
    pub fn EnableEventWaiting();
    pub fn DisableEventWaiting();
    pub fn ShowCursor();
    pub fn HideCursor();
    pub fn IsCursorHidden() -> bool;
    pub fn EnableCursor();
    pub fn DisableCursor();
    pub fn IsCursorOnScreen() -> bool;
    pub fn ClearBackground(color: Color);
    pub fn BeginDrawing();
    pub fn EndDrawing();
    pub fn BeginMode2D(camera: Camera2D);
    pub fn EndMode2D();
    pub fn BeginMode3D(camera: Camera3D);
    pub fn EndMode3D();
    pub fn BeginTextureMode(target: RenderTexture2D);
    pub fn EndTextureMode();
    pub fn BeginShaderMode(shader: Shader);
    pub fn EndShaderMode();
    pub fn BeginBlendMode(mode: ::std::os::raw::c_int);
    pub fn EndBlendMode();
    pub fn BeginScissorMode(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    );
    pub fn EndScissorMode();
    pub fn BeginVrStereoMode(config: VrStereoConfig);
    pub fn EndVrStereoMode();
    pub fn LoadVrStereoConfig(device: VrDeviceInfo) -> VrStereoConfig;
    pub fn UnloadVrStereoConfig(config: VrStereoConfig);
    pub fn LoadShader(
        vsFileName: *const ::std::os::raw::c_char,
        fsFileName: *const ::std::os::raw::c_char,
    ) -> Shader;
    pub fn LoadShaderFromMemory(
        vsCode: *const ::std::os::raw::c_char,
        fsCode: *const ::std::os::raw::c_char,
    ) -> Shader;
    pub fn IsShaderReady(shader: Shader) -> bool;
    pub fn GetShaderLocation(
        shader: Shader,
        uniformName: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    pub fn GetShaderLocationAttrib(
        shader: Shader,
        attribName: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    pub fn SetShaderValue(
        shader: Shader,
        locIndex: ::std::os::raw::c_int,
        value: *const ::std::os::raw::c_void,
        uniformType: ::std::os::raw::c_int,
    );
    pub fn SetShaderValueV(
        shader: Shader,
        locIndex: ::std::os::raw::c_int,
        value: *const ::std::os::raw::c_void,
        uniformType: ::std::os::raw::c_int,
        count: ::std::os::raw::c_int,
    );
    pub fn SetShaderValueMatrix(shader: Shader, locIndex: ::std::os::raw::c_int, mat: Matrix);
    pub fn SetShaderValueTexture(
        shader: Shader,
        locIndex: ::std::os::raw::c_int,
        texture: Texture2D,
    );
    pub fn UnloadShader(shader: Shader);
    pub fn GetMouseRay(mousePosition: Vector2, camera: Camera) -> Ray;
    pub fn GetCameraMatrix(camera: Camera) -> Matrix;
    pub fn GetCameraMatrix2D(camera: Camera2D) -> Matrix;
    pub fn GetWorldToScreen(position: Vector3, camera: Camera) -> Vector2;
    pub fn GetScreenToWorld2D(position: Vector2, camera: Camera2D) -> Vector2;
    pub fn GetWorldToScreenEx(
        position: Vector3,
        camera: Camera,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    ) -> Vector2;
    pub fn GetWorldToScreen2D(position: Vector2, camera: Camera2D) -> Vector2;
    pub fn SetTargetFPS(fps: ::std::os::raw::c_int);
    pub fn GetFrameTime() -> f32;
    pub fn GetTime() -> f64;
    pub fn GetFPS() -> ::std::os::raw::c_int;
    pub fn SwapScreenBuffer();
    pub fn PollInputEvents();
    pub fn WaitTime(seconds: f64);
    pub fn SetRandomSeed(seed: ::std::os::raw::c_uint);
    pub fn GetRandomValue(
        min: ::std::os::raw::c_int,
        max: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn LoadRandomSequence(
        count: ::std::os::raw::c_uint,
        min: ::std::os::raw::c_int,
        max: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_int;
    pub fn UnloadRandomSequence(sequence: *mut ::std::os::raw::c_int);
    pub fn TakeScreenshot(fileName: *const ::std::os::raw::c_char);
    pub fn SetConfigFlags(flags: ::std::os::raw::c_uint);
    pub fn OpenURL(url: *const ::std::os::raw::c_char);
    pub fn TraceLog(logLevel: ::std::os::raw::c_int, text: *const ::std::os::raw::c_char, ...);
    pub fn SetTraceLogLevel(logLevel: ::std::os::raw::c_int);
    pub fn MemAlloc(size: ::std::os::raw::c_uint) -> *mut ::std::os::raw::c_void;
    pub fn MemRealloc(
        ptr: *mut ::std::os::raw::c_void,
        size: ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void;
    pub fn MemFree(ptr: *mut ::std::os::raw::c_void);
    pub fn SetTraceLogCallback(callback: TraceLogCallback);
    pub fn SetLoadFileDataCallback(callback: LoadFileDataCallback);
    pub fn SetSaveFileDataCallback(callback: SaveFileDataCallback);
    pub fn SetLoadFileTextCallback(callback: LoadFileTextCallback);
    pub fn SetSaveFileTextCallback(callback: SaveFileTextCallback);
    pub fn LoadFileData(
        fileName: *const ::std::os::raw::c_char,
        dataSize: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_uchar;
    pub fn UnloadFileData(data: *mut ::std::os::raw::c_uchar);
    pub fn SaveFileData(
        fileName: *const ::std::os::raw::c_char,
        data: *mut ::std::os::raw::c_void,
        dataSize: ::std::os::raw::c_int,
    ) -> bool;
    pub fn ExportDataAsCode(
        data: *const ::std::os::raw::c_uchar,
        dataSize: ::std::os::raw::c_int,
        fileName: *const ::std::os::raw::c_char,
    ) -> bool;
    pub fn LoadFileText(fileName: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
    pub fn UnloadFileText(text: *mut ::std::os::raw::c_char);
    pub fn SaveFileText(
        fileName: *const ::std::os::raw::c_char,
        text: *mut ::std::os::raw::c_char,
    ) -> bool;
    pub fn FileExists(fileName: *const ::std::os::raw::c_char) -> bool;
    pub fn DirectoryExists(dirPath: *const ::std::os::raw::c_char) -> bool;
    pub fn IsFileExtension(
        fileName: *const ::std::os::raw::c_char,
        ext: *const ::std::os::raw::c_char,
    ) -> bool;
    pub fn GetFileLength(fileName: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
    pub fn GetFileExtension(
        fileName: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
    pub fn GetFileName(filePath: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
    pub fn GetFileNameWithoutExt(
        filePath: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
    pub fn GetDirectoryPath(
        filePath: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
    pub fn GetPrevDirectoryPath(
        dirPath: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
    pub fn GetWorkingDirectory() -> *const ::std::os::raw::c_char;
    pub fn GetApplicationDirectory() -> *const ::std::os::raw::c_char;
    pub fn ChangeDirectory(dir: *const ::std::os::raw::c_char) -> bool;
    pub fn IsPathFile(path: *const ::std::os::raw::c_char) -> bool;
    pub fn LoadDirectoryFiles(dirPath: *const ::std::os::raw::c_char) -> FilePathList;
    pub fn LoadDirectoryFilesEx(
        basePath: *const ::std::os::raw::c_char,
        filter: *const ::std::os::raw::c_char,
        scanSubdirs: bool,
    ) -> FilePathList;
    pub fn UnloadDirectoryFiles(files: FilePathList);
    pub fn IsFileDropped() -> bool;
    pub fn LoadDroppedFiles() -> FilePathList;
    pub fn UnloadDroppedFiles(files: FilePathList);
    pub fn GetFileModTime(fileName: *const ::std::os::raw::c_char) -> ::std::os::raw::c_long;
    pub fn CompressData(
        data: *const ::std::os::raw::c_uchar,
        dataSize: ::std::os::raw::c_int,
        compDataSize: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_uchar;
    pub fn DecompressData(
        compData: *const ::std::os::raw::c_uchar,
        compDataSize: ::std::os::raw::c_int,
        dataSize: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_uchar;
    pub fn EncodeDataBase64(
        data: *const ::std::os::raw::c_uchar,
        dataSize: ::std::os::raw::c_int,
        outputSize: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
    pub fn DecodeDataBase64(
        data: *const ::std::os::raw::c_uchar,
        outputSize: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_uchar;
    pub fn LoadAutomationEventList(fileName: *const ::std::os::raw::c_char) -> AutomationEventList;
    pub fn UnloadAutomationEventList(list: *mut AutomationEventList);
    pub fn ExportAutomationEventList(
        list: AutomationEventList,
        fileName: *const ::std::os::raw::c_char,
    ) -> bool;
    pub fn SetAutomationEventList(list: *mut AutomationEventList);
    pub fn SetAutomationEventBaseFrame(frame: ::std::os::raw::c_int);
    pub fn StartAutomationEventRecording();
    pub fn StopAutomationEventRecording();
    pub fn PlayAutomationEvent(event: AutomationEvent);
    pub fn IsKeyPressed(key: ::std::os::raw::c_int) -> bool;
    pub fn IsKeyPressedRepeat(key: ::std::os::raw::c_int) -> bool;
    pub fn IsKeyDown(key: ::std::os::raw::c_int) -> bool;
    pub fn IsKeyReleased(key: ::std::os::raw::c_int) -> bool;
    pub fn IsKeyUp(key: ::std::os::raw::c_int) -> bool;
    pub fn GetKeyPressed() -> ::std::os::raw::c_int;
    pub fn GetCharPressed() -> ::std::os::raw::c_int;
    pub fn SetExitKey(key: ::std::os::raw::c_int);
    pub fn IsGamepadAvailable(gamepad: ::std::os::raw::c_int) -> bool;
    pub fn GetGamepadName(gamepad: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
    pub fn IsGamepadButtonPressed(
        gamepad: ::std::os::raw::c_int,
        button: ::std::os::raw::c_int,
    ) -> bool;
    pub fn IsGamepadButtonDown(
        gamepad: ::std::os::raw::c_int,
        button: ::std::os::raw::c_int,
    ) -> bool;
    pub fn IsGamepadButtonReleased(
        gamepad: ::std::os::raw::c_int,
        button: ::std::os::raw::c_int,
    ) -> bool;
    pub fn IsGamepadButtonUp(gamepad: ::std::os::raw::c_int, button: ::std::os::raw::c_int)
        -> bool;
    pub fn GetGamepadButtonPressed() -> ::std::os::raw::c_int;
    pub fn GetGamepadAxisCount(gamepad: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn GetGamepadAxisMovement(
        gamepad: ::std::os::raw::c_int,
        axis: ::std::os::raw::c_int,
    ) -> f32;
    pub fn SetGamepadMappings(mappings: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
    pub fn IsMouseButtonPressed(button: ::std::os::raw::c_int) -> bool;
    pub fn IsMouseButtonDown(button: ::std::os::raw::c_int) -> bool;
    pub fn IsMouseButtonReleased(button: ::std::os::raw::c_int) -> bool;
    pub fn IsMouseButtonUp(button: ::std::os::raw::c_int) -> bool;
    pub fn GetMouseX() -> ::std::os::raw::c_int;
    pub fn GetMouseY() -> ::std::os::raw::c_int;
    pub fn GetMousePosition() -> Vector2;
    pub fn GetMouseDelta() -> Vector2;
    pub fn SetMousePosition(x: ::std::os::raw::c_int, y: ::std::os::raw::c_int);
    pub fn SetMouseOffset(offsetX: ::std::os::raw::c_int, offsetY: ::std::os::raw::c_int);
    pub fn SetMouseScale(scaleX: f32, scaleY: f32);
    pub fn GetMouseWheelMove() -> f32;
    pub fn GetMouseWheelMoveV() -> Vector2;
    pub fn SetMouseCursor(cursor: ::std::os::raw::c_int);
    pub fn GetTouchX() -> ::std::os::raw::c_int;
    pub fn GetTouchY() -> ::std::os::raw::c_int;
    pub fn GetTouchPosition(index: ::std::os::raw::c_int) -> Vector2;
    pub fn GetTouchPointId(index: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn GetTouchPointCount() -> ::std::os::raw::c_int;
    pub fn SetGesturesEnabled(flags: ::std::os::raw::c_uint);
    pub fn IsGestureDetected(gesture: ::std::os::raw::c_uint) -> bool;
    pub fn GetGestureDetected() -> ::std::os::raw::c_int;
    pub fn GetGestureHoldDuration() -> f32;
    pub fn GetGestureDragVector() -> Vector2;
    pub fn GetGestureDragAngle() -> f32;
    pub fn GetGesturePinchVector() -> Vector2;
    pub fn GetGesturePinchAngle() -> f32;
    pub fn UpdateCamera(camera: *mut Camera, mode: ::std::os::raw::c_int);
    pub fn UpdateCameraPro(camera: *mut Camera, movement: Vector3, rotation: Vector3, zoom: f32);
    pub fn SetShapesTexture(texture: Texture2D, source: Rectangle);
    pub fn DrawPixel(posX: ::std::os::raw::c_int, posY: ::std::os::raw::c_int, color: Color);
    pub fn DrawPixelV(position: Vector2, color: Color);
    pub fn DrawLine(
        startPosX: ::std::os::raw::c_int,
        startPosY: ::std::os::raw::c_int,
        endPosX: ::std::os::raw::c_int,
        endPosY: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawLineV(startPos: Vector2, endPos: Vector2, color: Color);
    pub fn DrawLineEx(startPos: Vector2, endPos: Vector2, thick: f32, color: Color);
    pub fn DrawLineStrip(points: *mut Vector2, pointCount: ::std::os::raw::c_int, color: Color);
    pub fn DrawLineBezier(startPos: Vector2, endPos: Vector2, thick: f32, color: Color);
    pub fn DrawCircle(
        centerX: ::std::os::raw::c_int,
        centerY: ::std::os::raw::c_int,
        radius: f32,
        color: Color,
    );
    pub fn DrawCircleSector(
        center: Vector2,
        radius: f32,
        startAngle: f32,
        endAngle: f32,
        segments: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawCircleSectorLines(
        center: Vector2,
        radius: f32,
        startAngle: f32,
        endAngle: f32,
        segments: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawCircleGradient(
        centerX: ::std::os::raw::c_int,
        centerY: ::std::os::raw::c_int,
        radius: f32,
        color1: Color,
        color2: Color,
    );
    pub fn DrawCircleV(center: Vector2, radius: f32, color: Color);
    pub fn DrawCircleLines(
        centerX: ::std::os::raw::c_int,
        centerY: ::std::os::raw::c_int,
        radius: f32,
        color: Color,
    );
    pub fn DrawCircleLinesV(center: Vector2, radius: f32, color: Color);
    pub fn DrawEllipse(
        centerX: ::std::os::raw::c_int,
        centerY: ::std::os::raw::c_int,
        radiusH: f32,
        radiusV: f32,
        color: Color,
    );
    pub fn DrawEllipseLines(
        centerX: ::std::os::raw::c_int,
        centerY: ::std::os::raw::c_int,
        radiusH: f32,
        radiusV: f32,
        color: Color,
    );
    pub fn DrawRing(
        center: Vector2,
        innerRadius: f32,
        outerRadius: f32,
        startAngle: f32,
        endAngle: f32,
        segments: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawRingLines(
        center: Vector2,
        innerRadius: f32,
        outerRadius: f32,
        startAngle: f32,
        endAngle: f32,
        segments: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawRectangle(
        posX: ::std::os::raw::c_int,
        posY: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawRectangleV(position: Vector2, size: Vector2, color: Color);
    pub fn DrawRectangleRec(rec: Rectangle, color: Color);
    pub fn DrawRectanglePro(rec: Rectangle, origin: Vector2, rotation: f32, color: Color);
    pub fn DrawRectangleGradientV(
        posX: ::std::os::raw::c_int,
        posY: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        color1: Color,
        color2: Color,
    );
    pub fn DrawRectangleGradientH(
        posX: ::std::os::raw::c_int,
        posY: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        color1: Color,
        color2: Color,
    );
    pub fn DrawRectangleGradientEx(
        rec: Rectangle,
        col1: Color,
        col2: Color,
        col3: Color,
        col4: Color,
    );
    pub fn DrawRectangleLines(
        posX: ::std::os::raw::c_int,
        posY: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawRectangleLinesEx(rec: Rectangle, lineThick: f32, color: Color);
    pub fn DrawRectangleRounded(
        rec: Rectangle,
        roundness: f32,
        segments: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawRectangleRoundedLines(
        rec: Rectangle,
        roundness: f32,
        segments: ::std::os::raw::c_int,
        lineThick: f32,
        color: Color,
    );
    pub fn DrawTriangle(v1: Vector2, v2: Vector2, v3: Vector2, color: Color);
    pub fn DrawTriangleLines(v1: Vector2, v2: Vector2, v3: Vector2, color: Color);
    pub fn DrawTriangleFan(points: *mut Vector2, pointCount: ::std::os::raw::c_int, color: Color);
    pub fn DrawTriangleStrip(points: *mut Vector2, pointCount: ::std::os::raw::c_int, color: Color);
    pub fn DrawPoly(
        center: Vector2,
        sides: ::std::os::raw::c_int,
        radius: f32,
        rotation: f32,
        color: Color,
    );
    pub fn DrawPolyLines(
        center: Vector2,
        sides: ::std::os::raw::c_int,
        radius: f32,
        rotation: f32,
        color: Color,
    );
    pub fn DrawPolyLinesEx(
        center: Vector2,
        sides: ::std::os::raw::c_int,
        radius: f32,
        rotation: f32,
        lineThick: f32,
        color: Color,
    );
    pub fn DrawSplineLinear(
        points: *mut Vector2,
        pointCount: ::std::os::raw::c_int,
        thick: f32,
        color: Color,
    );
    pub fn DrawSplineBasis(
        points: *mut Vector2,
        pointCount: ::std::os::raw::c_int,
        thick: f32,
        color: Color,
    );
    pub fn DrawSplineCatmullRom(
        points: *mut Vector2,
        pointCount: ::std::os::raw::c_int,
        thick: f32,
        color: Color,
    );
    pub fn DrawSplineBezierQuadratic(
        points: *mut Vector2,
        pointCount: ::std::os::raw::c_int,
        thick: f32,
        color: Color,
    );
    pub fn DrawSplineBezierCubic(
        points: *mut Vector2,
        pointCount: ::std::os::raw::c_int,
        thick: f32,
        color: Color,
    );
    pub fn DrawSplineSegmentLinear(p1: Vector2, p2: Vector2, thick: f32, color: Color);
    pub fn DrawSplineSegmentBasis(
        p1: Vector2,
        p2: Vector2,
        p3: Vector2,
        p4: Vector2,
        thick: f32,
        color: Color,
    );
    pub fn DrawSplineSegmentCatmullRom(
        p1: Vector2,
        p2: Vector2,
        p3: Vector2,
        p4: Vector2,
        thick: f32,
        color: Color,
    );
    pub fn DrawSplineSegmentBezierQuadratic(
        p1: Vector2,
        c2: Vector2,
        p3: Vector2,
        thick: f32,
        color: Color,
    );
    pub fn DrawSplineSegmentBezierCubic(
        p1: Vector2,
        c2: Vector2,
        c3: Vector2,
        p4: Vector2,
        thick: f32,
        color: Color,
    );
    pub fn GetSplinePointLinear(startPos: Vector2, endPos: Vector2, t: f32) -> Vector2;
    pub fn GetSplinePointBasis(
        p1: Vector2,
        p2: Vector2,
        p3: Vector2,
        p4: Vector2,
        t: f32,
    ) -> Vector2;
    pub fn GetSplinePointCatmullRom(
        p1: Vector2,
        p2: Vector2,
        p3: Vector2,
        p4: Vector2,
        t: f32,
    ) -> Vector2;
    pub fn GetSplinePointBezierQuad(p1: Vector2, c2: Vector2, p3: Vector2, t: f32) -> Vector2;
    pub fn GetSplinePointBezierCubic(
        p1: Vector2,
        c2: Vector2,
        c3: Vector2,
        p4: Vector2,
        t: f32,
    ) -> Vector2;
    pub fn CheckCollisionRecs(rec1: Rectangle, rec2: Rectangle) -> bool;
    pub fn CheckCollisionCircles(
        center1: Vector2,
        radius1: f32,
        center2: Vector2,
        radius2: f32,
    ) -> bool;
    pub fn CheckCollisionCircleRec(center: Vector2, radius: f32, rec: Rectangle) -> bool;
    pub fn CheckCollisionPointRec(point: Vector2, rec: Rectangle) -> bool;
    pub fn CheckCollisionPointCircle(point: Vector2, center: Vector2, radius: f32) -> bool;
    pub fn CheckCollisionPointTriangle(
        point: Vector2,
        p1: Vector2,
        p2: Vector2,
        p3: Vector2,
    ) -> bool;
    pub fn CheckCollisionPointPoly(
        point: Vector2,
        points: *mut Vector2,
        pointCount: ::std::os::raw::c_int,
    ) -> bool;
    pub fn CheckCollisionLines(
        startPos1: Vector2,
        endPos1: Vector2,
        startPos2: Vector2,
        endPos2: Vector2,
        collisionPoint: *mut Vector2,
    ) -> bool;
    pub fn CheckCollisionPointLine(
        point: Vector2,
        p1: Vector2,
        p2: Vector2,
        threshold: ::std::os::raw::c_int,
    ) -> bool;
    pub fn GetCollisionRec(rec1: Rectangle, rec2: Rectangle) -> Rectangle;
    pub fn LoadImage(fileName: *const ::std::os::raw::c_char) -> Image;
    pub fn LoadImageRaw(
        fileName: *const ::std::os::raw::c_char,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        format: ::std::os::raw::c_int,
        headerSize: ::std::os::raw::c_int,
    ) -> Image;
    pub fn LoadImageSvg(
        fileNameOrString: *const ::std::os::raw::c_char,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    ) -> Image;
    pub fn LoadImageAnim(
        fileName: *const ::std::os::raw::c_char,
        frames: *mut ::std::os::raw::c_int,
    ) -> Image;
    pub fn LoadImageFromMemory(
        fileType: *const ::std::os::raw::c_char,
        fileData: *const ::std::os::raw::c_uchar,
        dataSize: ::std::os::raw::c_int,
    ) -> Image;
    pub fn LoadImageFromTexture(texture: Texture2D) -> Image;
    pub fn LoadImageFromScreen() -> Image;
    pub fn IsImageReady(image: Image) -> bool;
    pub fn UnloadImage(image: Image);
    pub fn ExportImage(image: Image, fileName: *const ::std::os::raw::c_char) -> bool;
    pub fn ExportImageToMemory(
        image: Image,
        fileType: *const ::std::os::raw::c_char,
        fileSize: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_uchar;
    pub fn ExportImageAsCode(image: Image, fileName: *const ::std::os::raw::c_char) -> bool;
    pub fn GenImageColor(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        color: Color,
    ) -> Image;
    pub fn GenImageGradientLinear(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        direction: ::std::os::raw::c_int,
        start: Color,
        end: Color,
    ) -> Image;
    pub fn GenImageGradientRadial(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        density: f32,
        inner: Color,
        outer: Color,
    ) -> Image;
    pub fn GenImageGradientSquare(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        density: f32,
        inner: Color,
        outer: Color,
    ) -> Image;
    pub fn GenImageChecked(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        checksX: ::std::os::raw::c_int,
        checksY: ::std::os::raw::c_int,
        col1: Color,
        col2: Color,
    ) -> Image;
    pub fn GenImageWhiteNoise(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        factor: f32,
    ) -> Image;
    pub fn GenImagePerlinNoise(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        offsetX: ::std::os::raw::c_int,
        offsetY: ::std::os::raw::c_int,
        scale: f32,
    ) -> Image;
    pub fn GenImageCellular(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        tileSize: ::std::os::raw::c_int,
    ) -> Image;
    pub fn GenImageText(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        text: *const ::std::os::raw::c_char,
    ) -> Image;
    pub fn ImageCopy(image: Image) -> Image;
    pub fn ImageFromImage(image: Image, rec: Rectangle) -> Image;
    pub fn ImageText(
        text: *const ::std::os::raw::c_char,
        fontSize: ::std::os::raw::c_int,
        color: Color,
    ) -> Image;
    pub fn ImageTextEx(
        font: Font,
        text: *const ::std::os::raw::c_char,
        fontSize: f32,
        spacing: f32,
        tint: Color,
    ) -> Image;
    pub fn ImageFormat(image: *mut Image, newFormat: ::std::os::raw::c_int);
    pub fn ImageToPOT(image: *mut Image, fill: Color);
    pub fn ImageCrop(image: *mut Image, crop: Rectangle);
    pub fn ImageAlphaCrop(image: *mut Image, threshold: f32);
    pub fn ImageAlphaClear(image: *mut Image, color: Color, threshold: f32);
    pub fn ImageAlphaMask(image: *mut Image, alphaMask: Image);
    pub fn ImageAlphaPremultiply(image: *mut Image);
    pub fn ImageBlurGaussian(image: *mut Image, blurSize: ::std::os::raw::c_int);
    pub fn ImageResize(
        image: *mut Image,
        newWidth: ::std::os::raw::c_int,
        newHeight: ::std::os::raw::c_int,
    );
    pub fn ImageResizeNN(
        image: *mut Image,
        newWidth: ::std::os::raw::c_int,
        newHeight: ::std::os::raw::c_int,
    );
    pub fn ImageResizeCanvas(
        image: *mut Image,
        newWidth: ::std::os::raw::c_int,
        newHeight: ::std::os::raw::c_int,
        offsetX: ::std::os::raw::c_int,
        offsetY: ::std::os::raw::c_int,
        fill: Color,
    );
    pub fn ImageMipmaps(image: *mut Image);
    pub fn ImageDither(
        image: *mut Image,
        rBpp: ::std::os::raw::c_int,
        gBpp: ::std::os::raw::c_int,
        bBpp: ::std::os::raw::c_int,
        aBpp: ::std::os::raw::c_int,
    );
    pub fn ImageFlipVertical(image: *mut Image);
    pub fn ImageFlipHorizontal(image: *mut Image);
    pub fn ImageRotate(image: *mut Image, degrees: ::std::os::raw::c_int);
    pub fn ImageRotateCW(image: *mut Image);
    pub fn ImageRotateCCW(image: *mut Image);
    pub fn ImageColorTint(image: *mut Image, color: Color);
    pub fn ImageColorInvert(image: *mut Image);
    pub fn ImageColorGrayscale(image: *mut Image);
    pub fn ImageColorContrast(image: *mut Image, contrast: f32);
    pub fn ImageColorBrightness(image: *mut Image, brightness: ::std::os::raw::c_int);
    pub fn ImageColorReplace(image: *mut Image, color: Color, replace: Color);
    pub fn LoadImageColors(image: Image) -> *mut Color;
    pub fn LoadImagePalette(
        image: Image,
        maxPaletteSize: ::std::os::raw::c_int,
        colorCount: *mut ::std::os::raw::c_int,
    ) -> *mut Color;
    pub fn UnloadImageColors(colors: *mut Color);
    pub fn UnloadImagePalette(colors: *mut Color);
    pub fn GetImageAlphaBorder(image: Image, threshold: f32) -> Rectangle;
    pub fn GetImageColor(image: Image, x: ::std::os::raw::c_int, y: ::std::os::raw::c_int)
        -> Color;
    pub fn ImageClearBackground(dst: *mut Image, color: Color);
    pub fn ImageDrawPixel(
        dst: *mut Image,
        posX: ::std::os::raw::c_int,
        posY: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn ImageDrawPixelV(dst: *mut Image, position: Vector2, color: Color);
    pub fn ImageDrawLine(
        dst: *mut Image,
        startPosX: ::std::os::raw::c_int,
        startPosY: ::std::os::raw::c_int,
        endPosX: ::std::os::raw::c_int,
        endPosY: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn ImageDrawLineV(dst: *mut Image, start: Vector2, end: Vector2, color: Color);
    pub fn ImageDrawCircle(
        dst: *mut Image,
        centerX: ::std::os::raw::c_int,
        centerY: ::std::os::raw::c_int,
        radius: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn ImageDrawCircleV(
        dst: *mut Image,
        center: Vector2,
        radius: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn ImageDrawCircleLines(
        dst: *mut Image,
        centerX: ::std::os::raw::c_int,
        centerY: ::std::os::raw::c_int,
        radius: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn ImageDrawCircleLinesV(
        dst: *mut Image,
        center: Vector2,
        radius: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn ImageDrawRectangle(
        dst: *mut Image,
        posX: ::std::os::raw::c_int,
        posY: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn ImageDrawRectangleV(dst: *mut Image, position: Vector2, size: Vector2, color: Color);
    pub fn ImageDrawRectangleRec(dst: *mut Image, rec: Rectangle, color: Color);
    pub fn ImageDrawRectangleLines(
        dst: *mut Image,
        rec: Rectangle,
        thick: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn ImageDraw(
        dst: *mut Image,
        src: Image,
        srcRec: Rectangle,
        dstRec: Rectangle,
        tint: Color,
    );
    pub fn ImageDrawText(
        dst: *mut Image,
        text: *const ::std::os::raw::c_char,
        posX: ::std::os::raw::c_int,
        posY: ::std::os::raw::c_int,
        fontSize: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn ImageDrawTextEx(
        dst: *mut Image,
        font: Font,
        text: *const ::std::os::raw::c_char,
        position: Vector2,
        fontSize: f32,
        spacing: f32,
        tint: Color,
    );
    pub fn LoadTexture(fileName: *const ::std::os::raw::c_char) -> Texture2D;
    pub fn LoadTextureFromImage(image: Image) -> Texture2D;
    pub fn LoadTextureCubemap(image: Image, layout: ::std::os::raw::c_int) -> TextureCubemap;
    pub fn LoadRenderTexture(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    ) -> RenderTexture2D;
    pub fn IsTextureReady(texture: Texture2D) -> bool;
    pub fn UnloadTexture(texture: Texture2D);
    pub fn IsRenderTextureReady(target: RenderTexture2D) -> bool;
    pub fn UnloadRenderTexture(target: RenderTexture2D);
    pub fn UpdateTexture(texture: Texture2D, pixels: *const ::std::os::raw::c_void);
    pub fn UpdateTextureRec(
        texture: Texture2D,
        rec: Rectangle,
        pixels: *const ::std::os::raw::c_void,
    );
    pub fn GenTextureMipmaps(texture: *mut Texture2D);
    pub fn SetTextureFilter(texture: Texture2D, filter: ::std::os::raw::c_int);
    pub fn SetTextureWrap(texture: Texture2D, wrap: ::std::os::raw::c_int);
    pub fn DrawTexture(
        texture: Texture2D,
        posX: ::std::os::raw::c_int,
        posY: ::std::os::raw::c_int,
        tint: Color,
    );
    pub fn DrawTextureV(texture: Texture2D, position: Vector2, tint: Color);
    pub fn DrawTextureEx(
        texture: Texture2D,
        position: Vector2,
        rotation: f32,
        scale: f32,
        tint: Color,
    );
    pub fn DrawTextureRec(texture: Texture2D, source: Rectangle, position: Vector2, tint: Color);
    pub fn DrawTexturePro(
        texture: Texture2D,
        source: Rectangle,
        dest: Rectangle,
        origin: Vector2,
        rotation: f32,
        tint: Color,
    );
    pub fn DrawTextureNPatch(
        texture: Texture2D,
        nPatchInfo: NPatchInfo,
        dest: Rectangle,
        origin: Vector2,
        rotation: f32,
        tint: Color,
    );
    pub fn Fade(color: Color, alpha: f32) -> Color;
    pub fn ColorToInt(color: Color) -> ::std::os::raw::c_int;
    pub fn ColorNormalize(color: Color) -> Vector4;
    pub fn ColorFromNormalized(normalized: Vector4) -> Color;
    pub fn ColorToHSV(color: Color) -> Vector3;
    pub fn ColorFromHSV(hue: f32, saturation: f32, value: f32) -> Color;
    pub fn ColorTint(color: Color, tint: Color) -> Color;
    pub fn ColorBrightness(color: Color, factor: f32) -> Color;
    pub fn ColorContrast(color: Color, contrast: f32) -> Color;
    pub fn ColorAlpha(color: Color, alpha: f32) -> Color;
    pub fn ColorAlphaBlend(dst: Color, src: Color, tint: Color) -> Color;
    pub fn GetColor(hexValue: ::std::os::raw::c_uint) -> Color;
    pub fn GetPixelColor(
        srcPtr: *mut ::std::os::raw::c_void,
        format: ::std::os::raw::c_int,
    ) -> Color;
    pub fn SetPixelColor(
        dstPtr: *mut ::std::os::raw::c_void,
        color: Color,
        format: ::std::os::raw::c_int,
    );
    pub fn GetPixelDataSize(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        format: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn GetFontDefault() -> Font;
    pub fn LoadFont(fileName: *const ::std::os::raw::c_char) -> Font;
    pub fn LoadFontEx(
        fileName: *const ::std::os::raw::c_char,
        fontSize: ::std::os::raw::c_int,
        codepoints: *mut ::std::os::raw::c_int,
        codepointCount: ::std::os::raw::c_int,
    ) -> Font;
    pub fn LoadFontFromImage(image: Image, key: Color, firstChar: ::std::os::raw::c_int) -> Font;
    pub fn LoadFontFromMemory(
        fileType: *const ::std::os::raw::c_char,
        fileData: *const ::std::os::raw::c_uchar,
        dataSize: ::std::os::raw::c_int,
        fontSize: ::std::os::raw::c_int,
        codepoints: *mut ::std::os::raw::c_int,
        codepointCount: ::std::os::raw::c_int,
    ) -> Font;
    pub fn IsFontReady(font: Font) -> bool;
    pub fn LoadFontData(
        fileData: *const ::std::os::raw::c_uchar,
        dataSize: ::std::os::raw::c_int,
        fontSize: ::std::os::raw::c_int,
        codepoints: *mut ::std::os::raw::c_int,
        codepointCount: ::std::os::raw::c_int,
        type_: ::std::os::raw::c_int,
    ) -> *mut GlyphInfo;
    pub fn GenImageFontAtlas(
        glyphs: *const GlyphInfo,
        glyphRecs: *mut *mut Rectangle,
        glyphCount: ::std::os::raw::c_int,
        fontSize: ::std::os::raw::c_int,
        padding: ::std::os::raw::c_int,
        packMethod: ::std::os::raw::c_int,
    ) -> Image;
    pub fn UnloadFontData(glyphs: *mut GlyphInfo, glyphCount: ::std::os::raw::c_int);
    pub fn UnloadFont(font: Font);
    pub fn ExportFontAsCode(font: Font, fileName: *const ::std::os::raw::c_char) -> bool;
    pub fn DrawFPS(posX: ::std::os::raw::c_int, posY: ::std::os::raw::c_int);
    pub fn DrawText(
        text: *const ::std::os::raw::c_char,
        posX: ::std::os::raw::c_int,
        posY: ::std::os::raw::c_int,
        fontSize: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawTextEx(
        font: Font,
        text: *const ::std::os::raw::c_char,
        position: Vector2,
        fontSize: f32,
        spacing: f32,
        tint: Color,
    );
    pub fn DrawTextPro(
        font: Font,
        text: *const ::std::os::raw::c_char,
        position: Vector2,
        origin: Vector2,
        rotation: f32,
        fontSize: f32,
        spacing: f32,
        tint: Color,
    );
    pub fn DrawTextCodepoint(
        font: Font,
        codepoint: ::std::os::raw::c_int,
        position: Vector2,
        fontSize: f32,
        tint: Color,
    );
    pub fn DrawTextCodepoints(
        font: Font,
        codepoints: *const ::std::os::raw::c_int,
        codepointCount: ::std::os::raw::c_int,
        position: Vector2,
        fontSize: f32,
        spacing: f32,
        tint: Color,
    );
    pub fn SetTextLineSpacing(spacing: ::std::os::raw::c_int);
    pub fn MeasureText(
        text: *const ::std::os::raw::c_char,
        fontSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn MeasureTextEx(
        font: Font,
        text: *const ::std::os::raw::c_char,
        fontSize: f32,
        spacing: f32,
    ) -> Vector2;
    pub fn GetGlyphIndex(font: Font, codepoint: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn GetGlyphInfo(font: Font, codepoint: ::std::os::raw::c_int) -> GlyphInfo;
    pub fn GetGlyphAtlasRec(font: Font, codepoint: ::std::os::raw::c_int) -> Rectangle;
    pub fn LoadUTF8(
        codepoints: *const ::std::os::raw::c_int,
        length: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
    pub fn UnloadUTF8(text: *mut ::std::os::raw::c_char);
    pub fn LoadCodepoints(
        text: *const ::std::os::raw::c_char,
        count: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_int;
    pub fn UnloadCodepoints(codepoints: *mut ::std::os::raw::c_int);
    pub fn GetCodepointCount(text: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
    pub fn GetCodepoint(
        text: *const ::std::os::raw::c_char,
        codepointSize: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn GetCodepointNext(
        text: *const ::std::os::raw::c_char,
        codepointSize: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn GetCodepointPrevious(
        text: *const ::std::os::raw::c_char,
        codepointSize: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn CodepointToUTF8(
        codepoint: ::std::os::raw::c_int,
        utf8Size: *mut ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
    pub fn TextCopy(
        dst: *mut ::std::os::raw::c_char,
        src: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    pub fn TextIsEqual(
        text1: *const ::std::os::raw::c_char,
        text2: *const ::std::os::raw::c_char,
    ) -> bool;
    pub fn TextLength(text: *const ::std::os::raw::c_char) -> ::std::os::raw::c_uint;
    pub fn TextFormat(text: *const ::std::os::raw::c_char, ...) -> *const ::std::os::raw::c_char;
    pub fn TextSubtext(
        text: *const ::std::os::raw::c_char,
        position: ::std::os::raw::c_int,
        length: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
    pub fn TextReplace(
        text: *mut ::std::os::raw::c_char,
        replace: *const ::std::os::raw::c_char,
        by: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
    pub fn TextInsert(
        text: *const ::std::os::raw::c_char,
        insert: *const ::std::os::raw::c_char,
        position: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
    pub fn TextJoin(
        textList: *mut *const ::std::os::raw::c_char,
        count: ::std::os::raw::c_int,
        delimiter: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
    pub fn TextSplit(
        text: *const ::std::os::raw::c_char,
        delimiter: ::std::os::raw::c_char,
        count: *mut ::std::os::raw::c_int,
    ) -> *mut *const ::std::os::raw::c_char;
    pub fn TextAppend(
        text: *mut ::std::os::raw::c_char,
        append: *const ::std::os::raw::c_char,
        position: *mut ::std::os::raw::c_int,
    );
    pub fn TextFindIndex(
        text: *const ::std::os::raw::c_char,
        find: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    pub fn TextToUpper(text: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
    pub fn TextToLower(text: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
    pub fn TextToPascal(text: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
    pub fn TextToInteger(text: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
    pub fn DrawLine3D(startPos: Vector3, endPos: Vector3, color: Color);
    pub fn DrawPoint3D(position: Vector3, color: Color);
    pub fn DrawCircle3D(
        center: Vector3,
        radius: f32,
        rotationAxis: Vector3,
        rotationAngle: f32,
        color: Color,
    );
    pub fn DrawTriangle3D(v1: Vector3, v2: Vector3, v3: Vector3, color: Color);
    pub fn DrawTriangleStrip3D(
        points: *mut Vector3,
        pointCount: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawCube(position: Vector3, width: f32, height: f32, length: f32, color: Color);
    pub fn DrawCubeV(position: Vector3, size: Vector3, color: Color);
    pub fn DrawCubeWires(position: Vector3, width: f32, height: f32, length: f32, color: Color);
    pub fn DrawCubeWiresV(position: Vector3, size: Vector3, color: Color);
    pub fn DrawSphere(centerPos: Vector3, radius: f32, color: Color);
    pub fn DrawSphereEx(
        centerPos: Vector3,
        radius: f32,
        rings: ::std::os::raw::c_int,
        slices: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawSphereWires(
        centerPos: Vector3,
        radius: f32,
        rings: ::std::os::raw::c_int,
        slices: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawCylinder(
        position: Vector3,
        radiusTop: f32,
        radiusBottom: f32,
        height: f32,
        slices: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawCylinderEx(
        startPos: Vector3,
        endPos: Vector3,
        startRadius: f32,
        endRadius: f32,
        sides: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawCylinderWires(
        position: Vector3,
        radiusTop: f32,
        radiusBottom: f32,
        height: f32,
        slices: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawCylinderWiresEx(
        startPos: Vector3,
        endPos: Vector3,
        startRadius: f32,
        endRadius: f32,
        sides: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawCapsule(
        startPos: Vector3,
        endPos: Vector3,
        radius: f32,
        slices: ::std::os::raw::c_int,
        rings: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawCapsuleWires(
        startPos: Vector3,
        endPos: Vector3,
        radius: f32,
        slices: ::std::os::raw::c_int,
        rings: ::std::os::raw::c_int,
        color: Color,
    );
    pub fn DrawPlane(centerPos: Vector3, size: Vector2, color: Color);
    pub fn DrawRay(ray: Ray, color: Color);
    pub fn DrawGrid(slices: ::std::os::raw::c_int, spacing: f32);
    pub fn LoadModel(fileName: *const ::std::os::raw::c_char) -> Model;
    pub fn LoadModelFromMesh(mesh: Mesh) -> Model;
    pub fn IsModelReady(model: Model) -> bool;
    pub fn UnloadModel(model: Model);
    pub fn GetModelBoundingBox(model: Model) -> BoundingBox;
    pub fn DrawModel(model: Model, position: Vector3, scale: f32, tint: Color);
    pub fn DrawModelEx(
        model: Model,
        position: Vector3,
        rotationAxis: Vector3,
        rotationAngle: f32,
        scale: Vector3,
        tint: Color,
    );
    pub fn DrawModelWires(model: Model, position: Vector3, scale: f32, tint: Color);
    pub fn DrawModelWiresEx(
        model: Model,
        position: Vector3,
        rotationAxis: Vector3,
        rotationAngle: f32,
        scale: Vector3,
        tint: Color,
    );
    pub fn DrawBoundingBox(box_: BoundingBox, color: Color);
    pub fn DrawBillboard(
        camera: Camera,
        texture: Texture2D,
        position: Vector3,
        size: f32,
        tint: Color,
    );
    pub fn DrawBillboardRec(
        camera: Camera,
        texture: Texture2D,
        source: Rectangle,
        position: Vector3,
        size: Vector2,
        tint: Color,
    );
    pub fn DrawBillboardPro(
        camera: Camera,
        texture: Texture2D,
        source: Rectangle,
        position: Vector3,
        up: Vector3,
        size: Vector2,
        origin: Vector2,
        rotation: f32,
        tint: Color,
    );
    pub fn UploadMesh(mesh: *mut Mesh, dynamic: bool);
    pub fn UpdateMeshBuffer(
        mesh: Mesh,
        index: ::std::os::raw::c_int,
        data: *const ::std::os::raw::c_void,
        dataSize: ::std::os::raw::c_int,
        offset: ::std::os::raw::c_int,
    );
    pub fn UnloadMesh(mesh: Mesh);
    pub fn DrawMesh(mesh: Mesh, material: Material, transform: Matrix);
    pub fn DrawMeshInstanced(
        mesh: Mesh,
        material: Material,
        transforms: *const Matrix,
        instances: ::std::os::raw::c_int,
    );
    pub fn ExportMesh(mesh: Mesh, fileName: *const ::std::os::raw::c_char) -> bool;
    pub fn GetMeshBoundingBox(mesh: Mesh) -> BoundingBox;
    pub fn GenMeshTangents(mesh: *mut Mesh);
    pub fn GenMeshPoly(sides: ::std::os::raw::c_int, radius: f32) -> Mesh;
    pub fn GenMeshPlane(
        width: f32,
        length: f32,
        resX: ::std::os::raw::c_int,
        resZ: ::std::os::raw::c_int,
    ) -> Mesh;
    pub fn GenMeshCube(width: f32, height: f32, length: f32) -> Mesh;
    pub fn GenMeshSphere(
        radius: f32,
        rings: ::std::os::raw::c_int,
        slices: ::std::os::raw::c_int,
    ) -> Mesh;
    pub fn GenMeshHemiSphere(
        radius: f32,
        rings: ::std::os::raw::c_int,
        slices: ::std::os::raw::c_int,
    ) -> Mesh;
    pub fn GenMeshCylinder(radius: f32, height: f32, slices: ::std::os::raw::c_int) -> Mesh;
    pub fn GenMeshCone(radius: f32, height: f32, slices: ::std::os::raw::c_int) -> Mesh;
    pub fn GenMeshTorus(
        radius: f32,
        size: f32,
        radSeg: ::std::os::raw::c_int,
        sides: ::std::os::raw::c_int,
    ) -> Mesh;
    pub fn GenMeshKnot(
        radius: f32,
        size: f32,
        radSeg: ::std::os::raw::c_int,
        sides: ::std::os::raw::c_int,
    ) -> Mesh;
    pub fn GenMeshHeightmap(heightmap: Image, size: Vector3) -> Mesh;
    pub fn GenMeshCubicmap(cubicmap: Image, cubeSize: Vector3) -> Mesh;
    pub fn LoadMaterials(
        fileName: *const ::std::os::raw::c_char,
        materialCount: *mut ::std::os::raw::c_int,
    ) -> *mut Material;
    pub fn LoadMaterialDefault() -> Material;
    pub fn IsMaterialReady(material: Material) -> bool;
    pub fn UnloadMaterial(material: Material);
    pub fn SetMaterialTexture(
        material: *mut Material,
        mapType: ::std::os::raw::c_int,
        texture: Texture2D,
    );
    pub fn SetModelMeshMaterial(
        model: *mut Model,
        meshId: ::std::os::raw::c_int,
        materialId: ::std::os::raw::c_int,
    );
    pub fn LoadModelAnimations(
        fileName: *const ::std::os::raw::c_char,
        animCount: *mut ::std::os::raw::c_int,
    ) -> *mut ModelAnimation;
    pub fn UpdateModelAnimation(model: Model, anim: ModelAnimation, frame: ::std::os::raw::c_int);
    pub fn UnloadModelAnimation(anim: ModelAnimation);
    pub fn UnloadModelAnimations(animations: *mut ModelAnimation, animCount: ::std::os::raw::c_int);
    pub fn IsModelAnimationValid(model: Model, anim: ModelAnimation) -> bool;
    pub fn CheckCollisionSpheres(
        center1: Vector3,
        radius1: f32,
        center2: Vector3,
        radius2: f32,
    ) -> bool;
    pub fn CheckCollisionBoxes(box1: BoundingBox, box2: BoundingBox) -> bool;
    pub fn CheckCollisionBoxSphere(box_: BoundingBox, center: Vector3, radius: f32) -> bool;
    pub fn GetRayCollisionSphere(ray: Ray, center: Vector3, radius: f32) -> RayCollision;
    pub fn GetRayCollisionBox(ray: Ray, box_: BoundingBox) -> RayCollision;
    pub fn GetRayCollisionMesh(ray: Ray, mesh: Mesh, transform: Matrix) -> RayCollision;
    pub fn GetRayCollisionTriangle(ray: Ray, p1: Vector3, p2: Vector3, p3: Vector3)
        -> RayCollision;
    pub fn GetRayCollisionQuad(
        ray: Ray,
        p1: Vector3,
        p2: Vector3,
        p3: Vector3,
        p4: Vector3,
    ) -> RayCollision;
    pub fn InitAudioDevice();
    pub fn CloseAudioDevice();
    pub fn IsAudioDeviceReady() -> bool;
    pub fn SetMasterVolume(volume: f32);
    pub fn GetMasterVolume() -> f32;
    pub fn LoadWave(fileName: *const ::std::os::raw::c_char) -> Wave;
    pub fn LoadWaveFromMemory(
        fileType: *const ::std::os::raw::c_char,
        fileData: *const ::std::os::raw::c_uchar,
        dataSize: ::std::os::raw::c_int,
    ) -> Wave;
    pub fn IsWaveReady(wave: Wave) -> bool;
    pub fn LoadSound(fileName: *const ::std::os::raw::c_char) -> Sound;
    pub fn LoadSoundFromWave(wave: Wave) -> Sound;
    pub fn LoadSoundAlias(source: Sound) -> Sound;
    pub fn IsSoundReady(sound: Sound) -> bool;
    pub fn UpdateSound(
        sound: Sound,
        data: *const ::std::os::raw::c_void,
        sampleCount: ::std::os::raw::c_int,
    );
    pub fn UnloadWave(wave: Wave);
    pub fn UnloadSound(sound: Sound);
    pub fn UnloadSoundAlias(alias: Sound);
    pub fn ExportWave(wave: Wave, fileName: *const ::std::os::raw::c_char) -> bool;
    pub fn ExportWaveAsCode(wave: Wave, fileName: *const ::std::os::raw::c_char) -> bool;
    pub fn PlaySound(sound: Sound);
    pub fn StopSound(sound: Sound);
    pub fn PauseSound(sound: Sound);
    pub fn ResumeSound(sound: Sound);
    pub fn IsSoundPlaying(sound: Sound) -> bool;
    pub fn SetSoundVolume(sound: Sound, volume: f32);
    pub fn SetSoundPitch(sound: Sound, pitch: f32);
    pub fn SetSoundPan(sound: Sound, pan: f32);
    pub fn WaveCopy(wave: Wave) -> Wave;
    pub fn WaveCrop(
        wave: *mut Wave,
        initSample: ::std::os::raw::c_int,
        finalSample: ::std::os::raw::c_int,
    );
    pub fn WaveFormat(
        wave: *mut Wave,
        sampleRate: ::std::os::raw::c_int,
        sampleSize: ::std::os::raw::c_int,
        channels: ::std::os::raw::c_int,
    );
    pub fn LoadWaveSamples(wave: Wave) -> *mut f32;
    pub fn UnloadWaveSamples(samples: *mut f32);
    pub fn LoadMusicStream(fileName: *const ::std::os::raw::c_char) -> Music;
    pub fn LoadMusicStreamFromMemory(
        fileType: *const ::std::os::raw::c_char,
        data: *const ::std::os::raw::c_uchar,
        dataSize: ::std::os::raw::c_int,
    ) -> Music;
    pub fn IsMusicReady(music: Music) -> bool;
    pub fn UnloadMusicStream(music: Music);
    pub fn PlayMusicStream(music: Music);
    pub fn IsMusicStreamPlaying(music: Music) -> bool;
    pub fn UpdateMusicStream(music: Music);
    pub fn StopMusicStream(music: Music);
    pub fn PauseMusicStream(music: Music);
    pub fn ResumeMusicStream(music: Music);
    pub fn SeekMusicStream(music: Music, position: f32);
    pub fn SetMusicVolume(music: Music, volume: f32);
    pub fn SetMusicPitch(music: Music, pitch: f32);
    pub fn SetMusicPan(music: Music, pan: f32);
    pub fn GetMusicTimeLength(music: Music) -> f32;
    pub fn GetMusicTimePlayed(music: Music) -> f32;
    pub fn LoadAudioStream(
        sampleRate: ::std::os::raw::c_uint,
        sampleSize: ::std::os::raw::c_uint,
        channels: ::std::os::raw::c_uint,
    ) -> AudioStream;
    pub fn IsAudioStreamReady(stream: AudioStream) -> bool;
    pub fn UnloadAudioStream(stream: AudioStream);
    pub fn UpdateAudioStream(
        stream: AudioStream,
        data: *const ::std::os::raw::c_void,
        frameCount: ::std::os::raw::c_int,
    );
    pub fn IsAudioStreamProcessed(stream: AudioStream) -> bool;
    pub fn PlayAudioStream(stream: AudioStream);
    pub fn PauseAudioStream(stream: AudioStream);
    pub fn ResumeAudioStream(stream: AudioStream);
    pub fn IsAudioStreamPlaying(stream: AudioStream) -> bool;
    pub fn StopAudioStream(stream: AudioStream);
    pub fn SetAudioStreamVolume(stream: AudioStream, volume: f32);
    pub fn SetAudioStreamPitch(stream: AudioStream, pitch: f32);
    pub fn SetAudioStreamPan(stream: AudioStream, pan: f32);
    pub fn SetAudioStreamBufferSizeDefault(size: ::std::os::raw::c_int);
    pub fn SetAudioStreamCallback(stream: AudioStream, callback: AudioCallback);
    pub fn AttachAudioStreamProcessor(stream: AudioStream, processor: AudioCallback);
    pub fn DetachAudioStreamProcessor(stream: AudioStream, processor: AudioCallback);
    pub fn AttachAudioMixedProcessor(processor: AudioCallback);
    pub fn DetachAudioMixedProcessor(processor: AudioCallback);
}
