## Camera types and pure helpers.
##
## The same types are available from the companion `roc-ray-types` package for
## libraries that do not otherwise depend on this platform.
# Generated by scripts/generate_reexports.py; edit types/Camera.roc instead.
import rrt.Camera as RrtCamera
import Math

Camera := [].{

	## Immutable camera value accepted by drawing and coordinate transforms.
	## Its representation is opaque so non-finite transform fields or a
	## non-invertible zero zoom cannot bypass the sanitizing below.
	Camera2D : RrtCamera.Camera2D

	## Target, screen offset, clockwise rotation in degrees, and zoom factor.
	Settings : RrtCamera.Settings

	## The zoom substituted for a zoom that cannot be used, meaning zero (which
	## has no inverse) or a non-finite one (which has no meaning).
	##
	## Deliberately tiny rather than `1`: a camera that had to be rescued
	## collapses the world to a dot at its offset, which reads on screen as the
	## mistake it is, instead of quietly looking plausible.
	fallback_zoom : F32
	fallback_zoom = RrtCamera.fallback_zoom

	## Identity camera: no offset or rotation, with unit zoom.
	default : Camera2D
	default = RrtCamera.default

	## Construct a camera from explicit settings.
	##
	## Total: non-finite `target`, `offset`, and `rotation` components become
	## `0`, and a `zoom` of zero or one that is not finite becomes
	## `fallback_zoom` with the same sign. Every usable setting is kept exactly.
	new : RrtCamera.Settings -> Camera2D
	new = |a0| RrtCamera.new(a0)

	## Place `target` at the center of a screen with unit zoom.
	##
	## Total: a non-finite component of either vector becomes `0`.
	centered : Math.Vec2, Math.Vec2 -> Camera2D
	centered = |a0, a1| RrtCamera.centered(a0, a1)

	## A common player-follow camera with a configurable zoom.
	##
	## Total: a non-finite `target` or `screen` component becomes `0`, and a
	## `zoom` of zero or one that is not finite becomes `fallback_zoom` with the
	## same sign.
	follow : Math.Vec2, { screen : Math.Vec2, zoom : F32 } -> Camera2D
	follow = |a0, a1| RrtCamera.follow(a0, a1)
}
