## Camera module -- re-exported from the companion `roc-ray-types` package.
##
## The types and pure helpers live in the package so reusable packages can
## depend on them without depending on this platform. These are aliases, so the
## nominals here and in the package are the same and values pass freely between
## them. Receivers ride along with the type and are not repeated, so they are
## documented in the [roc-ray-types docs](../types/) instead.
##
## Generated by scripts/generate_reexports.py -- edit package/Camera.roc, not this.
import rrt.Camera as RrtCamera
import Math

Camera := [].{

	## Immutable camera value accepted by drawing and coordinate transforms.
	## Its representation is opaque so non-finite transform fields or a
	## non-invertible zero zoom cannot bypass validation.
	Camera2D : RrtCamera.Camera2D

	## Target, screen offset, clockwise rotation in degrees, and zoom factor.
	Settings : RrtCamera.Settings

	## Identity camera: no offset or rotation, with unit zoom.
	default : Camera2D
	default = RrtCamera.default

	## Construct a camera from explicit settings, rejecting every non-finite
	## transform field and zero zoom.
	new : RrtCamera.Settings -> Try(Camera2D, [ZeroZoom, NonFiniteZoom, NonFiniteTarget, NonFiniteOffset, NonFiniteRotation, ..])
	new = |a0| RrtCamera.new(a0)

	## Place `target` at the center of a screen with unit zoom.
	centered : Math.Vec2, Math.Vec2 -> Try(Camera2D, [NonFiniteTarget, NonFiniteOffset, ..])
	centered = |a0, a1| RrtCamera.centered(a0, a1)

	## A common player-follow camera with a validated configurable zoom.
	follow : Math.Vec2, { screen : Math.Vec2, zoom : F32 } -> Try(Camera2D, [ZeroZoom, NonFiniteZoom, NonFiniteTarget, NonFiniteOffset, ..])
	follow = |a0, a1| RrtCamera.follow(a0, a1)
}
