## Color types and pure helpers.
##
## The same types are available from the companion `roc-ray-types` package for
## libraries that do not otherwise depend on this platform.
# Generated by scripts/generate_reexports.py; edit types/Color.roc instead.
import rrt.Color as RrtColor

Color := [].{

	## An 8-bit sRGB color with alpha.
	Rgba : RrtColor.Rgba

	## Construct a color from red, green, blue, and alpha channels.
	rgba : U8, U8, U8, U8 -> Rgba
	rgba = |a0, a1, a2, a3| RrtColor.rgba(a0, a1, a2, a3)

	## Construct an opaque color from red, green, and blue channels.
	rgb : U8, U8, U8 -> Rgba
	rgb = |a0, a1, a2| RrtColor.rgb(a0, a1, a2)

	## Return a copy with a new alpha channel.
	with_alpha : Rgba, U8 -> Rgba
	with_alpha = |a0, a1| RrtColor.with_alpha(a0, a1)

	## Decode `0xRRGGBB` into an opaque color.
	from_hex_rgb : U32 -> Rgba
	from_hex_rgb = |a0| RrtColor.from_hex_rgb(a0)

	## Decode `0xRRGGBBAA` into a color.
	from_hex_rgba : U32 -> Rgba
	from_hex_rgba = |a0| RrtColor.from_hex_rgba(a0)

	## Fully transparent black.
	transparent : Rgba
	transparent = RrtColor.transparent

	## Black.
	black : Rgba
	black = RrtColor.black

	## Raylib's standard blue.
	blue : Rgba
	blue = RrtColor.blue

	## Raylib's standard dark gray.
	dark_gray : Rgba
	dark_gray = RrtColor.dark_gray

	## Raylib's standard gray.
	gray : Rgba
	gray = RrtColor.gray

	## Raylib's standard green.
	green : Rgba
	green = RrtColor.green

	## Raylib's standard light gray.
	light_gray : Rgba
	light_gray = RrtColor.light_gray

	## Raylib's standard orange.
	orange : Rgba
	orange = RrtColor.orange

	## Raylib's standard pink.
	pink : Rgba
	pink = RrtColor.pink

	## Raylib's standard purple.
	purple : Rgba
	purple = RrtColor.purple

	## Raylib's warm off-white background color.
	ray_white : Rgba
	ray_white = RrtColor.ray_white

	## Raylib's standard red.
	red : Rgba
	red = RrtColor.red

	## White.
	white : Rgba
	white = RrtColor.white

	## Raylib's standard yellow.
	yellow : Rgba
	yellow = RrtColor.yellow
}
