## Color module -- re-exported from the companion `roc-ray-types` package.
##
## The types and pure helpers live in the package so reusable packages can
## depend on them without depending on this platform. These are aliases, so the
## nominals here and in the package are the same and values pass freely between
## them. Receivers ride along with the type and are not repeated, so they are
## documented in the [roc-ray-types docs](../types/) instead.
##
## Generated by scripts/generate_reexports.py -- edit package/Color.roc, not this.
import rrt.Color as RrtColor

Color := [].{

	## An 8-bit sRGB color with alpha.
	##
	## `with_alpha` is deliberately a module function rather than a receiver on
	## this type: a receiver that calls its enclosing namespace's same-named
	## module function crashes the compiler. Every call site is `Color.with_alpha`
	## anyway, so the surface is unchanged.
	Rgba : RrtColor.Rgba

	## Construct a color from red, green, blue, and alpha channels.
	rgba : U8, U8, U8, U8 -> Rgba
	rgba = |a0, a1, a2, a3| RrtColor.rgba(a0, a1, a2, a3)

	## Construct an opaque color from red, green, and blue channels.
	rgb : U8, U8, U8 -> Rgba
	rgb = |a0, a1, a2| RrtColor.rgb(a0, a1, a2)

	## Return a copy with a new alpha channel.
	with_alpha : Rgba, U8 -> Rgba
	with_alpha = |a0, a1| RrtColor.with_alpha(a0, a1)

	## Decode `0xRRGGBB` into an opaque color.
	from_hex_rgb : U32 -> Rgba
	from_hex_rgb = |a0| RrtColor.from_hex_rgb(a0)

	## Decode `0xRRGGBBAA` into a color.
	from_hex_rgba : U32 -> Rgba
	from_hex_rgba = |a0| RrtColor.from_hex_rgba(a0)

	## Fully transparent black.
	transparent : Rgba
	transparent = RrtColor.transparent

	## Black.
	black : Rgba
	black = RrtColor.black

	## Raylib's standard blue.
	blue : Rgba
	blue = RrtColor.blue

	## Raylib's standard dark gray.
	dark_gray : Rgba
	dark_gray = RrtColor.dark_gray

	## Raylib's standard gray.
	gray : Rgba
	gray = RrtColor.gray

	## Raylib's standard green.
	green : Rgba
	green = RrtColor.green

	## Raylib's standard light gray.
	light_gray : Rgba
	light_gray = RrtColor.light_gray

	## Raylib's standard orange.
	orange : Rgba
	orange = RrtColor.orange

	## Raylib's standard pink.
	pink : Rgba
	pink = RrtColor.pink

	## Raylib's standard purple.
	purple : Rgba
	purple = RrtColor.purple

	## Raylib's warm off-white background color.
	ray_white : Rgba
	ray_white = RrtColor.ray_white

	## Raylib's standard red.
	red : Rgba
	red = RrtColor.red

	## White.
	white : Rgba
	white = RrtColor.white

	## Raylib's standard yellow.
	yellow : Rgba
	yellow = RrtColor.yellow
}
