## RGBA colors.
##
## Channels are 8-bit sRGB values. Alpha is `0` for transparent and `255` for
## fully opaque. A color is a plain value: build one, keep it in the model, and
## hand it to any drawing call.
##
## The named constants cover the common cases, `from_hex_rgb` reads the form a
## designer hands over, and `with_alpha` makes any of them translucent.
##
## ```roc
## accent = Color.from_hex_rgb(0x2f80ed)
## glow = Color.with_alpha(accent, 100)
## ```
##
## These types live in the companion `roc-ray-types` package and are re-exported
## here, so a value passes between the two spellings freely and a library can
## depend on the package without depending on this platform.
# Generated by scripts/generate_reexports.py; edit types/Color.roc instead.
import rrt.Color as RrtColor

Color := [].{

	## An 8-bit sRGB color with alpha. `Color.Rgba` on the platform is this same
	## type, re-exported.
	Rgba : RrtColor.Rgba

	## Construct a color from red, green, blue, and alpha channels.
	rgba : U8, U8, U8, U8 -> Rgba
	rgba = |a0, a1, a2, a3| RrtColor.rgba(a0, a1, a2, a3)

	## Construct an opaque color from red, green, and blue channels.
	rgb : U8, U8, U8 -> Rgba
	rgb = |a0, a1, a2| RrtColor.rgb(a0, a1, a2)

	## Return a copy with a new alpha channel.
	with_alpha : Rgba, U8 -> Rgba
	with_alpha = |a0, a1| RrtColor.with_alpha(a0, a1)

	## Decode `0xRRGGBB` into an opaque color.
	from_hex_rgb : U32 -> Rgba
	from_hex_rgb = |a0| RrtColor.from_hex_rgb(a0)

	## Decode `0xRRGGBBAA` into a color.
	from_hex_rgba : U32 -> Rgba
	from_hex_rgba = |a0| RrtColor.from_hex_rgba(a0)

	## Fully transparent black.
	transparent : Rgba
	transparent = RrtColor.transparent

	## Black.
	black : Rgba
	black = RrtColor.black

	## Raylib's standard blue.
	blue : Rgba
	blue = RrtColor.blue

	## Raylib's standard dark gray.
	dark_gray : Rgba
	dark_gray = RrtColor.dark_gray

	## Raylib's standard gray.
	gray : Rgba
	gray = RrtColor.gray

	## Raylib's standard green.
	green : Rgba
	green = RrtColor.green

	## Raylib's standard light gray.
	light_gray : Rgba
	light_gray = RrtColor.light_gray

	## Raylib's standard orange.
	orange : Rgba
	orange = RrtColor.orange

	## Raylib's standard pink.
	pink : Rgba
	pink = RrtColor.pink

	## Raylib's standard purple.
	purple : Rgba
	purple = RrtColor.purple

	## Raylib's warm off-white background color.
	ray_white : Rgba
	ray_white = RrtColor.ray_white

	## Raylib's standard red.
	red : Rgba
	red = RrtColor.red

	## White.
	white : Rgba
	white = RrtColor.white

	## Raylib's standard yellow.
	yellow : Rgba
	yellow = RrtColor.yellow
}
