## Math types and pure helpers.
##
## The same types are available from the companion `roc-ray-types` package for
## libraries that do not otherwise depend on this platform.
# Generated by scripts/generate_reexports.py; edit types/Math.roc instead.
import rrt.Math as RrtMath

Math := [].{

	## Two-dimensional floating-point vector.
	Vec2 : RrtMath.Vec2

	## Axis-aligned rectangle represented by top-left position and size.
	Rect : RrtMath.Rect

	## Circle represented by center and radius.
	Circle : RrtMath.Circle

	## Construct a two-dimensional vector.
	vec2 : F32, F32 -> Vec2
	vec2 = |a0, a1| RrtMath.vec2(a0, a1)

	## The zero vector.
	zero : Vec2
	zero = RrtMath.zero

	## Construct an axis-aligned rectangle.
	rect : F32, F32, F32, F32 -> Rect
	rect = |a0, a1, a2, a3| RrtMath.rect(a0, a1, a2, a3)

	## Construct a circle.
	circle : Vec2, F32 -> Circle
	circle = |a0, a1| RrtMath.circle(a0, a1)

	## Clamp a value to inclusive lower and upper bounds.
	clamp : F32, F32, F32 -> F32
	clamp = |a0, a1, a2| RrtMath.clamp(a0, a1, a2)

	## Clamp a value to the inclusive 0-to-1 range.
	clamp01 : F32 -> F32
	clamp01 = |a0| RrtMath.clamp01(a0)

	## Linearly interpolate between two scalars; amounts outside 0 to 1 extrapolate.
	lerp : F32, F32, F32 -> F32
	lerp = |a0, a1, a2| RrtMath.lerp(a0, a1, a2)

	## Square root for game-scale F32 values.
	## Roc's pinned builtins do not expose sqrt yet, so keep this pure Roc.
	sqrt : F32 -> F32
	sqrt = |a0| RrtMath.sqrt(a0)

	## Add two vectors component-wise.
	add : Vec2, Vec2 -> Vec2
	add = |a0, a1| RrtMath.add(a0, a1)

	## Subtract two vectors component-wise.
	sub : Vec2, Vec2 -> Vec2
	sub = |a0, a1| RrtMath.sub(a0, a1)

	## Multiply both vector components by a scalar.
	scale : Vec2, F32 -> Vec2
	scale = |a0, a1| RrtMath.scale(a0, a1)

	## Compute the vector dot product.
	dot : Vec2, Vec2 -> F32
	dot = |a0, a1| RrtMath.dot(a0, a1)

	## Squared vector length, avoiding a square root.
	length_squared : Vec2 -> F32
	length_squared = |a0| RrtMath.length_squared(a0)

	## Euclidean vector length.
	length : Vec2 -> F32
	length = |a0| RrtMath.length(a0)

	## Squared distance between two points.
	distance_squared : Vec2, Vec2 -> F32
	distance_squared = |a0, a1| RrtMath.distance_squared(a0, a1)

	## Euclidean distance between two points.
	distance : Vec2, Vec2 -> F32
	distance = |a0, a1| RrtMath.distance(a0, a1)

	## Return a unit vector, or zero when the input has zero length.
	normalize : Vec2 -> Vec2
	normalize = |a0| RrtMath.normalize(a0)

	## Linearly interpolate between two vectors.
	lerp_vec2 : Vec2, Vec2, F32 -> Vec2
	lerp_vec2 = |a0, a1, a2| RrtMath.lerp_vec2(a0, a1, a2)

	## Left edge of a rectangle.
	left : Rect -> F32
	left = |a0| RrtMath.left(a0)

	## Right edge of a rectangle.
	right : Rect -> F32
	right = |a0| RrtMath.right(a0)

	## Top edge of a rectangle.
	top : Rect -> F32
	top = |a0| RrtMath.top(a0)

	## Bottom edge of a rectangle.
	bottom : Rect -> F32
	bottom = |a0| RrtMath.bottom(a0)

	## Center point of a rectangle.
	center : Rect -> Vec2
	center = |a0| RrtMath.center(a0)

	## Closest point in or on a rectangle.
	closest_point : Rect, Vec2 -> Vec2
	closest_point = |a0, a1| RrtMath.closest_point(a0, a1)

	## Whether a rectangle contains a point, including its edges.
	contains : Rect, Vec2 -> Bool
	contains = |a0, a1| RrtMath.contains(a0, a1)

	## Whether a circle contains a point, including its edge.
	circle_contains : Circle, Vec2 -> Bool
	circle_contains = |a0, a1| RrtMath.circle_contains(a0, a1)

	## Whether two rectangles overlap or touch.
	overlaps : Rect, Rect -> Bool
	overlaps = |a0, a1| RrtMath.overlaps(a0, a1)

	## Whether two circles overlap or touch.
	circle_overlaps : Circle, Circle -> Bool
	circle_overlaps = |a0, a1| RrtMath.circle_overlaps(a0, a1)

	## Whether a circle and rectangle overlap or touch.
	circle_rect : Circle, Rect -> Bool
	circle_rect = |a0, a1| RrtMath.circle_rect(a0, a1)

	## Receiver-friendly aliases for circle queries. The longer names avoid
	## ambiguity with the corresponding rectangle methods.
	contains_point : Circle, Vec2 -> Bool
	contains_point = |a0, a1| RrtMath.contains_point(a0, a1)

	overlaps_circle : Circle, Circle -> Bool
	overlaps_circle = |a0, a1| RrtMath.overlaps_circle(a0, a1)

	overlaps_rect : Circle, Rect -> Bool
	overlaps_rect = |a0, a1| RrtMath.overlaps_rect(a0, a1)
}
