## 3D projective geometric algebra: points, lines, planes, and the motors
## that move them.
##
## Use this module to compose 3D rotation and translation and to join, meet, or
## project geometric objects. Use `Math` for ordinary 2D vectors and shapes.
## Values use compact, grade-specific PGA coefficients.
##
## These types live in the companion `roc-ray-types` package and are re-exported
## here, so a value passes between the two spellings freely and a library can
## depend on the package without depending on this platform.
# Generated by scripts/generate_reexports.py; edit types/Physics.roc instead.
import rrt.Physics as RrtPhysics
import Math

Physics := [].{

	## A finite 3D PGA point stored as compact grade-3 homogeneous coefficients.
	Point : RrtPhysics.Point

	## A free 3D direction or translation stored as the ideal part of a point.
	Vector : RrtPhysics.Vector

	## A 3D PGA plane stored as grade-1 coefficients.
	Plane : RrtPhysics.Plane

	## A 3D PGA line stored as six grade-2 Plucker-style coefficients.
	Line : RrtPhysics.Line

	## A 3D PGA motor stored as compact even-subalgebra coefficients.
	Motor : RrtPhysics.Motor

	## A simple particle body with a PGA point position and vector velocity.
	Body : RrtPhysics.Body

	## Plain coordinate view returned by accessors.
	Coords : RrtPhysics.Coords

	## Read-only coefficient view for a point.
	PointCoeffs : RrtPhysics.PointCoeffs

	## Read-only coefficient view for a vector.
	VectorCoeffs : RrtPhysics.VectorCoeffs

	## Read-only coefficient view for a plane.
	PlaneCoeffs : RrtPhysics.PlaneCoeffs

	## Read-only coefficient view for a line.
	LineCoeffs : RrtPhysics.LineCoeffs

	## Read-only coefficient view for a motor.
	MotorCoeffs : RrtPhysics.MotorCoeffs

	## Construct a finite point from x, y, and z coordinates.
	point : F32, F32, F32 -> Point
	point = |a0, a1, a2| RrtPhysics.point(a0, a1, a2)

	## Construct a finite point on the z=0 plane.
	point_xy : F32, F32 -> Point
	point_xy = |a0, a1| RrtPhysics.point_xy(a0, a1)

	## The finite point at the coordinate origin.
	origin : Point
	origin = RrtPhysics.origin

	## Construct a free vector from x, y, and z components.
	vector : F32, F32, F32 -> Vector
	vector = |a0, a1, a2| RrtPhysics.vector(a0, a1, a2)

	## Construct a free vector on the z=0 plane.
	vector_xy : F32, F32 -> Vector
	vector_xy = |a0, a1| RrtPhysics.vector_xy(a0, a1)

	## The zero vector.
	zero : Vector
	zero = RrtPhysics.zero

	## Return normalized x, y, and z coordinates for a point.
	coords : Point -> RrtPhysics.Coords
	coords = |a0| RrtPhysics.coords(a0)

	## Return x, y, and z components for a free vector.
	components : Vector -> RrtPhysics.Coords
	components = |a0| RrtPhysics.components(a0)

	## Return the x/y components of a point for 2D drawing boundaries.
	xy : Point -> Math.Vec2
	xy = |a0| RrtPhysics.xy(a0)

	## Return the x/y components of a vector for 2D drawing boundaries.
	vector_xy_components : Vector -> Math.Vec2
	vector_xy_components = |a0| RrtPhysics.vector_xy_components(a0)

	## Return a read-only point coefficient record.
	point_coeffs : Point -> RrtPhysics.PointCoeffs
	point_coeffs = |a0| RrtPhysics.point_coeffs(a0)

	## Return a read-only vector coefficient record.
	vector_coeffs : Vector -> RrtPhysics.VectorCoeffs
	vector_coeffs = |a0| RrtPhysics.vector_coeffs(a0)

	## Return a read-only plane coefficient record.
	plane_coeffs : Plane -> RrtPhysics.PlaneCoeffs
	plane_coeffs = |a0| RrtPhysics.plane_coeffs(a0)

	## Return a read-only line coefficient record.
	line_coeffs : Line -> RrtPhysics.LineCoeffs
	line_coeffs = |a0| RrtPhysics.line_coeffs(a0)

	## Return a read-only motor coefficient record.
	motor_coeffs : Motor -> RrtPhysics.MotorCoeffs
	motor_coeffs = |a0| RrtPhysics.motor_coeffs(a0)

	## Translate a point by a free vector.
	add : Point, Vector -> Point
	add = |a0, a1| RrtPhysics.add(a0, a1)

	## Return the free vector from the second point to the first point.
	sub : Point, Point -> Vector
	sub = |a0, a1| RrtPhysics.sub(a0, a1)

	## Add two free vectors.
	add_vec : Vector, Vector -> Vector
	add_vec = |a0, a1| RrtPhysics.add_vec(a0, a1)

	## Subtract the second free vector from the first.
	sub_vec : Vector, Vector -> Vector
	sub_vec = |a0, a1| RrtPhysics.sub_vec(a0, a1)

	## Scale a free vector by a scalar amount.
	scale : Vector, F32 -> Vector
	scale = |a0, a1| RrtPhysics.scale(a0, a1)

	## Compute the Euclidean dot product of two free vectors.
	dot : Vector, Vector -> F32
	dot = |a0, a1| RrtPhysics.dot(a0, a1)

	## Compute the Euclidean cross product of two free vectors.
	cross : Vector, Vector -> Vector
	cross = |a0, a1| RrtPhysics.cross(a0, a1)

	## Compute the squared Euclidean length of a free vector.
	length_squared : Vector -> F32
	length_squared = |a0| RrtPhysics.length_squared(a0)

	## Compute the Euclidean length of a free vector.
	length : Vector -> F32
	length = |a0| RrtPhysics.length(a0)

	## Return a unit-length vector, or zero for a zero-length input.
	normalize : Vector -> Vector
	normalize = |a0| RrtPhysics.normalize(a0)

	## Reflect a vector around a surface normal.
	reflect : Vector, Vector -> Vector
	reflect = |a0, a1| RrtPhysics.reflect(a0, a1)

	## Compute the Euclidean distance between two finite points.
	distance : Point, Point -> F32
	distance = |a0, a1| RrtPhysics.distance(a0, a1)

	## Construct a normalized plane from a normal and signed distance to origin.
	plane : Vector, F32 -> Plane
	plane = |a0, a1| RrtPhysics.plane(a0, a1)

	## Construct a plane through a point with the given normal direction.
	plane_from_point_normal : Point, Vector -> Plane
	plane_from_point_normal = |a0, a1| RrtPhysics.plane_from_point_normal(a0, a1)

	## Compute the signed Euclidean distance from a normalized plane to a point.
	signed_distance : Plane, Point -> F32
	signed_distance = |a0, a1| RrtPhysics.signed_distance(a0, a1)

	## Project a point onto a normalized plane.
	project_point_plane : Plane, Point -> Point
	project_point_plane = |a0, a1| RrtPhysics.project_point_plane(a0, a1)

	## Construct a PGA line passing through two finite points.
	line_from_points : Point, Point -> Line
	line_from_points = |a0, a1| RrtPhysics.line_from_points(a0, a1)

	## The identity motor.
	motor_identity : Motor
	motor_identity = RrtPhysics.motor_identity

	## Construct a translation motor from a free offset vector.
	translation : Vector -> Motor
	translation = |a0| RrtPhysics.translation(a0)

	## Extract the translation offset represented by a translation motor.
	translation_vector : Motor -> Vector
	translation_vector = |a0| RrtPhysics.translation_vector(a0)

	## Apply a translation motor to a finite point.
	apply_motor_point : Motor, Point -> Point
	apply_motor_point = |a0, a1| RrtPhysics.apply_motor_point(a0, a1)

	## Construct a simple particle body.
	body : Point, Vector -> Body
	body = |a0, a1| RrtPhysics.body(a0, a1)

	## Integrate acceleration into a body's velocity over a time step.
	apply_acceleration : Body, Vector, F32 -> Body
	apply_acceleration = |a0, a1, a2| RrtPhysics.apply_acceleration(a0, a1, a2)

	## Integrate velocity into a body's position over a time step.
	integrate_body : Body, F32 -> Body
	integrate_body = |a0, a1| RrtPhysics.integrate_body(a0, a1)

	## Clamp only the y component of a free vector.
	clamp_y : Vector, F32, F32 -> Vector
	clamp_y = |a0, a1, a2| RrtPhysics.clamp_y(a0, a1, a2)
}
