#!/usr/bin/env python3
"""Generate or verify a deterministic roc-ray loose-asset manifest.

The root digest is SHA-256 over lexically sorted records:
    UTF-8 relative path, NUL, decimal byte length, NUL, raw file SHA-256, NUL
`roc-assets.manifest` itself is excluded. Files are read in chunks, never held
in full. This gives packaging/CI a stable content revision without charging a
runtime startup walk over every asset.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path


MANIFEST = "roc-assets.manifest"
CHUNK = 1024 * 1024
MAX_U32 = (1 << 32) - 1


class ManifestError(ValueError):
    """A portable asset namespace or manifest contract violation."""


@dataclass(frozen=True)
class Entry:
    path: str
    size: int
    sha256: bytes


def portable_path(root: Path, file: Path) -> str:
    relative = file.relative_to(root).as_posix()
    parts = relative.split("/")
    if not relative or any(not part or part in {".", ".."} or "\\" in part for part in parts):
        raise ManifestError(f"nonportable asset path: {relative!r}")
    try:
        relative.encode("utf-8")
    except UnicodeEncodeError as error:
        raise ManifestError(f"asset path is not UTF-8: {relative!r}") from error
    return relative


def file_sha256(path: Path) -> tuple[int, bytes]:
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(CHUNK), b""):
            size += len(chunk)
            digest.update(chunk)
    return size, digest.digest()


def inventory(root: Path) -> list[Entry]:
    if not root.is_dir():
        raise ManifestError(f"asset root is not a directory: {root}")
    entries: list[Entry] = []
    folded: dict[str, str] = {}
    for directory, names, files in os.walk(root, followlinks=False):
        directory_path = Path(directory)
        for name in names:
            candidate = directory_path / name
            if candidate.is_symlink():
                raise ManifestError(f"asset-directory symlinks are not packageable: {candidate}")
        for name in files:
            candidate = directory_path / name
            if candidate.is_symlink():
                raise ManifestError(f"asset symlinks are not packageable: {candidate}")
            relative = portable_path(root, candidate)
            if relative == MANIFEST:
                continue
            key = relative.casefold()
            previous = folded.get(key)
            if previous is not None:
                raise ManifestError(f"case-colliding asset paths: {previous!r} and {relative!r}")
            folded[key] = relative
            size, digest = file_sha256(candidate)
            entries.append(Entry(relative, size, digest))
    return sorted(entries, key=lambda entry: entry.path.encode("utf-8"))


def root_sha256(entries: list[Entry]) -> str:
    digest = hashlib.sha256()
    for entry in entries:
        digest.update(entry.path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(str(entry.size).encode("ascii"))
        digest.update(b"\0")
        digest.update(entry.sha256)
        digest.update(b"\0")
    return digest.hexdigest()


def manifest_text(asset_set: str, schema: int, content_version: int, digest: str) -> str:
    return (
        "# Generated by scripts/asset_manifest.py; do not hand-edit content_sha256.\n"
        f'asset_set = "{asset_set}"\n'
        f"schema = {schema}\n"
        f"content_version = {content_version}\n"
        f'content_sha256 = "{digest}"\n'
    )


def write_atomic(path: Path, text: str) -> None:
    descriptor, temporary = tempfile.mkstemp(prefix=".roc-assets-", dir=path.parent, text=True)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as output:
            output.write(text)
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("write", "check"))
    parser.add_argument("root", type=Path)
    parser.add_argument("--asset-set", required=True)
    parser.add_argument("--schema", required=True, type=int)
    parser.add_argument("--content-version", required=True, type=int)
    args = parser.parse_args()
    if not (0 <= args.schema <= MAX_U32 and 0 <= args.content_version <= MAX_U32):
        raise ManifestError("schema and content version must fit U32")
    if "\n" in args.asset_set or '"' in args.asset_set:
        raise ManifestError("asset-set must be representable in the manifest string format")

    root = args.root.resolve()
    digest = root_sha256(inventory(root))
    wanted = manifest_text(args.asset_set, args.schema, args.content_version, digest)
    path = root / MANIFEST
    if args.mode == "write":
        write_atomic(path, wanted)
        print(f"wrote {path} ({digest})")
        return 0
    try:
        actual = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"missing {path}")
        return 1
    if actual != wanted:
        print(f"stale {path}; expected content_sha256 {digest}")
        return 1
    print(f"ok {path} ({digest})")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ManifestError as error:
        raise SystemExit(f"asset manifest error: {error}")
