#!/usr/bin/env python3
"""Regenerate the platform's re-export shims for `roc-ray-types` modules.

A module moved into the companion package still needs a same-named module in
`platform/` so `exposes` and every existing app keep working. Those shims are
pure boilerplate that must track the package exactly, so they are generated
rather than hand-maintained: edit the module under `types/` and rerun this.

Two things are not obvious and are why this script exists:

* Receivers ride along with a nominal, so aliasing the type re-exports them.
  Only module-level items need explicit re-export.
* A plain record alias (`Settings : { .. }`) does NOT unify when referenced
  through the shim's own alias from inside the shim, so its uses in signatures
  are qualified back to the package. Nominals (`:=` / `::`) are fine either way.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGE_DIR = ROOT / "types"
PLATFORM_DIR = ROOT / "platform"

# Modules that live in the package and are re-exported by a generated shim.
# Keys/Mouse/Gamepad/Time have hand-written shims with curated prose and are
# deliberately not listed here.
GENERATED: tuple[str, ...] = ("Math", "Camera", "Physics", "Color")

# Module names a signature may refer to, so the shim can import them.
SIBLINGS: tuple[str, ...] = (
    "Math", "Camera", "Physics", "Color", "Keys", "Mouse", "Gamepad", "Time",
)

# Appended to the package module's own header, so the shim's page says the same
# thing the package's page does rather than a one-line stand-in for it.
HEADER_SUFFIX = """##
## These types live in the companion `roc-ray-types` package and are re-exported
## here, so a value passes between the two spellings freely and a library can
## depend on the package without depending on this platform.
# Generated by scripts/generate_reexports.py; edit types/{mod}.roc instead.
import rrt.{mod} as Rrt{mod}
"""


def module_header(source: str) -> str:
    """The `##` block at the top of a package module, verbatim."""
    lines: list[str] = []
    for line in source.splitlines(keepends=True):
        if line.startswith("##"):
            lines.append(line)
            continue
        if line.strip():
            break
    return "".join(lines)


def split_top(text: str, separators: list[str]) -> list[str]:
    """Split on separators that are not nested inside brackets."""
    out: list[str] = []
    depth = last = index = 0
    while index < len(text):
        char = text[index]
        if char in "([{":
            depth += 1
        elif char in ")]}":
            depth -= 1
        elif depth == 0:
            for separator in separators:
                if text.startswith(separator, index):
                    out.append(text[last:index])
                    last = index + len(separator)
                    index += len(separator) - 1
                    break
        index += 1
    out.append(text[last:])
    return out


def arity(signature: str) -> int:
    parts = split_top(signature, ["->", "=>"])
    if len(parts) < 2:
        return 0
    left = parts[0].strip()
    if not left:
        return 0
    return len([p for p in split_top(left, [","]) if p.strip()])


def doc_before(source: str, declaration: str) -> str:
    match = re.search(r"((?:^\t##[^\n]*\n)+)(?=" + declaration + ")", source, re.M)
    return match.group(1) if match else ""


def render(mod: str, source: str) -> str:
    nominals: list[str] = []
    plain: list[str] = []
    functions: list[tuple[str, str]] = []
    seen: set[str] = set()

    # Top-level items of the module object sit at exactly one tab.
    for match in re.finditer(r"^\t([A-Z][A-Za-z0-9_]*)\s*(::|:=|:)(?!:)\s", source, re.M):
        name = match.group(1)
        if name in seen:
            continue
        seen.add(name)
        (nominals if match.group(2) in ("::", ":=") else plain).append(name)

    for match in re.finditer(r"^\t([a-z_][A-Za-z0-9_]*!?)\s*:\s*([^\n]+)$", source, re.M):
        name = match.group(1)
        if name in seen:
            continue
        seen.add(name)
        functions.append((name, match.group(2).rstrip()))

    def qualify(signature: str) -> str:
        for name in plain:
            signature = re.sub(r"(?<![.\w])" + name + r"\b", f"Rrt{mod}.{name}", signature)
        return signature

    body: list[str] = []
    for name in nominals + plain:
        body.append(
            doc_before(source, r"\t" + name + r"\s*(?:::|:=|:)")
            + f"\t{name} : Rrt{mod}.{name}\n\n"
        )
    for name, signature in functions:
        count = arity(signature)
        if count == 0:
            impl = f"\t{name} = Rrt{mod}.{name}\n"
        else:
            args = ", ".join(f"a{i}" for i in range(count))
            # Eta-expanded so open tag unions unify per call site.
            impl = f"\t{name} = |{args}| Rrt{mod}.{name}({args})\n"
        body.append(doc_before(source, r"\t" + name + r"\s*:") + f"\t{name} : {qualify(signature)}\n{impl}\n")

    text = "".join(body)
    needed = sorted({s for s in SIBLINGS if s != mod and re.search(r"(?<!\w)" + s + r"\.", text)})
    imports = "".join(f"import {name}\n" for name in needed)
    # The blank line after the module opener is what `roc fmt` produces, so
    # generated output stays fmt-stable and `--check` is meaningful.
    header = module_header(source) + HEADER_SUFFIX.format(mod=mod)
    return header + imports + f"\n{mod} := [].{{\n\n" + text.rstrip("\n") + "\n}\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if a shim is out of date instead of rewriting it",
    )
    args = parser.parse_args(argv)

    stale: list[str] = []
    for mod in GENERATED:
        source = (PACKAGE_DIR / f"{mod}.roc").read_text(encoding="utf-8")
        generated = render(mod, source)
        target = PLATFORM_DIR / f"{mod}.roc"
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == generated:
            continue
        if args.check:
            stale.append(str(target.relative_to(ROOT)))
            continue
        target.write_text(generated, encoding="utf-8")
        print(f"Updated {target.relative_to(ROOT)}")

    if stale:
        print(
            "ERROR: re-export shims are stale; run scripts/generate_reexports.py:\n  "
            + "\n  ".join(stale),
            file=sys.stderr,
        )
        return 1

    print("Re-export shims are up to date" if args.check else "Re-export shims regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
