#!/usr/bin/env python3
"""Update the pinned Roc compiler commit in ci/ROC_COMMIT to a new commit.

The host is self-contained (the platform ABI is generated by `roc glue`), so
there is no Zig-package dependency to re-hash; we simply record the commit used
to build/run examples in ci/ROC_COMMIT.
"""

import re
import sys
from pathlib import Path


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(f"Usage: {sys.argv[0]} <new_commit_sha>")

    new_commit = sys.argv[1]
    if not re.fullmatch(r"[0-9a-fA-F]{40}", new_commit):
        raise SystemExit(f"Invalid commit SHA: {new_commit}")

    commit_path = Path(__file__).resolve().parent / "ROC_COMMIT"
    commit_path.write_text(new_commit + "\n")
    print(f"Updated ROC_COMMIT to {new_commit}")


if __name__ == "__main__":
    main()
