//! Roc Platform ABI
//!
//! This file defines Zig declarations for the direct symbol ABI used by a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this file from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

const std = @import("std");
const builtin = @import("builtin");

/// Runtime representation of an opaque `Box(T)` value.
pub const RocBox = ?*anyopaque;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
pub const RocHost = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocHost, usize, usize) callconv(.c) ?*anyopaque,
    roc_dealloc: *const fn (*RocHost, *anyopaque, usize) callconv(.c) void,
    roc_realloc: *const fn (*RocHost, *anyopaque, usize, usize) callconv(.c) ?*anyopaque,
    roc_dbg: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_expect_failed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_crashed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
};

/// Private erased-callable function pointer stored in `RocErasedCallablePayload`.
pub const RocErasedCallableFn = *const fn (*RocHost, ?[*]u8, ?[*]const u8, ?[*]u8) callconv(.c) void;

/// Final-drop callback for inline erased-callable captures.
pub const RocErasedCallableOnDrop = *const fn (?[*]u8, *RocHost) callconv(.c) void;

/// Payload header for `Box(function)`.
pub const RocErasedCallablePayload = extern struct {
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
};

/// Runtime representation of `Box(function)`.
pub const RocErasedCallable = ?[*]u8;

pub const roc_erased_callable_capture_alignment: usize = 16;
pub const roc_erased_callable_payload_alignment: usize = 16;
pub const roc_erased_callable_capture_offset: usize = std.mem.alignForward(usize, @sizeOf(RocErasedCallablePayload), roc_erased_callable_capture_alignment);

pub fn rocErasedCallablePayloadSize(capture_size: usize) usize {
    return roc_erased_callable_capture_offset + capture_size;
}

pub fn rocErasedCallablePayloadPtr(callable: RocErasedCallable) *RocErasedCallablePayload {
    return @ptrCast(@alignCast(callable orelse unreachable));
}

pub fn rocErasedCallableCapturePtr(callable: RocErasedCallable) ?[*]u8 {
    const data = callable orelse return null;
    return data + roc_erased_callable_capture_offset;
}

pub fn rocErasedCallableAllocate(
    roc_host: *RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
    capture_size: usize,
) RocErasedCallable {
    const ptr_width = @sizeOf(usize);
    const alignment = @max(ptr_width, roc_erased_callable_payload_alignment);
    const extra_bytes = @max(ptr_width, roc_erased_callable_payload_alignment);
    const length = extra_bytes + rocErasedCallablePayloadSize(capture_size);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, length, alignment));
    const data = base + extra_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    const payload: *RocErasedCallablePayload = @ptrCast(@alignCast(data));
    payload.* = .{ .callable_fn_ptr = callable_fn_ptr, .on_drop = on_drop };
    return data;
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decrefBoxWith` and `freeBoxWith` free it after the callback.
pub const RocBoxPayloadDecref = *const fn (?*anyopaque, *RocHost) callconv(.c) void;

/// Increment the refcount of a boxed payload data pointer.
pub fn increfBox(data_ptr: ?*anyopaque, amount: isize) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
    _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decrefBox(data_ptr: ?*anyopaque, roc_host: *RocHost) void {
    decrefBoxWith(data_ptr, @alignOf(usize), null, roc_host);
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
pub fn decrefBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA

    const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
    if (prev == 1) {
        if (payload_decref) |callback| callback(data_ptr, roc_host);
        freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
pub fn freeBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    if (payload_decref) |callback| callback(data_ptr, roc_host);
    freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn isUniqueBox(data_ptr: ?*anyopaque) bool {
    const data = boxDataPtr(data_ptr) orelse return true;
    const rc = boxRefcountPtr(data);
    return rc.* == 1;
}

fn boxDataPtr(data_ptr: ?*anyopaque) ?[*]u8 {
    const ptr = data_ptr orelse return null;
    return @ptrCast(ptr);
}

fn boxRefcountPtr(data: [*]u8) *isize {
    return @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
}

fn freeBoxAllocation(
    data: [*]u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) void {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: *anyopaque = @ptrFromInt(@intFromPtr(data) - header_bytes);
    roc_host.roc_dealloc(roc_host, base, alloc_alignment);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `std.math.maxInt(isize)` bytes: about 2 GiB on 32-bit targets
/// and 8 EiB on 64-bit targets.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    capacity_or_alloc_ptr: usize,
    length: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const small_str_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));
    const seamless_slice_tag: usize = 1;

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and (self.capacity_or_alloc_ptr & seamless_slice_tag) != 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .capacity_or_alloc_ptr = 0, .length = small_str_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_host: *RocHost) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, @alignOf(usize)));
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .capacity_or_alloc_ptr = slice.len << 1,
                .length = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_host: *RocHost) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            roc_host.roc_dealloc(roc_host, base, @alignOf(usize));
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~seamless_slice_tag));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return true if this list is a seamless slice into another allocation.
        /// Slices share the rc slot with their backing allocation; the alloc ptr is
        /// encoded in `capacity_or_alloc_ptr` with the low bit set.
        pub fn isSeamlessSlice(self: Self) bool {
            return (self.capacity_or_alloc_ptr & 1) != 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Resolve `self` to the start of its backing allocation (the element block
        /// just after the rc slot). Returns `null` for empty lists. Handles both
        /// whole-backing and seamless-slice forms.
        fn getAllocationPtr(self: Self) ?[*]u8 {
            if (self.isSeamlessSlice()) {
                return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~@as(usize, 1)));
            }
            const ptr = self.elements_ptr orelse return null;
            return @ptrCast(ptr);
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_host: *RocHost) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, alloc_align));
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length << 1,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_host: *RocHost) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_host);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Decrement the reference count; frees the allocation when it reaches zero.
        pub fn decref(self: Self, roc_host: *RocHost) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_host.roc_dealloc(roc_host, base, alloc_align);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
            return rc.* == 1;
        }
    };
}

/// Minimal I/O abstraction for Roc platform hosts.
///
/// Provides stderr output and fatal-error handling that can be routed
/// to different backends (POSIX, freestanding/WASM, custom).
///
/// Use `RocIo.default()` for most platforms; inject a custom vtable for
/// environments without POSIX stdio (e.g. WASM freestanding).
pub const RocIo = struct {
    ctx: ?*anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Write to stderr. Best-effort: errors are silently ignored.
        writeStderr: *const fn (?*anyopaque, []const u8) void,
        /// Terminate the process or trap. Must not return.
        onFatal: *const fn (?*anyopaque) noreturn,
    };

    /// Write `data` to stderr (best-effort).
    pub fn writeStderr(self: RocIo, data: []const u8) void {
        self.vtable.writeStderr(self.ctx, data);
    }

    /// Terminate the process or trap. Does not return.
    pub fn onFatal(self: RocIo) noreturn {
        self.vtable.onFatal(self.ctx);
    }

    /// Native (POSIX) implementation: writes to stderr, exits with code 1.
    pub fn native() RocIo {
        return .{ .ctx = null, .vtable = &native_vtable };
    }

    /// Freestanding implementation: no-op stderr, @trap() on fatal.
    pub fn freestanding() RocIo {
        return .{ .ctx = null, .vtable = &freestanding_vtable };
    }

    /// Select the appropriate implementation for the current build target.
    pub fn default() RocIo {
        if (comptime builtin.os.tag == .freestanding) {
            return freestanding();
        }
        return native();
    }

    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        std.fs.File.stderr().writeAll(data) catch {};
    }

    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        std.process.exit(1);
    }

    fn freestandingWriteStderr(_: ?*anyopaque, _: []const u8) void {}

    fn freestandingOnFatal(_: ?*anyopaque) noreturn {
        @trap();
    }

    const native_vtable: VTable = .{
        .writeStderr = &nativeWriteStderr,
        .onFatal = &nativeOnFatal,
    };

    const freestanding_vtable: VTable = .{
        .writeStderr = &freestandingWriteStderr,
        .onFatal = &freestandingOnFatal,
    };
};

/// Host environment passed to the Roc runtime.
///
/// Bundles the allocator and I/O backend used by DefaultAllocators
/// and DefaultHandlers.
pub const RocEnv = struct {
    allocator: std.mem.Allocator,
    roc_io: RocIo,
};

/// Element type for __AnonStruct0
pub const __AnonStruct0 = extern struct {
    @"handle": u64,
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct0) != 16) @compileError("__AnonStruct0 size mismatch");
        if (@alignOf(__AnonStruct0) != 8) @compileError("__AnonStruct0 alignment mismatch");
    }
}

/// Element type for __AnonStruct5
pub const __AnonStruct5 = extern struct {
    @"freq": f32,
    @"ms": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct5) != 8) @compileError("__AnonStruct5 size mismatch");
        if (@alignOf(__AnonStruct5) != 4) @compileError("__AnonStruct5 alignment mismatch");
    }
}

/// Element type for __AnonStruct8
pub const __AnonStruct8 = extern struct {
    @"attack_ms": i32,
    @"decay_ms": i32,
    @"freq_end": f32,
    @"freq_start": f32,
    @"ms": i32,
    @"release_ms": i32,
    @"sustain": f32,
    @"volume": f32,
    @"waveform": u8,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct8) != 36) @compileError("__AnonStruct8 size mismatch");
        if (@alignOf(__AnonStruct8) != 4) @compileError("__AnonStruct8 alignment mismatch");
    }
}

/// Element type for __AnonStruct14
pub const __AnonStruct14 = extern struct {
    @"offset": __AnonStruct15,
    @"rotation": f32,
    @"target": __AnonStruct15,
    @"zoom": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct14) != 24) @compileError("__AnonStruct14 size mismatch");
        if (@alignOf(__AnonStruct14) != 4) @compileError("__AnonStruct14 alignment mismatch");
    }
}

/// Element type for __AnonStruct15
pub const __AnonStruct15 = extern struct {
    @"x": f32,
    @"y": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct15) != 8) @compileError("__AnonStruct15 size mismatch");
        if (@alignOf(__AnonStruct15) != 4) @compileError("__AnonStruct15 alignment mismatch");
    }
}

/// Element type for __AnonStruct17
pub const __AnonStruct17 = extern struct {
    @"center": __AnonStruct18,
    @"radius": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct17) != 16) @compileError("__AnonStruct17 size mismatch");
        if (@alignOf(__AnonStruct17) != 4) @compileError("__AnonStruct17 alignment mismatch");
    }
}

/// Element type for __AnonStruct18
pub const __AnonStruct18 = extern struct {
    @"x": f32,
    @"y": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct18) != 8) @compileError("__AnonStruct18 size mismatch");
        if (@alignOf(__AnonStruct18) != 4) @compileError("__AnonStruct18 alignment mismatch");
    }
}

/// Element type for Color
pub const Color = extern struct {
    @"a": u8,
    @"b": u8,
    @"g": u8,
    @"r": u8,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Color) != 4) @compileError("Color size mismatch");
        if (@alignOf(Color) != 1) @compileError("Color alignment mismatch");
    }
}

/// Element type for __AnonStruct21
pub const __AnonStruct21 = extern struct {
    @"center": __AnonStruct18,
    @"radius": f32,
    @"color_inner": Color,
    @"color_outer": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct21) != 20) @compileError("__AnonStruct21 size mismatch");
        if (@alignOf(__AnonStruct21) != 4) @compileError("__AnonStruct21 alignment mismatch");
    }
}

/// Element type for __AnonStruct22
pub const __AnonStruct22 = extern struct {
    @"center": __AnonStruct18,
    @"radius": f32,
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct22) != 20) @compileError("__AnonStruct22 size mismatch");
        if (@alignOf(__AnonStruct22) != 4) @compileError("__AnonStruct22 alignment mismatch");
    }
}

/// Element type for __AnonStruct23
pub const __AnonStruct23 = extern struct {
    @"pos": __AnonStruct18,
    @"size": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct23) != 16) @compileError("__AnonStruct23 size mismatch");
        if (@alignOf(__AnonStruct23) != 4) @compileError("__AnonStruct23 alignment mismatch");
    }
}

/// Element type for __AnonStruct24
pub const __AnonStruct24 = extern struct {
    @"end": __AnonStruct18,
    @"start": __AnonStruct18,
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct24) != 24) @compileError("__AnonStruct24 size mismatch");
        if (@alignOf(__AnonStruct24) != 4) @compileError("__AnonStruct24 alignment mismatch");
    }
}

/// Element type for __AnonStruct26
pub const __AnonStruct26 = extern struct {
    @"path": RocStr,
    @"size": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct26) != 32) @compileError("__AnonStruct26 size mismatch");
        if (@alignOf(__AnonStruct26) != 8) @compileError("__AnonStruct26 alignment mismatch");
    }
}

/// Element type for __AnonStruct29
pub const __AnonStruct29 = extern struct {
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct29) != 8) @compileError("__AnonStruct29 size mismatch");
        if (@alignOf(__AnonStruct29) != 4) @compileError("__AnonStruct29 alignment mismatch");
    }
}

/// Element type for __AnonStruct30
pub const __AnonStruct30 = extern struct {
    @"font": u64,
    @"text": RocStr,
    @"size": f32,
    @"spacing": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct30) != 40) @compileError("__AnonStruct30 size mismatch");
        if (@alignOf(__AnonStruct30) != 8) @compileError("__AnonStruct30 alignment mismatch");
    }
}

/// Element type for __AnonStruct31
pub const __AnonStruct31 = extern struct {
    @"points": RocListWith(__AnonStruct18, false),
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct31) != 32) @compileError("__AnonStruct31 size mismatch");
        if (@alignOf(__AnonStruct31) != 8) @compileError("__AnonStruct31 alignment mismatch");
    }
}

/// Element type for __AnonStruct33
pub const __AnonStruct33 = extern struct {
    @"points": RocListWith(__AnonStruct18, false),
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct33) != 32) @compileError("__AnonStruct33 size mismatch");
        if (@alignOf(__AnonStruct33) != 8) @compileError("__AnonStruct33 alignment mismatch");
    }
}

/// Element type for __AnonStruct34
pub const __AnonStruct34 = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct34) != 20) @compileError("__AnonStruct34 size mismatch");
        if (@alignOf(__AnonStruct34) != 4) @compileError("__AnonStruct34 alignment mismatch");
    }
}

/// Element type for __AnonStruct35
pub const __AnonStruct35 = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color_left": Color,
    @"color_right": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct35) != 24) @compileError("__AnonStruct35 size mismatch");
        if (@alignOf(__AnonStruct35) != 4) @compileError("__AnonStruct35 alignment mismatch");
    }
}

/// Element type for __AnonStruct36
pub const __AnonStruct36 = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color_bottom": Color,
    @"color_top": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct36) != 24) @compileError("__AnonStruct36 size mismatch");
        if (@alignOf(__AnonStruct36) != 4) @compileError("__AnonStruct36 alignment mismatch");
    }
}

/// Element type for __AnonStruct37
pub const __AnonStruct37 = extern struct {
    @"height": f32,
    @"thickness": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct37) != 24) @compileError("__AnonStruct37 size mismatch");
        if (@alignOf(__AnonStruct37) != 4) @compileError("__AnonStruct37 alignment mismatch");
    }
}

/// Element type for __AnonStruct38
pub const __AnonStruct38 = extern struct {
    @"height": f32,
    @"radius": f32,
    @"segments": i32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct38) != 28) @compileError("__AnonStruct38 size mismatch");
        if (@alignOf(__AnonStruct38) != 4) @compileError("__AnonStruct38 alignment mismatch");
    }
}

/// Element type for __AnonStruct39
pub const __AnonStruct39 = extern struct {
    @"height": f32,
    @"radius": f32,
    @"segments": i32,
    @"thickness": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct39) != 32) @compileError("__AnonStruct39 size mismatch");
        if (@alignOf(__AnonStruct39) != 4) @compileError("__AnonStruct39 alignment mismatch");
    }
}

/// Element type for __AnonStruct40
pub const __AnonStruct40 = extern struct {
    @"font": u64,
    @"text": RocStr,
    @"pos": __AnonStruct18,
    @"size": f32,
    @"spacing": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct40) != 56) @compileError("__AnonStruct40 size mismatch");
        if (@alignOf(__AnonStruct40) != 8) @compileError("__AnonStruct40 alignment mismatch");
    }
}

/// Element type for __AnonStruct41
pub const __AnonStruct41 = extern struct {
    @"texture": u64,
    @"dest": __AnonStruct42,
    @"origin": __AnonStruct15,
    @"rotation": f32,
    @"source": __AnonStruct42,
    @"tint": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct41) != 56) @compileError("__AnonStruct41 size mismatch");
        if (@alignOf(__AnonStruct41) != 8) @compileError("__AnonStruct41 alignment mismatch");
    }
}

/// Element type for __AnonStruct42
pub const __AnonStruct42 = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct42) != 16) @compileError("__AnonStruct42 size mismatch");
        if (@alignOf(__AnonStruct42) != 4) @compileError("__AnonStruct42 alignment mismatch");
    }
}

/// Element type for __AnonStruct43
pub const __AnonStruct43 = extern struct {
    @"a": __AnonStruct18,
    @"b": __AnonStruct18,
    @"c": __AnonStruct18,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct43) != 28) @compileError("__AnonStruct43 size mismatch");
        if (@alignOf(__AnonStruct43) != 4) @compileError("__AnonStruct43 alignment mismatch");
    }
}

/// Element type for __AnonStruct44
pub const __AnonStruct44 = extern struct {
    @"a": __AnonStruct18,
    @"b": __AnonStruct18,
    @"c": __AnonStruct18,
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct44) != 32) @compileError("__AnonStruct44 size mismatch");
        if (@alignOf(__AnonStruct44) != 4) @compileError("__AnonStruct44 alignment mismatch");
    }
}

/// Element type for __AnonStruct47
pub const __AnonStruct47 = extern struct {
    @"height": i32,
    @"width": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct47) != 8) @compileError("__AnonStruct47 size mismatch");
        if (@alignOf(__AnonStruct47) != 4) @compileError("__AnonStruct47 alignment mismatch");
    }
}

/// Element type for Host
pub const Host = extern struct {
    @"frame_count": u64,
    @"keys": RocListWith(u8, false),
    @"keys_pressed": RocListWith(u8, false),
    @"keys_released": RocListWith(u8, false),
    @"mouse": __AnonStruct56,
    @"timestamp_nanos": u64,
    @"frame_time": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Host) != 184) @compileError("Host size mismatch");
        if (@alignOf(Host) != 8) @compileError("Host alignment mismatch");
    }
}

/// Element type for __AnonStruct56
pub const __AnonStruct56 = extern struct {
    @"buttons": RocListWith(u8, false),
    @"buttons_pressed": RocListWith(u8, false),
    @"buttons_released": RocListWith(u8, false),
    @"wheel": f32,
    @"x": f32,
    @"y": f32,
    @"left": bool,
    @"middle": bool,
    @"right": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct56) != 88) @compileError("__AnonStruct56 size mismatch");
        if (@alignOf(__AnonStruct56) != 8) @compileError("__AnonStruct56 alignment mismatch");
    }
}

/// Element type for __AnonStruct58
pub const __AnonStruct58 = extern struct {
    @"contents": RocStr,
    @"err": u8,
    @"ok": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct58) != 32) @compileError("__AnonStruct58 size mismatch");
        if (@alignOf(__AnonStruct58) != 8) @compileError("__AnonStruct58 alignment mismatch");
    }
}

/// Element type for __AnonStruct61
pub const __AnonStruct61 = extern struct {
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct61) != 8) @compileError("__AnonStruct61 size mismatch");
        if (@alignOf(__AnonStruct61) != 4) @compileError("__AnonStruct61 alignment mismatch");
    }
}

/// Element type for __AnonStruct62
pub const __AnonStruct62 = extern struct {
    @"map": __AnonStruct64,
    @"err": u8,
    @"ok": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct62) != 216) @compileError("__AnonStruct62 size mismatch");
        if (@alignOf(__AnonStruct62) != 8) @compileError("__AnonStruct62 alignment mismatch");
    }
}

/// Element type for __AnonStruct64
pub const __AnonStruct64 = extern struct {
    @"gids": RocListWith(u64, false),
    @"height": u64,
    @"layers": RocList(__AnonStruct68),
    @"map_property_count": u64,
    @"map_property_start": u64,
    @"objects": RocList(__AnonStruct73),
    @"points": RocListWith(__AnonStruct75, false),
    @"properties": RocList(__AnonStruct77),
    @"tile_properties": RocListWith(__AnonStruct80, false),
    @"tilesets": RocList(__AnonStruct82),
    @"width": u64,
    @"tile_height": f32,
    @"tile_width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct64) != 208) @compileError("__AnonStruct64 size mismatch");
        if (@alignOf(__AnonStruct64) != 8) @compileError("__AnonStruct64 alignment mismatch");
    }
}

/// Element type for __AnonStruct68
pub const __AnonStruct68 = extern struct {
    @"gid_count": u64,
    @"gid_start": u64,
    @"height": u64,
    @"name": RocStr,
    @"property_count": u64,
    @"property_start": u64,
    @"width": u64,
    @"opacity": f32,
    @"visible": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct68) != 80) @compileError("__AnonStruct68 size mismatch");
        if (@alignOf(__AnonStruct68) != 8) @compileError("__AnonStruct68 alignment mismatch");
    }
}

/// Element type for __AnonStruct73
pub const __AnonStruct73 = extern struct {
    @"id": u64,
    @"name": RocStr,
    @"point_count": u64,
    @"point_start": u64,
    @"property_count": u64,
    @"property_start": u64,
    @"type_name": RocStr,
    @"height": f32,
    @"rotation": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"kind": u8,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct73) != 112) @compileError("__AnonStruct73 size mismatch");
        if (@alignOf(__AnonStruct73) != 8) @compileError("__AnonStruct73 alignment mismatch");
    }
}

/// Element type for __AnonStruct75
pub const __AnonStruct75 = extern struct {
    @"x": f32,
    @"y": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct75) != 8) @compileError("__AnonStruct75 size mismatch");
        if (@alignOf(__AnonStruct75) != 4) @compileError("__AnonStruct75 alignment mismatch");
    }
}

/// Element type for __AnonStruct77
pub const __AnonStruct77 = extern struct {
    @"integer": i64,
    @"name": RocStr,
    @"text": RocStr,
    @"number": f32,
    @"bool_value": bool,
    @"kind": u8,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct77) != 64) @compileError("__AnonStruct77 size mismatch");
        if (@alignOf(__AnonStruct77) != 8) @compileError("__AnonStruct77 alignment mismatch");
    }
}

/// Element type for __AnonStruct80
pub const __AnonStruct80 = extern struct {
    @"gid": u64,
    @"property_count": u64,
    @"property_start": u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct80) != 24) @compileError("__AnonStruct80 size mismatch");
        if (@alignOf(__AnonStruct80) != 8) @compileError("__AnonStruct80 alignment mismatch");
    }
}

/// Element type for __AnonStruct82
pub const __AnonStruct82 = extern struct {
    @"columns": u64,
    @"first_gid": u64,
    @"image_source": RocStr,
    @"name": RocStr,
    @"property_count": u64,
    @"property_start": u64,
    @"tile_count": u64,
    @"image_height": f32,
    @"image_width": f32,
    @"tile_height": f32,
    @"tile_width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct82) != 104) @compileError("__AnonStruct82 size mismatch");
        if (@alignOf(__AnonStruct82) != 8) @compileError("__AnonStruct82 alignment mismatch");
    }
}

/// Element type for __AnonStruct83
pub const __AnonStruct83 = extern struct {
    @"init!": __AnonStruct96,
    @"render!": *anyopaque,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct83) != 56) @compileError("__AnonStruct83 size mismatch");
        if (@alignOf(__AnonStruct83) != 8) @compileError("__AnonStruct83 alignment mismatch");
    }
}

/// Element type for __AnonStruct91
pub const __AnonStruct91 = extern struct {
    @"buttons": RocListWith(u8, false),
    @"buttons_pressed": RocListWith(u8, false),
    @"buttons_released": RocListWith(u8, false),
    @"wheel": f32,
    @"x": f32,
    @"y": f32,
    @"left": bool,
    @"middle": bool,
    @"right": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct91) != 88) @compileError("__AnonStruct91 size mismatch");
        if (@alignOf(__AnonStruct91) != 8) @compileError("__AnonStruct91 alignment mismatch");
    }
}

/// Element type for __AnonStruct96
pub const __AnonStruct96 = extern struct {
    @"config": __AnonStruct100,
    @"run!": *anyopaque,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct96) != 48) @compileError("__AnonStruct96 size mismatch");
        if (@alignOf(__AnonStruct96) != 8) @compileError("__AnonStruct96 alignment mismatch");
    }
}

/// Element type for __AnonStruct100
pub const __AnonStruct100 = extern struct {
    @"title": RocStr,
    @"height": i32,
    @"target_fps": i32,
    @"width": i32,
    @"cursor_visible": bool,
    @"fullscreen": bool,
    @"resizable": bool,
    @"vsync": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct100) != 40) @compileError("__AnonStruct100 size mismatch");
        if (@alignOf(__AnonStruct100) != 8) @compileError("__AnonStruct100 alignment mismatch");
    }
}

/// Element type for __AnonStruct104
pub const __AnonStruct104 = extern struct {
    @"title": RocStr,
    @"height": i32,
    @"target_fps": i32,
    @"width": i32,
    @"cursor_visible": bool,
    @"fullscreen": bool,
    @"resizable": bool,
    @"vsync": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct104) != 40) @compileError("__AnonStruct104 size mismatch");
        if (@alignOf(__AnonStruct104) != 8) @compileError("__AnonStruct104 alignment mismatch");
    }
}

/// Element type for __AnonStruct106
pub const __AnonStruct106 = extern struct {
    @"frame_count": u64,
    @"keys": RocListWith(u8, false),
    @"keys_pressed": RocListWith(u8, false),
    @"keys_released": RocListWith(u8, false),
    @"mouse_buttons": RocListWith(u8, false),
    @"mouse_buttons_pressed": RocListWith(u8, false),
    @"mouse_buttons_released": RocListWith(u8, false),
    @"timestamp_nanos": u64,
    @"frame_time": f32,
    @"mouse_wheel": f32,
    @"mouse_x": f32,
    @"mouse_y": f32,
    @"mouse_left": bool,
    @"mouse_middle": bool,
    @"mouse_right": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct106) != 184) @compileError("__AnonStruct106 size mismatch");
        if (@alignOf(__AnonStruct106) != 8) @compileError("__AnonStruct106 alignment mismatch");
    }
}

/// Tag discriminant for Try.
pub const TryTag = enum(u8) {
    Err = 0,
    Ok = 1,
};

/// Tag union: Try
pub const Try = extern struct {
    payload: extern union {
        err: *anyopaque,
        ok: RocStr,
    },
    tag: TryTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Try) != 32) @compileError("Try size mismatch");
        if (@alignOf(Try) != 8) @compileError("Try alignment mismatch");
    }
}

/// Return type record for Assets.load_texture_raw!
/// Fields ordered by alignment descending (Roc ABI)
pub const AssetsLoad_texture_rawRetRecord = extern struct {
    @"handle": u64,
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(AssetsLoad_texture_rawRetRecord) != 16) @compileError("AssetsLoad_texture_rawRetRecord size mismatch");
        if (@alignOf(AssetsLoad_texture_rawRetRecord) != 8) @compileError("AssetsLoad_texture_rawRetRecord alignment mismatch");
    }
}

/// Return type record for Draw.measure_text_raw!
/// Fields ordered by alignment descending (Roc ABI)
pub const DrawMeasure_text_rawRetRecord = extern struct {
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawMeasure_text_rawRetRecord) != 8) @compileError("DrawMeasure_text_rawRetRecord size mismatch");
        if (@alignOf(DrawMeasure_text_rawRetRecord) != 4) @compileError("DrawMeasure_text_rawRetRecord alignment mismatch");
    }
}

/// Return type record for Host.get_screen_size!
/// Fields ordered by alignment descending (Roc ABI)
pub const HostGet_screen_sizeRetRecord = extern struct {
    @"height": i32,
    @"width": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostGet_screen_sizeRetRecord) != 8) @compileError("HostGet_screen_sizeRetRecord size mismatch");
        if (@alignOf(HostGet_screen_sizeRetRecord) != 4) @compileError("HostGet_screen_sizeRetRecord alignment mismatch");
    }
}

/// Return type record for Host.read_file_raw!
/// Fields ordered by alignment descending (Roc ABI)
pub const HostRead_file_rawRetRecord = extern struct {
    @"contents": RocStr,
    @"err": u8,
    @"ok": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostRead_file_rawRetRecord) != 32) @compileError("HostRead_file_rawRetRecord size mismatch");
        if (@alignOf(HostRead_file_rawRetRecord) != 8) @compileError("HostRead_file_rawRetRecord alignment mismatch");
    }
}

/// Return type record for Tilemap.load_tmx_raw!
/// Fields ordered by alignment descending (Roc ABI)
pub const TilemapLoad_tmx_rawRetRecord = extern struct {
    @"map": __AnonStruct64,
    @"err": u8,
    @"ok": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(TilemapLoad_tmx_rawRetRecord) != 216) @compileError("TilemapLoad_tmx_rawRetRecord size mismatch");
        if (@alignOf(TilemapLoad_tmx_rawRetRecord) != 8) @compileError("TilemapLoad_tmx_rawRetRecord alignment mismatch");
    }
}


// =============================================================================
// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.
// =============================================================================

pub extern fn roc_alloc(length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dealloc(ptr: *anyopaque, alignment: usize) callconv(.c) void;
pub extern fn roc_realloc(ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dbg(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_expect_failed(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_crashed(bytes: [*]const u8, len: usize) callconv(.c) void;

// =============================================================================
// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.
// =============================================================================

/// Hosted symbol for Assets.load_texture_raw!
/// Roc signature: Str => { handle : U64, height : F32, width : F32 }
pub extern fn roc_assets_load_texture_raw(arg0: RocStr) callconv(.c) __AnonStruct0;

/// Hosted symbol for Audio.gen_sound_raw!
/// Roc signature: { attack_ms : I32, decay_ms : I32, freq_end : F32, freq_start : F32, ms : I32, release_ms : I32, sustain : F32, volume : F32, waveform : U8 } => U64
pub extern fn roc_audio_gen_sound_raw(arg0: __AnonStruct8) callconv(.c) u64;

/// Hosted symbol for Audio.gen_tone_raw!
/// Roc signature: { freq : F32, ms : I32 } => U64
pub extern fn roc_audio_gen_tone_raw(arg0: __AnonStruct5) callconv(.c) u64;

/// Hosted symbol for Audio.load_music_raw!
/// Roc signature: Str => U64
pub extern fn roc_audio_load_music_raw(arg0: RocStr) callconv(.c) u64;

/// Hosted symbol for Audio.load_sound_raw!
/// Roc signature: Str => U64
pub extern fn roc_audio_load_sound_raw(arg0: RocStr) callconv(.c) u64;

/// Hosted symbol for Audio.pause_music_raw!
/// Roc signature: U64 => {}
pub extern fn roc_audio_pause_music_raw(arg0: u64) callconv(.c) void;

/// Hosted symbol for Audio.play_music_raw!
/// Roc signature: U64 => {}
pub extern fn roc_audio_play_music_raw(arg0: u64) callconv(.c) void;

/// Hosted symbol for Audio.play_raw!
/// Roc signature: U64 => {}
pub extern fn roc_audio_play_raw(arg0: u64) callconv(.c) void;

/// Hosted symbol for Audio.resume_music_raw!
/// Roc signature: U64 => {}
pub extern fn roc_audio_resume_music_raw(arg0: u64) callconv(.c) void;

/// Hosted symbol for Audio.set_music_looping_raw!
/// Roc signature: U64, Bool => {}
pub extern fn roc_audio_set_music_looping_raw(arg0: u64, arg1: bool) callconv(.c) void;

/// Hosted symbol for Audio.set_music_pan_raw!
/// Roc signature: U64, F32 => {}
pub extern fn roc_audio_set_music_pan_raw(arg0: u64, arg1: f32) callconv(.c) void;

/// Hosted symbol for Audio.set_music_pitch_raw!
/// Roc signature: U64, F32 => {}
pub extern fn roc_audio_set_music_pitch_raw(arg0: u64, arg1: f32) callconv(.c) void;

/// Hosted symbol for Audio.set_music_volume_raw!
/// Roc signature: U64, F32 => {}
pub extern fn roc_audio_set_music_volume_raw(arg0: u64, arg1: f32) callconv(.c) void;

/// Hosted symbol for Audio.set_pan_raw!
/// Roc signature: U64, F32 => {}
pub extern fn roc_audio_set_pan_raw(arg0: u64, arg1: f32) callconv(.c) void;

/// Hosted symbol for Audio.set_pitch_raw!
/// Roc signature: U64, F32 => {}
pub extern fn roc_audio_set_pitch_raw(arg0: u64, arg1: f32) callconv(.c) void;

/// Hosted symbol for Audio.set_volume_raw!
/// Roc signature: U64, F32 => {}
pub extern fn roc_audio_set_volume_raw(arg0: u64, arg1: f32) callconv(.c) void;

/// Hosted symbol for Audio.stop_music_raw!
/// Roc signature: U64 => {}
pub extern fn roc_audio_stop_music_raw(arg0: u64) callconv(.c) void;

/// Hosted symbol for Draw.begin_camera!
/// Roc signature: { offset : { x : F32, y : F32 }, rotation : F32, target : { x : F32, y : F32 }, zoom : F32 } => {}
pub extern fn roc_draw_begin_camera(arg0: __AnonStruct14) callconv(.c) void;

/// Hosted symbol for Draw.begin_frame!
/// Roc signature: {} => {}
pub extern fn roc_draw_begin_frame() callconv(.c) void;

/// Hosted symbol for Draw.circle_gradient!
/// Roc signature: { center : { x : F32, y : F32 }, color_inner : Color, color_outer : Color, radius : F32 } => {}
pub extern fn roc_draw_circle_gradient(arg0: __AnonStruct21) callconv(.c) void;

/// Hosted symbol for Draw.circle_lines_raw!
/// Roc signature: { center : { x : F32, y : F32 }, color : Color, radius : F32, thickness : F32 } => {}
pub extern fn roc_draw_circle_lines_raw(arg0: __AnonStruct22) callconv(.c) void;

/// Hosted symbol for Draw.circle_raw!
/// Roc signature: { center : { x : F32, y : F32 }, color : Color, radius : F32 } => {}
pub extern fn roc_draw_circle_raw(arg0: __AnonStruct17) callconv(.c) void;

/// Hosted symbol for Draw.clear!
/// Roc signature: Color => {}
pub extern fn roc_draw_clear(arg0: Color) callconv(.c) void;

/// Hosted symbol for Draw.draw_texture_raw!
/// Roc signature: { dest : { height : F32, width : F32, x : F32, y : F32 }, origin : { x : F32, y : F32 }, rotation : F32, source : { height : F32, width : F32, x : F32, y : F32 }, texture : U64, tint : Color } => {}
pub extern fn roc_draw_draw_texture_raw(arg0: __AnonStruct41) callconv(.c) void;

/// Hosted symbol for Draw.end_camera!
/// Roc signature: {} => {}
pub extern fn roc_draw_end_camera() callconv(.c) void;

/// Hosted symbol for Draw.end_frame!
/// Roc signature: {} => {}
pub extern fn roc_draw_end_frame() callconv(.c) void;

/// Hosted symbol for Draw.fps!
/// Roc signature: { color : Color, pos : { x : F32, y : F32 }, size : F32 } => {}
pub extern fn roc_draw_fps(arg0: __AnonStruct23) callconv(.c) void;

/// Hosted symbol for Draw.line_raw!
/// Roc signature: { color : Color, end : { x : F32, y : F32 }, start : { x : F32, y : F32 }, thickness : F32 } => {}
pub extern fn roc_draw_line_raw(arg0: __AnonStruct24) callconv(.c) void;

/// Hosted symbol for Draw.load_font_raw!
/// Roc signature: { path : Str, size : I32 } => U64
pub extern fn roc_draw_load_font_raw(arg0: __AnonStruct26) callconv(.c) u64;

/// Hosted symbol for Draw.measure_text_raw!
/// Roc signature: { font : U64, size : F32, spacing : F32, text : Str } => { height : F32, width : F32 }
pub extern fn roc_draw_measure_text_raw(arg0: __AnonStruct30) callconv(.c) __AnonStruct29;

/// Hosted symbol for Draw.polygon_lines_raw!
/// Roc signature: { color : Color, points : List({ x : F32, y : F32 }), thickness : F32 } => {}
pub extern fn roc_draw_polygon_lines_raw(arg0: __AnonStruct33) callconv(.c) void;

/// Hosted symbol for Draw.polygon_raw!
/// Roc signature: { color : Color, points : List({ x : F32, y : F32 }) } => {}
pub extern fn roc_draw_polygon_raw(arg0: __AnonStruct31) callconv(.c) void;

/// Hosted symbol for Draw.rectangle_gradient_h!
/// Roc signature: { color_left : Color, color_right : Color, height : F32, width : F32, x : F32, y : F32 } => {}
pub extern fn roc_draw_rectangle_gradient_h(arg0: __AnonStruct35) callconv(.c) void;

/// Hosted symbol for Draw.rectangle_gradient_v!
/// Roc signature: { color_bottom : Color, color_top : Color, height : F32, width : F32, x : F32, y : F32 } => {}
pub extern fn roc_draw_rectangle_gradient_v(arg0: __AnonStruct36) callconv(.c) void;

/// Hosted symbol for Draw.rectangle_lines_raw!
/// Roc signature: { color : Color, height : F32, thickness : F32, width : F32, x : F32, y : F32 } => {}
pub extern fn roc_draw_rectangle_lines_raw(arg0: __AnonStruct37) callconv(.c) void;

/// Hosted symbol for Draw.rectangle_raw!
/// Roc signature: { color : Color, height : F32, width : F32, x : F32, y : F32 } => {}
pub extern fn roc_draw_rectangle_raw(arg0: __AnonStruct34) callconv(.c) void;

/// Hosted symbol for Draw.rounded_rectangle_lines_raw!
/// Roc signature: { color : Color, height : F32, radius : F32, segments : I32, thickness : F32, width : F32, x : F32, y : F32 } => {}
pub extern fn roc_draw_rounded_rectangle_lines_raw(arg0: __AnonStruct39) callconv(.c) void;

/// Hosted symbol for Draw.rounded_rectangle_raw!
/// Roc signature: { color : Color, height : F32, radius : F32, segments : I32, width : F32, x : F32, y : F32 } => {}
pub extern fn roc_draw_rounded_rectangle_raw(arg0: __AnonStruct38) callconv(.c) void;

/// Hosted symbol for Draw.text_raw!
/// Roc signature: { color : Color, font : U64, pos : { x : F32, y : F32 }, size : F32, spacing : F32, text : Str } => {}
pub extern fn roc_draw_text_raw(arg0: __AnonStruct40) callconv(.c) void;

/// Hosted symbol for Draw.triangle_lines_raw!
/// Roc signature: { a : { x : F32, y : F32 }, b : { x : F32, y : F32 }, c : { x : F32, y : F32 }, color : Color, thickness : F32 } => {}
pub extern fn roc_draw_triangle_lines_raw(arg0: __AnonStruct44) callconv(.c) void;

/// Hosted symbol for Draw.triangle_raw!
/// Roc signature: { a : { x : F32, y : F32 }, b : { x : F32, y : F32 }, c : { x : F32, y : F32 }, color : Color } => {}
pub extern fn roc_draw_triangle_raw(arg0: __AnonStruct43) callconv(.c) void;

/// Hosted symbol for Host.exit!
/// Roc signature: I32 => {}
pub extern fn roc_host_exit(arg0: i32) callconv(.c) void;

/// Hosted symbol for Host.get_screen_size!
/// Roc signature: {} => { height : I32, width : I32 }
pub extern fn roc_host_get_screen_size() callconv(.c) __AnonStruct47;

/// Hosted symbol for Host.random_i32!
/// Roc signature: I32, I32 => I32
pub extern fn roc_host_random_i32(arg0: i32, arg1: i32) callconv(.c) i32;

/// Hosted symbol for Host.read_env!
/// Roc signature: Host, Str => Try(Str, [NotFound])
pub extern fn roc_host_read_env(arg0: Host, arg1: RocStr) callconv(.c) Try;

/// Hosted symbol for Host.read_file_raw!
/// Roc signature: Str => { contents : Str, err : U8, ok : Bool }
pub extern fn roc_host_read_file_raw(arg0: RocStr) callconv(.c) __AnonStruct58;

/// Hosted symbol for Host.set_screen_size!
/// Roc signature: { height : F32, width : F32 } => Try({}, [NotSupported])
pub extern fn roc_host_set_screen_size(arg0: __AnonStruct61) callconv(.c) Try;

/// Hosted symbol for Host.set_target_fps!
/// Roc signature: I32 => {}
pub extern fn roc_host_set_target_fps(arg0: i32) callconv(.c) void;

/// Hosted symbol for Tilemap.load_tmx_raw!
/// Roc signature: Str => { err : U8, map : { gids : List(U64), height : U64, layers : List({ gid_count : U64, gid_start : U64, height : U64, name : Str, opacity : F32, property_count : U64, property_start : U64, visible : Bool, width : U64 }), map_property_count : U64, map_property_start : U64, objects : List({ height : F32, id : U64, kind : U8, name : Str, point_count : U64, point_start : U64, property_count : U64, property_start : U64, rotation : F32, type_name : Str, width : F32, x : F32, y : F32 }), points : List({ x : F32, y : F32 }), properties : List({ bool_value : Bool, integer : I64, kind : U8, name : Str, number : F32, text : Str }), tile_height : F32, tile_properties : List({ gid : U64, property_count : U64, property_start : U64 }), tile_width : F32, tilesets : List({ columns : U64, first_gid : U64, image_height : F32, image_source : Str, image_width : F32, name : Str, property_count : U64, property_start : U64, tile_count : U64, tile_height : F32, tile_width : F32 }), width : U64 }, ok : Bool }
pub extern fn roc_tilemap_load_tmx_raw(arg0: RocStr) callconv(.c) __AnonStruct62;


/// Default memory management functions for Roc platforms.
///
/// Uses `RocEnv.allocator` for allocation. Each allocation prepends
/// size metadata so that dealloc/realloc can recover the original
/// allocation size (required because `roc_dealloc` receives no length).
pub const DefaultAllocators = struct {
    /// Allocate memory for the Roc runtime.
    pub fn rocAlloc(roc_host: *RocHost, length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;
        const total_size = length + size_storage_bytes;

        const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_alloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Store total size immediately before the user data pointer
        const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
        size_ptr.* = total_size;

        return @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
    }

    /// Free memory previously allocated by `rocAlloc`.
    pub fn rocDealloc(roc_host: *RocHost, ptr: *anyopaque, alignment: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        const size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const total_size = size_ptr.*;

        const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);
        const slice = base_ptr[0..total_size];
        allocator.rawFree(slice, align_enum, @returnAddress());
    }

    /// Reallocate memory, copying existing data to the new allocation.
    pub fn rocRealloc(roc_host: *RocHost, ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        // Read old size from metadata
        const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const old_total_size = old_size_ptr.*;
        const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);

        // Allocate new block
        const new_total_size = new_length + size_storage_bytes;
        const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_realloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Copy old user data to new location
        const old_user_data_size = old_total_size - size_storage_bytes;
        const copy_size = @min(old_user_data_size, new_length);
        const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
        const old_user_ptr: [*]const u8 = @ptrCast(ptr);
        @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

        // Free old allocation
        allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

        // Store new size and return user pointer
        const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
        new_size_ptr.* = new_total_size;
        return new_user_ptr;
    }
};

/// Default handlers for dbg, expect-failed, and crash.
///
/// Routes output through `RocEnv.roc_io` for platform portability.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC DBG] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC EXPECT] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a `crash` message to stderr and terminate.
    pub fn rocCrashed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC CRASHED] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
        env.roc_io.onFatal();
    }
};

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
///
/// Example:
/// ```zig
/// var env = RocEnv{ .allocator = gpa.allocator(), .roc_io = RocIo.default() };
/// var roc_host = makeRocHost(&env);
/// ```
pub fn makeRocHost(env: *RocEnv) RocHost {
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &DefaultAllocators.rocAlloc,
        .roc_dealloc = &DefaultAllocators.rocDealloc,
        .roc_realloc = &DefaultAllocators.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
    };
}

// =============================================================================
// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.
// =============================================================================

/// Entrypoint: app_config_for_host!
pub extern fn app_config_for_host() callconv(.c) __AnonStruct104;

/// Entrypoint: init_for_host!
pub extern fn init_for_host(arg0: __AnonStruct106) callconv(.c) Try;

/// Entrypoint: render_for_host!
pub extern fn render_for_host(arg0: RocBox, arg1: __AnonStruct106) callconv(.c) Try;

/// Entrypoint: drop_model_for_host!
pub extern fn drop_model_for_host(arg0: RocBox) callconv(.c) void;
