//! Roc Platform ABI
//!
//! This file defines the Zig interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Usage:
//! 1. Import this file in your platform host
//! 2. Implement each hosted function according to its signature
//! 3. Call hostedFunctions() to create the dispatch table for RocOps

const std = @import("std");

/// Type-erased function pointer for hosted function dispatch.
pub const HostedFn = *const fn (*anyopaque, *anyopaque, *anyopaque) callconv(.c) void;

/// Table of hosted function pointers passed to the Roc runtime.
pub const HostedFunctions = extern struct {
    count: u32,
    fns: [*]HostedFn,
};

/// Arguments for a Roc allocation request.
pub const RocAlloc = extern struct { alignment: usize, length: usize, answer: *anyopaque };
/// Arguments for a Roc deallocation request.
pub const RocDealloc = extern struct { alignment: usize, ptr: *anyopaque };
/// Arguments for a Roc reallocation request.
pub const RocRealloc = extern struct { alignment: usize, new_length: usize, answer: *anyopaque };
/// Arguments for a Roc `dbg` expression.
pub const RocDbg = extern struct { utf8_bytes: [*]u8, len: usize };
/// Arguments for a failed Roc `expect`.
pub const RocExpectFailed = extern struct { utf8_bytes: [*]u8, len: usize };
/// Arguments for a Roc `crash`.
pub const RocCrashed = extern struct { utf8_bytes: [*]u8, len: usize };

/// The operations table passed from the host to the Roc runtime.
pub const RocOps = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocAlloc, *anyopaque) callconv(.c) void,
    roc_dealloc: *const fn (*RocDealloc, *anyopaque) callconv(.c) void,
    roc_realloc: *const fn (*RocRealloc, *anyopaque) callconv(.c) void,
    roc_dbg: *const fn (*const RocDbg, *anyopaque) callconv(.c) void,
    roc_expect_failed: *const fn (*const RocExpectFailed, *anyopaque) callconv(.c) void,
    roc_crashed: *const fn (*const RocCrashed, *anyopaque) callconv(.c) void,
    hosted_fns: HostedFunctions,
};

/// Type-erase a hosted function pointer to `HostedFn`.
///
/// Hosted functions are typically written with concrete parameter types for clarity
/// (e.g. `*RocOps`, `*RocStr`, `[*]u8`), but must be stored as `HostedFn` which
/// uses `*anyopaque` for all parameters. This helper performs that cast.
pub fn hostedFn(func: anytype) HostedFn {
    const T = @TypeOf(func);
    const info = @typeInfo(T);
    if (info == .pointer) {
        const child = @typeInfo(info.pointer.child);
        if (child == .@"fn") {
            const f = child.@"fn";
            if (f.params.len != 3)
                @compileError("hostedFn: function must take exactly 3 parameters (ops, ret_ptr, args_ptr)");
            if (f.return_type != void)
                @compileError("hostedFn: function must return void");
        }
    }
    return @ptrCast(func);
}

/// Comptime constructor for Roc's `Try(Ok, Err)` result type.
///
/// Roc's `Try(ok, err)` is the tag union `[Ok(ok), Err(err)]`.
/// Layout: payload extern union at offset 0, u8 discriminant after.
/// Discriminant values: Err = 0, Ok = 1 (alphabetical).
///
/// Example: `Try(*anyopaque, i32)` for `Try(Box(Model), I32)`.
pub fn Try(comptime Ok: type, comptime Err: type) type {
    const OkField = if (@sizeOf(Ok) == 0) [0]u8 else Ok;
    const ErrField = if (@sizeOf(Err) == 0) [0]u8 else Err;
    return extern struct {
        payload: extern union {
            err: ErrField,
            ok: OkField,
        },
        tag: TryTag,
        pub const TryTag = enum(u8) { Err = 0, Ok = 1 };
    };
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    length: usize,
    capacity_or_alloc_ptr: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const seamless_slice_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length & ~seamless_slice_bit;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.capacity_or_alloc_ptr)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .length = 0, .capacity_or_alloc_ptr = seamless_slice_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_ops` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_ops: *RocOps) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            var alloc_args: RocAlloc = .{
                .alignment = @alignOf(usize),
                .length = total,
                .answer = undefined,
            };
            roc_ops.roc_alloc(&alloc_args, roc_ops.env);
            const base: [*]u8 = @ptrCast(alloc_args.answer);
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .length = slice.len,
                .capacity_or_alloc_ptr = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_ops: *RocOps) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            var dealloc_args: RocDealloc = .{ .alignment = @alignOf(usize), .ptr = base };
            roc_ops.roc_dealloc(&dealloc_args, roc_ops.env);
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        if (self.capacity_or_alloc_ptr == 0) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr << 1));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_ops: *RocOps) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            var alloc_args: RocAlloc = .{
                .alignment = alloc_align,
                .length = total,
                .answer = undefined,
            };
            roc_ops.roc_alloc(&alloc_args, roc_ops.env);
            const base: [*]u8 = @ptrCast(alloc_args.answer);
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_ops: *RocOps) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_ops);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Decrement the reference count; frees the allocation when it reaches zero.
        pub fn decref(self: Self, roc_ops: *RocOps) void {
            const ptr = self.elements_ptr orelse return;
            const data_addr = @intFromPtr(ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                var dealloc_args: RocDealloc = .{
                    .alignment = alloc_align,
                    .ptr = base,
                };
                roc_ops.roc_dealloc(&dealloc_args, roc_ops.env);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const ptr = self.elements_ptr orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(isize));
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const ptr = self.elements_ptr orelse return true;
            if (self.capacity_or_alloc_ptr == 0) return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(isize));
            return rc.* == 1;
        }
    };
}

/// Element type for __AnonStruct2
pub const __AnonStruct2 = extern struct {
    center: __AnonStruct3,
    radius: f32,
    color: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct2) != 16) @compileError("__AnonStruct2 size mismatch");
        if (@alignOf(__AnonStruct2) != 4) @compileError("__AnonStruct2 alignment mismatch");
    }
}

/// Element type for __AnonStruct3
pub const __AnonStruct3 = extern struct {
    x: f32,
    y: f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct3) != 8) @compileError("__AnonStruct3 size mismatch");
        if (@alignOf(__AnonStruct3) != 4) @compileError("__AnonStruct3 alignment mismatch");
    }
}

/// Element type for __AnonStruct9
pub const __AnonStruct9 = extern struct {
    center: __AnonStruct10,
    radius: f32,
    color_inner: Color,
    color_outer: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct9) != 16) @compileError("__AnonStruct9 size mismatch");
        if (@alignOf(__AnonStruct9) != 4) @compileError("__AnonStruct9 alignment mismatch");
    }
}

/// Element type for __AnonStruct10
pub const __AnonStruct10 = extern struct {
    x: f32,
    y: f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct10) != 8) @compileError("__AnonStruct10 size mismatch");
        if (@alignOf(__AnonStruct10) != 4) @compileError("__AnonStruct10 alignment mismatch");
    }
}

/// Element type for __AnonStruct20
pub const __AnonStruct20 = extern struct {
    end: __AnonStruct22,
    start: __AnonStruct25,
    color: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct20) != 20) @compileError("__AnonStruct20 size mismatch");
        if (@alignOf(__AnonStruct20) != 4) @compileError("__AnonStruct20 alignment mismatch");
    }
}

/// Element type for __AnonStruct22
pub const __AnonStruct22 = extern struct {
    x: f32,
    y: f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct22) != 8) @compileError("__AnonStruct22 size mismatch");
        if (@alignOf(__AnonStruct22) != 4) @compileError("__AnonStruct22 alignment mismatch");
    }
}

/// Element type for __AnonStruct25
pub const __AnonStruct25 = extern struct {
    x: f32,
    y: f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct25) != 8) @compileError("__AnonStruct25 size mismatch");
        if (@alignOf(__AnonStruct25) != 4) @compileError("__AnonStruct25 alignment mismatch");
    }
}

/// Element type for __AnonStruct29
pub const __AnonStruct29 = extern struct {
    height: f32,
    width: f32,
    x: f32,
    y: f32,
    color: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct29) != 20) @compileError("__AnonStruct29 size mismatch");
        if (@alignOf(__AnonStruct29) != 4) @compileError("__AnonStruct29 alignment mismatch");
    }
}

/// Element type for __AnonStruct36
pub const __AnonStruct36 = extern struct {
    height: f32,
    width: f32,
    x: f32,
    y: f32,
    color_left: Color,
    color_right: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct36) != 20) @compileError("__AnonStruct36 size mismatch");
        if (@alignOf(__AnonStruct36) != 4) @compileError("__AnonStruct36 alignment mismatch");
    }
}

/// Element type for __AnonStruct44
pub const __AnonStruct44 = extern struct {
    height: f32,
    width: f32,
    x: f32,
    y: f32,
    color_bottom: Color,
    color_top: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct44) != 20) @compileError("__AnonStruct44 size mismatch");
        if (@alignOf(__AnonStruct44) != 4) @compileError("__AnonStruct44 alignment mismatch");
    }
}

/// Element type for __AnonStruct52
pub const __AnonStruct52 = extern struct {
    text: RocStr,
    pos: __AnonStruct54,
    size: i32,
    color: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct52) != 40) @compileError("__AnonStruct52 size mismatch");
        if (@alignOf(__AnonStruct52) != 8) @compileError("__AnonStruct52 alignment mismatch");
    }
}

/// Element type for __AnonStruct54
pub const __AnonStruct54 = extern struct {
    x: f32,
    y: f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct54) != 8) @compileError("__AnonStruct54 size mismatch");
        if (@alignOf(__AnonStruct54) != 4) @compileError("__AnonStruct54 alignment mismatch");
    }
}

/// Element type for __AnonStruct61
pub const __AnonStruct61 = extern struct {
    height: i32,
    width: i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct61) != 8) @compileError("__AnonStruct61 size mismatch");
        if (@alignOf(__AnonStruct61) != 4) @compileError("__AnonStruct61 alignment mismatch");
    }
}

/// Element type for Host
pub const Host = extern struct {
    frame_count: u64,
    keys: Keys,
    mouse: __AnonStruct72,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Host) != 48) @compileError("Host size mismatch");
        if (@alignOf(Host) != 8) @compileError("Host alignment mismatch");
    }
}

/// Element type for Keys
pub const Keys = extern struct {
    data: RocListWith(u8, false),
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Keys) != 24) @compileError("Keys size mismatch");
        if (@alignOf(Keys) != 8) @compileError("Keys alignment mismatch");
    }
}

/// Element type for __AnonStruct72
pub const __AnonStruct72 = extern struct {
    wheel: f32,
    x: f32,
    y: f32,
    left: bool,
    middle: bool,
    right: bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct72) != 16) @compileError("__AnonStruct72 size mismatch");
        if (@alignOf(__AnonStruct72) != 4) @compileError("__AnonStruct72 alignment mismatch");
    }
}

/// Element type for __AnonStruct83
pub const __AnonStruct83 = extern struct {
    height: f32,
    width: f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct83) != 8) @compileError("__AnonStruct83 size mismatch");
        if (@alignOf(__AnonStruct83) != 4) @compileError("__AnonStruct83 alignment mismatch");
    }
}

/// Element type for __AnonStruct88
pub const __AnonStruct88 = extern struct {
    @"init!": *anyopaque,
    @"render!": *anyopaque,
};

/// Element type for __AnonStruct96
pub const __AnonStruct96 = extern struct {
    wheel: f32,
    x: f32,
    y: f32,
    left: bool,
    middle: bool,
    right: bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct96) != 16) @compileError("__AnonStruct96 size mismatch");
        if (@alignOf(__AnonStruct96) != 4) @compileError("__AnonStruct96 alignment mismatch");
    }
}

/// Element type for __AnonStruct112
pub const __AnonStruct112 = extern struct {
    wheel: f32,
    x: f32,
    y: f32,
    left: bool,
    middle: bool,
    right: bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct112) != 16) @compileError("__AnonStruct112 size mismatch");
        if (@alignOf(__AnonStruct112) != 4) @compileError("__AnonStruct112 alignment mismatch");
    }
}

/// Element type for __AnonStruct123
pub const __AnonStruct123 = extern struct {
    frame_count: u64,
    keys: RocListWith(u8, false),
    mouse_wheel: f32,
    mouse_x: f32,
    mouse_y: f32,
    mouse_left: bool,
    mouse_middle: bool,
    mouse_right: bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct123) != 48) @compileError("__AnonStruct123 size mismatch");
        if (@alignOf(__AnonStruct123) != 8) @compileError("__AnonStruct123 alignment mismatch");
    }
}

/// Element type for __AnonStruct137
pub const __AnonStruct137 = extern struct {
    frame_count: u64,
    keys: RocListWith(u8, false),
    mouse_wheel: f32,
    mouse_x: f32,
    mouse_y: f32,
    mouse_left: bool,
    mouse_middle: bool,
    mouse_right: bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct137) != 48) @compileError("__AnonStruct137 size mismatch");
        if (@alignOf(__AnonStruct137) != 8) @compileError("__AnonStruct137 alignment mismatch");
    }
}

/// Tag union: Color
pub const Color = enum(u8) {
    black = 0,
    blue = 1,
    dark_gray = 2,
    gray = 3,
    green = 4,
    light_gray = 5,
    orange = 6,
    pink = 7,
    purple = 8,
    ray_white = 9,
    red = 10,
    white = 11,
    yellow = 12,
};

/// Return type record for Host.get_screen_size!
/// Fields ordered by alignment descending (Roc ABI)
pub const HostGet_screen_sizeRetRecord = extern struct {
    height: i32,
    width: i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostGet_screen_sizeRetRecord) != 8) @compileError("HostGet_screen_sizeRetRecord size mismatch");
        if (@alignOf(HostGet_screen_sizeRetRecord) != 4) @compileError("HostGet_screen_sizeRetRecord alignment mismatch");
    }
}

/// Arguments for Draw.circle!
/// Roc signature: Draw.Circle => {}
/// Fields ordered by alignment descending (Roc ABI)
pub const DrawCircleArgs = extern struct {
    center: __AnonStruct3,
    radius: f32,
    color: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawCircleArgs) != 16) @compileError("DrawCircleArgs size mismatch");
        if (@alignOf(DrawCircleArgs) != 4) @compileError("DrawCircleArgs alignment mismatch");
    }
}

/// Arguments for Draw.circle_gradient!
/// Roc signature: Draw.CircleGradient => {}
/// Fields ordered by alignment descending (Roc ABI)
pub const DrawCircle_gradientArgs = extern struct {
    center: __AnonStruct10,
    radius: f32,
    color_inner: Color,
    color_outer: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawCircle_gradientArgs) != 16) @compileError("DrawCircle_gradientArgs size mismatch");
        if (@alignOf(DrawCircle_gradientArgs) != 4) @compileError("DrawCircle_gradientArgs alignment mismatch");
    }
}

/// Arguments for Draw.clear!
/// Roc signature: Color => {}
pub const DrawClearArgs = extern struct {
    arg0: Color,
};

/// Arguments for Draw.line!
/// Roc signature: Draw.Line => {}
/// Fields ordered by alignment descending (Roc ABI)
pub const DrawLineArgs = extern struct {
    end: __AnonStruct22,
    start: __AnonStruct25,
    color: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawLineArgs) != 20) @compileError("DrawLineArgs size mismatch");
        if (@alignOf(DrawLineArgs) != 4) @compileError("DrawLineArgs alignment mismatch");
    }
}

/// Arguments for Draw.rectangle!
/// Roc signature: Draw.Rectangle => {}
/// Fields ordered by alignment descending (Roc ABI)
pub const DrawRectangleArgs = extern struct {
    height: f32,
    width: f32,
    x: f32,
    y: f32,
    color: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawRectangleArgs) != 20) @compileError("DrawRectangleArgs size mismatch");
        if (@alignOf(DrawRectangleArgs) != 4) @compileError("DrawRectangleArgs alignment mismatch");
    }
}

/// Arguments for Draw.rectangle_gradient_h!
/// Roc signature: Draw.RectangleGradientH => {}
/// Fields ordered by alignment descending (Roc ABI)
pub const DrawRectangle_gradient_hArgs = extern struct {
    height: f32,
    width: f32,
    x: f32,
    y: f32,
    color_left: Color,
    color_right: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawRectangle_gradient_hArgs) != 20) @compileError("DrawRectangle_gradient_hArgs size mismatch");
        if (@alignOf(DrawRectangle_gradient_hArgs) != 4) @compileError("DrawRectangle_gradient_hArgs alignment mismatch");
    }
}

/// Arguments for Draw.rectangle_gradient_v!
/// Roc signature: Draw.RectangleGradientV => {}
/// Fields ordered by alignment descending (Roc ABI)
pub const DrawRectangle_gradient_vArgs = extern struct {
    height: f32,
    width: f32,
    x: f32,
    y: f32,
    color_bottom: Color,
    color_top: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawRectangle_gradient_vArgs) != 20) @compileError("DrawRectangle_gradient_vArgs size mismatch");
        if (@alignOf(DrawRectangle_gradient_vArgs) != 4) @compileError("DrawRectangle_gradient_vArgs alignment mismatch");
    }
}

/// Arguments for Draw.text!
/// Roc signature: Draw.Text => {}
/// Fields ordered by alignment descending (Roc ABI)
pub const DrawTextArgs = if (@sizeOf(usize) == 8) extern struct {
    text: RocStr,
    pos: __AnonStruct54,
    size: i32,
    color: Color,
} else extern struct {
    pos: __AnonStruct54,
    size: i32,
    text: RocStr,
    color: Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
    if (@sizeOf(DrawTextArgs) != 40) @compileError("DrawTextArgs size mismatch");
    if (@alignOf(DrawTextArgs) != 8) @compileError("DrawTextArgs alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
    if (@sizeOf(DrawTextArgs) != 28) @compileError("DrawTextArgs size mismatch");
    if (@alignOf(DrawTextArgs) != 4) @compileError("DrawTextArgs alignment mismatch");
    }
}

/// Arguments for Host.exit!
/// Roc signature: I32 => {}
pub const HostExitArgs = extern struct {
    arg0: i32,
};

/// Arguments for Host.read_env!
/// Roc signature: Host, Str => Try(Str, [NotFound, ..])
pub const HostRead_envArgs = extern struct {
    arg0: Host,
    arg1: RocStr,
};

/// Arguments for Host.set_screen_size!
/// Roc signature: { height: F32, width: F32 } => Try({}, [NotSupported, ..])
/// Fields ordered by alignment descending (Roc ABI)
pub const HostSet_screen_sizeArgs = extern struct {
    height: f32,
    width: f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostSet_screen_sizeArgs) != 8) @compileError("HostSet_screen_sizeArgs size mismatch");
        if (@alignOf(HostSet_screen_sizeArgs) != 4) @compileError("HostSet_screen_sizeArgs alignment mismatch");
    }
}

/// Arguments for Host.set_target_fps!
/// Roc signature: I32 => {}
pub const HostSet_target_fpsArgs = extern struct {
    arg0: i32,
};

/// Implement this struct with your hosted function implementations.
/// Pass it to hostedFunctions() to create the dispatch table.
pub const PlatformHostedFns = struct {
    draw_begin_frame: *const fn (*RocOps, *anyopaque, *anyopaque) callconv(.c) void, // Draw.begin_frame!
    draw_circle: *const fn (*RocOps, *anyopaque, *const DrawCircleArgs) callconv(.c) void, // Draw.circle!
    draw_circle_gradient: *const fn (*RocOps, *anyopaque, *const DrawCircle_gradientArgs) callconv(.c) void, // Draw.circle_gradient!
    draw_clear: *const fn (*RocOps, *anyopaque, *const DrawClearArgs) callconv(.c) void, // Draw.clear!
    draw_end_frame: *const fn (*RocOps, *anyopaque, *anyopaque) callconv(.c) void, // Draw.end_frame!
    draw_line: *const fn (*RocOps, *anyopaque, *const DrawLineArgs) callconv(.c) void, // Draw.line!
    draw_rectangle: *const fn (*RocOps, *anyopaque, *const DrawRectangleArgs) callconv(.c) void, // Draw.rectangle!
    draw_rectangle_gradient_h: *const fn (*RocOps, *anyopaque, *const DrawRectangle_gradient_hArgs) callconv(.c) void, // Draw.rectangle_gradient_h!
    draw_rectangle_gradient_v: *const fn (*RocOps, *anyopaque, *const DrawRectangle_gradient_vArgs) callconv(.c) void, // Draw.rectangle_gradient_v!
    draw_text: *const fn (*RocOps, *anyopaque, *const DrawTextArgs) callconv(.c) void, // Draw.text!
    host_exit: *const fn (*RocOps, *anyopaque, *const HostExitArgs) callconv(.c) void, // Host.exit!
    host_get_screen_size: *const fn (*RocOps, *HostGet_screen_sizeRetRecord, *anyopaque) callconv(.c) void, // Host.get_screen_size!
    host_read_env: *const fn (*RocOps, *Try(RocStr, void), *const HostRead_envArgs) callconv(.c) void, // Host.read_env!
    host_set_screen_size: *const fn (*RocOps, *Try(void, void), *const HostSet_screen_sizeArgs) callconv(.c) void, // Host.set_screen_size!
    host_set_target_fps: *const fn (*RocOps, *anyopaque, *const HostSet_target_fpsArgs) callconv(.c) void, // Host.set_target_fps!
};

/// Create a HostedFunctions dispatch table from your implementations.
/// The comptime parameter + nested struct ensures the function pointer array
/// lives in static memory, not on the stack.
pub fn hostedFunctions(comptime fns: PlatformHostedFns) HostedFunctions {
    const Static = struct {
        const ptrs = [_]HostedFn{
            hostedFn(fns.draw_begin_frame), // Draw.begin_frame! (index 0)
            hostedFn(fns.draw_circle), // Draw.circle! (index 1)
            hostedFn(fns.draw_circle_gradient), // Draw.circle_gradient! (index 2)
            hostedFn(fns.draw_clear), // Draw.clear! (index 3)
            hostedFn(fns.draw_end_frame), // Draw.end_frame! (index 4)
            hostedFn(fns.draw_line), // Draw.line! (index 5)
            hostedFn(fns.draw_rectangle), // Draw.rectangle! (index 6)
            hostedFn(fns.draw_rectangle_gradient_h), // Draw.rectangle_gradient_h! (index 7)
            hostedFn(fns.draw_rectangle_gradient_v), // Draw.rectangle_gradient_v! (index 8)
            hostedFn(fns.draw_text), // Draw.text! (index 9)
            hostedFn(fns.host_exit), // Host.exit! (index 10)
            hostedFn(fns.host_get_screen_size), // Host.get_screen_size! (index 11)
            hostedFn(fns.host_read_env), // Host.read_env! (index 12)
            hostedFn(fns.host_set_screen_size), // Host.set_screen_size! (index 13)
            hostedFn(fns.host_set_target_fps), // Host.set_target_fps! (index 14)
        };
    };
    return .{
        .count = Static.ptrs.len,
        .fns = @constCast(&Static.ptrs),
    };
}

/// Default memory management functions for Roc platforms.
///
/// Returns a struct with `rocAlloc`, `rocDealloc`, and `rocRealloc` functions
/// that follow the Roc ABI and use `EnvType.allocator()` for allocation.
///
/// Memory layout: each allocation prepends size metadata so that dealloc/realloc
/// can recover the original allocation size (required because `roc_dealloc` does
/// not receive a length parameter).
///
/// `EnvType` must have an `.allocator()` method that returns `std.mem.Allocator`.
pub fn DefaultAllocators(comptime EnvType: type) type {
    return struct {
        /// Allocate memory for the Roc runtime using the host environment's allocator.
        pub fn rocAlloc(alloc_args: *RocAlloc, env_ptr: *anyopaque) callconv(.c) void {
            const host_env: *EnvType = @ptrCast(@alignCast(env_ptr));
            const allocator = host_env.allocator();

            const min_alignment: usize = @max(alloc_args.alignment, @alignOf(usize));
            const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
            const size_storage_bytes = min_alignment;
            const total_size = alloc_args.length + size_storage_bytes;

            const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
                const stderr_file: std.fs.File = .stderr();
                stderr_file.writeAll("roc_alloc: out of memory\n") catch {};
                std.process.exit(1);
            };

            // Store total size immediately before the user data pointer
            const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
            size_ptr.* = total_size;

            alloc_args.answer = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
        }

        /// Free memory previously allocated by `rocAlloc`.
        pub fn rocDealloc(dealloc_args: *RocDealloc, env_ptr: *anyopaque) callconv(.c) void {
            const host_env: *EnvType = @ptrCast(@alignCast(env_ptr));
            const allocator = host_env.allocator();

            const min_alignment: usize = @max(dealloc_args.alignment, @alignOf(usize));
            const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
            const size_storage_bytes = min_alignment;

            const size_ptr: *const usize = @ptrFromInt(@intFromPtr(dealloc_args.ptr) - @sizeOf(usize));
            const total_size = size_ptr.*;

            const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(dealloc_args.ptr) - size_storage_bytes);
            const slice = base_ptr[0..total_size];
            allocator.rawFree(slice, align_enum, @returnAddress());
        }

        /// Reallocate memory, copying existing data to the new allocation.
        pub fn rocRealloc(realloc_args: *RocRealloc, env_ptr: *anyopaque) callconv(.c) void {
            const host_env: *EnvType = @ptrCast(@alignCast(env_ptr));
            const allocator = host_env.allocator();

            const min_alignment: usize = @max(realloc_args.alignment, @alignOf(usize));
            const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
            const size_storage_bytes = min_alignment;

            // Read old size from metadata
            const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(realloc_args.answer) - @sizeOf(usize));
            const old_total_size = old_size_ptr.*;
            const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(realloc_args.answer) - size_storage_bytes);

            // Allocate new block
            const new_total_size = realloc_args.new_length + size_storage_bytes;
            const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
                const stderr_file: std.fs.File = .stderr();
                stderr_file.writeAll("roc_realloc: out of memory\n") catch {};
                std.process.exit(1);
            };

            // Copy old user data to new location
            const old_user_data_size = old_total_size - size_storage_bytes;
            const copy_size = @min(old_user_data_size, realloc_args.new_length);
            const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
            const old_user_ptr: [*]const u8 = @ptrCast(realloc_args.answer);
            @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

            // Free old allocation
            allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

            // Store new size and return user pointer
            const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
            new_size_ptr.* = new_total_size;
            realloc_args.answer = new_user_ptr;
        }
    };
}

/// Default handlers for dbg, expect-failed, and crash.
///
/// These print to stderr and don't use the env pointer. Suitable for most
/// platform hosts that don't need custom handling of these events.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(dbg_args: *const RocDbg, _: *anyopaque) callconv(.c) void {
        const msg = dbg_args.utf8_bytes[0..dbg_args.len];
        const stderr_file: std.fs.File = .stderr();
        stderr_file.writeAll("\x1b[36m[ROC DBG]\x1b[0m ") catch {};
        stderr_file.writeAll(msg) catch {};
        stderr_file.writeAll("\n") catch {};
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(expect_args: *const RocExpectFailed, _: *anyopaque) callconv(.c) void {
        const msg = expect_args.utf8_bytes[0..expect_args.len];
        const stderr_file: std.fs.File = .stderr();
        stderr_file.writeAll("\x1b[33m[ROC EXPECT]\x1b[0m ") catch {};
        stderr_file.writeAll(msg) catch {};
        stderr_file.writeAll("\n") catch {};
    }

    /// Print a `crash` message to stderr and exit.
    pub fn rocCrashed(crash_args: *const RocCrashed, _: *anyopaque) callconv(.c) void {
        const msg = crash_args.utf8_bytes[0..crash_args.len];
        const stderr_file: std.fs.File = .stderr();
        stderr_file.writeAll("\x1b[31m[ROC CRASHED]\x1b[0m ") catch {};
        stderr_file.writeAll(msg) catch {};
        stderr_file.writeAll("\n") catch {};
        std.process.exit(1);
    }
};

/// Create a RocOps struct with default memory management and error handlers.
///
/// This is a convenience function that wires together `DefaultAllocators(EnvType)`,
/// `DefaultHandlers`, and the provided hosted functions into a ready-to-use `RocOps`.
///
/// `EnvType` must have an `.allocator()` method that returns `std.mem.Allocator`.
///
/// Example usage:
/// ```
/// var roc_ops = makeRocOps(HostEnv, &host_env, hostedFunctions(.{ ... }));
/// ```
pub fn makeRocOps(comptime EnvType: type, env: *EnvType, hosted_fns: HostedFunctions) RocOps {
    const Allocs = DefaultAllocators(EnvType);
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &Allocs.rocAlloc,
        .roc_dealloc = &Allocs.rocDealloc,
        .roc_realloc = &Allocs.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
        .hosted_fns = hosted_fns,
    };
}

// Entrypoint Declarations
//
// Extern declarations for Roc entrypoints. Call these from your platform host
// to invoke Roc application functions.

/// Arguments for entrypoint: render_for_host!
pub const Render_for_hostArgs = extern struct {
    arg0: *anyopaque,
    arg1: __AnonStruct137,
};

/// Entrypoint: init_for_host!
pub extern fn roc__init_for_host(ops: *RocOps, ret_ptr: *Try(*anyopaque, i64), arg_ptr: ?*const __AnonStruct123) callconv(.c) void;

/// Entrypoint: render_for_host!
pub extern fn roc__render_for_host(ops: *RocOps, ret_ptr: *Try(*anyopaque, i64), arg_ptr: ?*const Render_for_hostArgs) callconv(.c) void;

