//! Roc Platform ABI
//!
//! This file defines the Zig interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Usage:
//! 1. Import this file in your platform host
//! 2. Implement each hosted function according to its signature
//! 3. Call hostedFunctions() to create the dispatch table for RocOps

const std = @import("std");
const builtin = @import("builtin");

/// Type-erased pointer to a hosted function. Each hosted function has its own natural
/// C signature (determined by its Roc argument and return types under the platform C
/// ABI), so they are stored type-erased here and cast to their concrete signature at the
/// Roc call site. A hosted function takes a leading `*RocOps` only when it allocates or
/// frees Roc-managed memory (i.e. when an argument or its return is a heap type).
///
/// Roc transfers ownership of refcounted arguments to hosted functions. Hosted functions
/// must decref owned refcounted arguments when done, or transfer that ownership into the
/// return value or longer-lived storage. If the host keeps both the call argument and a
/// stored copy, it must incref the stored copy so each live reference has one ownership.
pub const HostedFn = *const anyopaque;

/// Table of hosted function pointers passed to the Roc runtime.
pub const HostedFunctions = extern struct {
    count: u32,
    fns: [*]HostedFn,
};

/// The operations table passed from the host to the Roc runtime. The memory and
/// diagnostic callbacks take a leading `*RocOps` and pass their remaining arguments and
/// return value in registers per the platform C ABI. `roc_alloc`/`roc_realloc` return the
/// allocation (or null on OOM — a platform host aborts instead of returning null).
pub const RocOps = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocOps, usize, usize) callconv(.c) ?*anyopaque,
    roc_dealloc: *const fn (*RocOps, *anyopaque, usize) callconv(.c) void,
    roc_realloc: *const fn (*RocOps, *anyopaque, usize, usize) callconv(.c) ?*anyopaque,
    roc_dbg: *const fn (*RocOps, [*]const u8, usize) callconv(.c) void,
    roc_expect_failed: *const fn (*RocOps, [*]const u8, usize) callconv(.c) void,
    roc_crashed: *const fn (*RocOps, [*]const u8, usize) callconv(.c) void,
    hosted_fns: HostedFunctions,
};

/// Uniform ABI function pointer stored in `RocErasedCallablePayload`.
pub const RocErasedCallableFn = *const fn (*RocOps, ?[*]u8, ?[*]const u8, ?[*]u8) callconv(.c) void;

/// Final-drop callback for inline erased-callable captures.
pub const RocErasedCallableOnDrop = *const fn (?[*]u8, *RocOps) callconv(.c) void;

/// Payload header for `Box(function)`.
pub const RocErasedCallablePayload = extern struct {
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
};

/// Runtime representation of `Box(function)`.
pub const RocErasedCallable = ?[*]u8;

pub const roc_erased_callable_capture_alignment: usize = 16;
pub const roc_erased_callable_payload_alignment: usize = 16;
pub const roc_erased_callable_capture_offset: usize = std.mem.alignForward(usize, @sizeOf(RocErasedCallablePayload), roc_erased_callable_capture_alignment);

pub fn rocErasedCallablePayloadSize(capture_size: usize) usize {
    return roc_erased_callable_capture_offset + capture_size;
}

pub fn rocErasedCallablePayloadPtr(callable: RocErasedCallable) *RocErasedCallablePayload {
    return @ptrCast(@alignCast(callable orelse unreachable));
}

pub fn rocErasedCallableCapturePtr(callable: RocErasedCallable) ?[*]u8 {
    const data = callable orelse return null;
    return data + roc_erased_callable_capture_offset;
}

pub fn rocErasedCallableAllocate(
    roc_ops: *RocOps,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
    capture_size: usize,
) RocErasedCallable {
    const ptr_width = @sizeOf(usize);
    const alignment = @max(ptr_width, roc_erased_callable_payload_alignment);
    const extra_bytes = @max(ptr_width, roc_erased_callable_payload_alignment);
    const length = extra_bytes + rocErasedCallablePayloadSize(capture_size);
    const base: [*]u8 = @ptrCast(roc_ops.roc_alloc(roc_ops, length, alignment));
    const data = base + extra_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    const payload: *RocErasedCallablePayload = @ptrCast(@alignCast(data));
    payload.* = .{ .callable_fn_ptr = callable_fn_ptr, .on_drop = on_drop };
    return data;
}

/// Type-erase a concrete hosted function pointer to `HostedFn` for storage in the vtable.
/// Hosted functions are written with their natural C signatures (e.g.
/// `fn(ops: *RocOps, x: i32) Plant` or `fn(s: RocStr) void`); this stores the pointer
/// type-erased, and the Roc call site casts it back to the concrete signature.
pub fn hostedFn(func: anytype) HostedFn {
    return @ptrCast(func);
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decrefBoxWith` and `freeBoxWith` free it after the callback.
pub const RocBoxPayloadDecref = *const fn (?*anyopaque, *RocOps) callconv(.c) void;

/// Increment the refcount of a boxed payload data pointer.
pub fn increfBox(data_ptr: ?*anyopaque, amount: isize) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
    _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decrefBox(data_ptr: ?*anyopaque, roc_ops: *RocOps) void {
    decrefBoxWith(data_ptr, @alignOf(usize), null, roc_ops);
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
pub fn decrefBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_ops: *RocOps,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA

    const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
    if (prev == 1) {
        if (payload_decref) |callback| callback(data_ptr, roc_ops);
        freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_ops);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
pub fn freeBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_ops: *RocOps,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    if (payload_decref) |callback| callback(data_ptr, roc_ops);
    freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_ops);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn isUniqueBox(data_ptr: ?*anyopaque) bool {
    const data = boxDataPtr(data_ptr) orelse return true;
    const rc = boxRefcountPtr(data);
    return rc.* == 1;
}

fn boxDataPtr(data_ptr: ?*anyopaque) ?[*]u8 {
    const ptr = data_ptr orelse return null;
    return @ptrCast(ptr);
}

fn boxRefcountPtr(data: [*]u8) *isize {
    return @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
}

fn freeBoxAllocation(
    data: [*]u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_ops: *RocOps,
) void {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: *anyopaque = @ptrFromInt(@intFromPtr(data) - header_bytes);
    roc_ops.roc_dealloc(roc_ops, base, alloc_alignment);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `std.math.maxInt(isize)` bytes: about 2 GiB on 32-bit targets
/// and 8 EiB on 64-bit targets.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    capacity_or_alloc_ptr: usize,
    length: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const small_str_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));
    const seamless_slice_tag: usize = 1;

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and (self.capacity_or_alloc_ptr & seamless_slice_tag) != 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .capacity_or_alloc_ptr = 0, .length = small_str_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_ops` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_ops: *RocOps) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            const base: [*]u8 = @ptrCast(roc_ops.roc_alloc(roc_ops, total, @alignOf(usize)));
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .capacity_or_alloc_ptr = slice.len << 1,
                .length = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_ops: *RocOps) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            roc_ops.roc_dealloc(roc_ops, base, @alignOf(usize));
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~seamless_slice_tag));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return true if this list is a seamless slice into another allocation.
        /// Slices share the rc slot with their backing allocation; the alloc ptr is
        /// encoded in `capacity_or_alloc_ptr` with the low bit set.
        pub fn isSeamlessSlice(self: Self) bool {
            return (self.capacity_or_alloc_ptr & 1) != 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Resolve `self` to the start of its backing allocation (the element block
        /// just after the rc slot). Returns `null` for empty lists. Handles both
        /// whole-backing and seamless-slice forms.
        fn getAllocationPtr(self: Self) ?[*]u8 {
            if (self.isSeamlessSlice()) {
                return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~@as(usize, 1)));
            }
            const ptr = self.elements_ptr orelse return null;
            return @ptrCast(ptr);
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_ops: *RocOps) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            const base: [*]u8 = @ptrCast(roc_ops.roc_alloc(roc_ops, total, alloc_align));
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length << 1,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_ops: *RocOps) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_ops);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Decrement the reference count; frees the allocation when it reaches zero.
        pub fn decref(self: Self, roc_ops: *RocOps) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_ops.roc_dealloc(roc_ops, base, alloc_align);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
            return rc.* == 1;
        }
    };
}

/// Minimal I/O abstraction for Roc platform hosts.
///
/// Provides stderr output and fatal-error handling that can be routed
/// to different backends (POSIX, freestanding/WASM, custom).
///
/// Use `RocIo.default()` for most platforms; inject a custom vtable for
/// environments without POSIX stdio (e.g. WASM freestanding).
pub const RocIo = struct {
    ctx: ?*anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Write to stderr. Best-effort: errors are silently ignored.
        writeStderr: *const fn (?*anyopaque, []const u8) void,
        /// Terminate the process or trap. Must not return.
        onFatal: *const fn (?*anyopaque) noreturn,
    };

    /// Write `data` to stderr (best-effort).
    pub fn writeStderr(self: RocIo, data: []const u8) void {
        self.vtable.writeStderr(self.ctx, data);
    }

    /// Terminate the process or trap. Does not return.
    pub fn onFatal(self: RocIo) noreturn {
        self.vtable.onFatal(self.ctx);
    }

    /// Native (POSIX) implementation: writes to stderr, exits with code 1.
    pub fn native() RocIo {
        return .{ .ctx = null, .vtable = &native_vtable };
    }

    /// Freestanding implementation: no-op stderr, @trap() on fatal.
    pub fn freestanding() RocIo {
        return .{ .ctx = null, .vtable = &freestanding_vtable };
    }

    /// Select the appropriate implementation for the current build target.
    pub fn default() RocIo {
        if (comptime builtin.os.tag == .freestanding) {
            return freestanding();
        }
        return native();
    }

    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        std.fs.File.stderr().writeAll(data) catch {};
    }

    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        std.process.exit(1);
    }

    fn freestandingWriteStderr(_: ?*anyopaque, _: []const u8) void {}

    fn freestandingOnFatal(_: ?*anyopaque) noreturn {
        @trap();
    }

    const native_vtable: VTable = .{
        .writeStderr = &nativeWriteStderr,
        .onFatal = &nativeOnFatal,
    };

    const freestanding_vtable: VTable = .{
        .writeStderr = &freestandingWriteStderr,
        .onFatal = &freestandingOnFatal,
    };
};

/// Host environment passed to the Roc runtime.
///
/// Bundles the allocator and I/O backend used by DefaultAllocators
/// and DefaultHandlers.
pub const RocEnv = struct {
    allocator: std.mem.Allocator,
    roc_io: RocIo,
};

/// Element type for __AnonStruct0
pub const __AnonStruct0 = extern struct {
    @"handle": u64,
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct0) != 16) @compileError("__AnonStruct0 size mismatch");
        if (@alignOf(__AnonStruct0) != 8) @compileError("__AnonStruct0 alignment mismatch");
    }
}

/// Element type for __AnonStruct5
pub const __AnonStruct5 = extern struct {
    @"freq": f32,
    @"ms": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct5) != 8) @compileError("__AnonStruct5 size mismatch");
        if (@alignOf(__AnonStruct5) != 4) @compileError("__AnonStruct5 alignment mismatch");
    }
}

/// Element type for __AnonStruct10
pub const __AnonStruct10 = extern struct {
    @"center": __AnonStruct11,
    @"radius": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct10) != 16) @compileError("__AnonStruct10 size mismatch");
        if (@alignOf(__AnonStruct10) != 4) @compileError("__AnonStruct10 alignment mismatch");
    }
}

/// Element type for __AnonStruct11
pub const __AnonStruct11 = extern struct {
    @"x": f32,
    @"y": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct11) != 8) @compileError("__AnonStruct11 size mismatch");
        if (@alignOf(__AnonStruct11) != 4) @compileError("__AnonStruct11 alignment mismatch");
    }
}

/// Element type for Color
pub const Color = extern struct {
    @"a": u8,
    @"b": u8,
    @"g": u8,
    @"r": u8,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Color) != 4) @compileError("Color size mismatch");
        if (@alignOf(Color) != 1) @compileError("Color alignment mismatch");
    }
}

/// Element type for __AnonStruct15
pub const __AnonStruct15 = extern struct {
    @"center": __AnonStruct11,
    @"radius": f32,
    @"color_inner": Color,
    @"color_outer": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct15) != 20) @compileError("__AnonStruct15 size mismatch");
        if (@alignOf(__AnonStruct15) != 4) @compileError("__AnonStruct15 alignment mismatch");
    }
}

/// Element type for __AnonStruct16
pub const __AnonStruct16 = extern struct {
    @"center": __AnonStruct11,
    @"radius": f32,
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct16) != 20) @compileError("__AnonStruct16 size mismatch");
        if (@alignOf(__AnonStruct16) != 4) @compileError("__AnonStruct16 alignment mismatch");
    }
}

/// Element type for __AnonStruct17
pub const __AnonStruct17 = extern struct {
    @"pos": __AnonStruct11,
    @"size": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct17) != 16) @compileError("__AnonStruct17 size mismatch");
        if (@alignOf(__AnonStruct17) != 4) @compileError("__AnonStruct17 alignment mismatch");
    }
}

/// Element type for __AnonStruct18
pub const __AnonStruct18 = extern struct {
    @"end": __AnonStruct11,
    @"start": __AnonStruct11,
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct18) != 24) @compileError("__AnonStruct18 size mismatch");
        if (@alignOf(__AnonStruct18) != 4) @compileError("__AnonStruct18 alignment mismatch");
    }
}

/// Element type for __AnonStruct20
pub const __AnonStruct20 = extern struct {
    @"path": RocStr,
    @"size": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct20) != 32) @compileError("__AnonStruct20 size mismatch");
        if (@alignOf(__AnonStruct20) != 8) @compileError("__AnonStruct20 alignment mismatch");
    }
}

/// Element type for __AnonStruct23
pub const __AnonStruct23 = extern struct {
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct23) != 8) @compileError("__AnonStruct23 size mismatch");
        if (@alignOf(__AnonStruct23) != 4) @compileError("__AnonStruct23 alignment mismatch");
    }
}

/// Element type for __AnonStruct24
pub const __AnonStruct24 = extern struct {
    @"font": u64,
    @"text": RocStr,
    @"size": f32,
    @"spacing": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct24) != 40) @compileError("__AnonStruct24 size mismatch");
        if (@alignOf(__AnonStruct24) != 8) @compileError("__AnonStruct24 alignment mismatch");
    }
}

/// Element type for __AnonStruct25
pub const __AnonStruct25 = extern struct {
    @"points": RocListWith(__AnonStruct11, false),
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct25) != 32) @compileError("__AnonStruct25 size mismatch");
        if (@alignOf(__AnonStruct25) != 8) @compileError("__AnonStruct25 alignment mismatch");
    }
}

/// Element type for __AnonStruct27
pub const __AnonStruct27 = extern struct {
    @"points": RocListWith(__AnonStruct11, false),
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct27) != 32) @compileError("__AnonStruct27 size mismatch");
        if (@alignOf(__AnonStruct27) != 8) @compileError("__AnonStruct27 alignment mismatch");
    }
}

/// Element type for __AnonStruct28
pub const __AnonStruct28 = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct28) != 20) @compileError("__AnonStruct28 size mismatch");
        if (@alignOf(__AnonStruct28) != 4) @compileError("__AnonStruct28 alignment mismatch");
    }
}

/// Element type for __AnonStruct29
pub const __AnonStruct29 = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color_left": Color,
    @"color_right": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct29) != 24) @compileError("__AnonStruct29 size mismatch");
        if (@alignOf(__AnonStruct29) != 4) @compileError("__AnonStruct29 alignment mismatch");
    }
}

/// Element type for __AnonStruct30
pub const __AnonStruct30 = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color_bottom": Color,
    @"color_top": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct30) != 24) @compileError("__AnonStruct30 size mismatch");
        if (@alignOf(__AnonStruct30) != 4) @compileError("__AnonStruct30 alignment mismatch");
    }
}

/// Element type for __AnonStruct31
pub const __AnonStruct31 = extern struct {
    @"height": f32,
    @"thickness": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct31) != 24) @compileError("__AnonStruct31 size mismatch");
        if (@alignOf(__AnonStruct31) != 4) @compileError("__AnonStruct31 alignment mismatch");
    }
}

/// Element type for __AnonStruct32
pub const __AnonStruct32 = extern struct {
    @"height": f32,
    @"radius": f32,
    @"segments": i32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct32) != 28) @compileError("__AnonStruct32 size mismatch");
        if (@alignOf(__AnonStruct32) != 4) @compileError("__AnonStruct32 alignment mismatch");
    }
}

/// Element type for __AnonStruct33
pub const __AnonStruct33 = extern struct {
    @"height": f32,
    @"radius": f32,
    @"segments": i32,
    @"thickness": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct33) != 32) @compileError("__AnonStruct33 size mismatch");
        if (@alignOf(__AnonStruct33) != 4) @compileError("__AnonStruct33 alignment mismatch");
    }
}

/// Element type for __AnonStruct34
pub const __AnonStruct34 = extern struct {
    @"font": u64,
    @"text": RocStr,
    @"pos": __AnonStruct11,
    @"size": f32,
    @"spacing": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct34) != 56) @compileError("__AnonStruct34 size mismatch");
        if (@alignOf(__AnonStruct34) != 8) @compileError("__AnonStruct34 alignment mismatch");
    }
}

/// Element type for __AnonStruct35
pub const __AnonStruct35 = extern struct {
    @"texture": u64,
    @"dest": __AnonStruct36,
    @"origin": __AnonStruct37,
    @"rotation": f32,
    @"source": __AnonStruct36,
    @"tint": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct35) != 56) @compileError("__AnonStruct35 size mismatch");
        if (@alignOf(__AnonStruct35) != 8) @compileError("__AnonStruct35 alignment mismatch");
    }
}

/// Element type for __AnonStruct36
pub const __AnonStruct36 = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct36) != 16) @compileError("__AnonStruct36 size mismatch");
        if (@alignOf(__AnonStruct36) != 4) @compileError("__AnonStruct36 alignment mismatch");
    }
}

/// Element type for __AnonStruct37
pub const __AnonStruct37 = extern struct {
    @"x": f32,
    @"y": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct37) != 8) @compileError("__AnonStruct37 size mismatch");
        if (@alignOf(__AnonStruct37) != 4) @compileError("__AnonStruct37 alignment mismatch");
    }
}

/// Element type for __AnonStruct38
pub const __AnonStruct38 = extern struct {
    @"a": __AnonStruct11,
    @"b": __AnonStruct11,
    @"c": __AnonStruct11,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct38) != 28) @compileError("__AnonStruct38 size mismatch");
        if (@alignOf(__AnonStruct38) != 4) @compileError("__AnonStruct38 alignment mismatch");
    }
}

/// Element type for __AnonStruct39
pub const __AnonStruct39 = extern struct {
    @"a": __AnonStruct11,
    @"b": __AnonStruct11,
    @"c": __AnonStruct11,
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct39) != 32) @compileError("__AnonStruct39 size mismatch");
        if (@alignOf(__AnonStruct39) != 4) @compileError("__AnonStruct39 alignment mismatch");
    }
}

/// Element type for __AnonStruct42
pub const __AnonStruct42 = extern struct {
    @"height": i32,
    @"width": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct42) != 8) @compileError("__AnonStruct42 size mismatch");
        if (@alignOf(__AnonStruct42) != 4) @compileError("__AnonStruct42 alignment mismatch");
    }
}

/// Element type for Host
pub const Host = extern struct {
    @"frame_count": u64,
    @"keys": RocListWith(u8, false),
    @"keys_pressed": RocListWith(u8, false),
    @"keys_released": RocListWith(u8, false),
    @"mouse": __AnonStruct51,
    @"timestamp_nanos": u64,
    @"frame_time": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Host) != 184) @compileError("Host size mismatch");
        if (@alignOf(Host) != 8) @compileError("Host alignment mismatch");
    }
}

/// Element type for __AnonStruct51
pub const __AnonStruct51 = extern struct {
    @"buttons": RocListWith(u8, false),
    @"buttons_pressed": RocListWith(u8, false),
    @"buttons_released": RocListWith(u8, false),
    @"wheel": f32,
    @"x": f32,
    @"y": f32,
    @"left": bool,
    @"middle": bool,
    @"right": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct51) != 88) @compileError("__AnonStruct51 size mismatch");
        if (@alignOf(__AnonStruct51) != 8) @compileError("__AnonStruct51 alignment mismatch");
    }
}

/// Element type for __AnonStruct55
pub const __AnonStruct55 = extern struct {
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct55) != 8) @compileError("__AnonStruct55 size mismatch");
        if (@alignOf(__AnonStruct55) != 4) @compileError("__AnonStruct55 alignment mismatch");
    }
}

/// Element type for __AnonStruct56
pub const __AnonStruct56 = extern struct {
    @"init!": __AnonStruct69,
    @"render!": *anyopaque,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct56) != 56) @compileError("__AnonStruct56 size mismatch");
        if (@alignOf(__AnonStruct56) != 8) @compileError("__AnonStruct56 alignment mismatch");
    }
}

/// Element type for __AnonStruct64
pub const __AnonStruct64 = extern struct {
    @"buttons": RocListWith(u8, false),
    @"buttons_pressed": RocListWith(u8, false),
    @"buttons_released": RocListWith(u8, false),
    @"wheel": f32,
    @"x": f32,
    @"y": f32,
    @"left": bool,
    @"middle": bool,
    @"right": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct64) != 88) @compileError("__AnonStruct64 size mismatch");
        if (@alignOf(__AnonStruct64) != 8) @compileError("__AnonStruct64 alignment mismatch");
    }
}

/// Element type for __AnonStruct69
pub const __AnonStruct69 = extern struct {
    @"config": __AnonStruct73,
    @"run!": *anyopaque,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct69) != 48) @compileError("__AnonStruct69 size mismatch");
        if (@alignOf(__AnonStruct69) != 8) @compileError("__AnonStruct69 alignment mismatch");
    }
}

/// Element type for __AnonStruct73
pub const __AnonStruct73 = extern struct {
    @"title": RocStr,
    @"height": i32,
    @"target_fps": i32,
    @"width": i32,
    @"cursor_visible": bool,
    @"fullscreen": bool,
    @"resizable": bool,
    @"vsync": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct73) != 40) @compileError("__AnonStruct73 size mismatch");
        if (@alignOf(__AnonStruct73) != 8) @compileError("__AnonStruct73 alignment mismatch");
    }
}

/// Element type for __AnonStruct77
pub const __AnonStruct77 = extern struct {
    @"title": RocStr,
    @"height": i32,
    @"target_fps": i32,
    @"width": i32,
    @"cursor_visible": bool,
    @"fullscreen": bool,
    @"resizable": bool,
    @"vsync": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct77) != 40) @compileError("__AnonStruct77 size mismatch");
        if (@alignOf(__AnonStruct77) != 8) @compileError("__AnonStruct77 alignment mismatch");
    }
}

/// Element type for __AnonStruct79
pub const __AnonStruct79 = extern struct {
    @"frame_count": u64,
    @"keys": RocListWith(u8, false),
    @"keys_pressed": RocListWith(u8, false),
    @"keys_released": RocListWith(u8, false),
    @"mouse_buttons": RocListWith(u8, false),
    @"mouse_buttons_pressed": RocListWith(u8, false),
    @"mouse_buttons_released": RocListWith(u8, false),
    @"timestamp_nanos": u64,
    @"frame_time": f32,
    @"mouse_wheel": f32,
    @"mouse_x": f32,
    @"mouse_y": f32,
    @"mouse_left": bool,
    @"mouse_middle": bool,
    @"mouse_right": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct79) != 184) @compileError("__AnonStruct79 size mismatch");
        if (@alignOf(__AnonStruct79) != 8) @compileError("__AnonStruct79 alignment mismatch");
    }
}

/// Tag discriminant for Try.
pub const TryTag = enum(u8) {
    Err = 0,
    Ok = 1,
};

/// Tag union: Try
pub const Try = extern struct {
    payload: extern union {
        err: *anyopaque,
        ok: RocStr,
    },
    tag: TryTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Try) != 32) @compileError("Try size mismatch");
        if (@alignOf(Try) != 8) @compileError("Try alignment mismatch");
    }
}

/// Return type record for Assets.load_texture_raw!
/// Fields ordered by alignment descending (Roc ABI)
pub const AssetsLoad_texture_rawRetRecord = extern struct {
    @"handle": u64,
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(AssetsLoad_texture_rawRetRecord) != 16) @compileError("AssetsLoad_texture_rawRetRecord size mismatch");
        if (@alignOf(AssetsLoad_texture_rawRetRecord) != 8) @compileError("AssetsLoad_texture_rawRetRecord alignment mismatch");
    }
}

/// Return type record for Draw.measure_text_raw!
/// Fields ordered by alignment descending (Roc ABI)
pub const DrawMeasure_text_rawRetRecord = extern struct {
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawMeasure_text_rawRetRecord) != 8) @compileError("DrawMeasure_text_rawRetRecord size mismatch");
        if (@alignOf(DrawMeasure_text_rawRetRecord) != 4) @compileError("DrawMeasure_text_rawRetRecord alignment mismatch");
    }
}

/// Return type record for Host.get_screen_size!
/// Fields ordered by alignment descending (Roc ABI)
pub const HostGet_screen_sizeRetRecord = extern struct {
    @"height": i32,
    @"width": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostGet_screen_sizeRetRecord) != 8) @compileError("HostGet_screen_sizeRetRecord size mismatch");
        if (@alignOf(HostGet_screen_sizeRetRecord) != 4) @compileError("HostGet_screen_sizeRetRecord alignment mismatch");
    }
}

/// Arguments for Assets.load_texture_raw!
/// Roc signature: Str => { handle : U64, height : F32, width : F32 }
/// Refcounted fields are owned by the hosted function.
pub const AssetsLoad_texture_rawArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Audio.gen_tone_raw!
/// Roc signature: { freq : F32, ms : I32 } => U64
/// Refcounted fields are owned by the hosted function.
pub const AudioGen_tone_rawArgs = extern struct {
    @"freq": f32,
    @"ms": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(AudioGen_tone_rawArgs) != 8) @compileError("AudioGen_tone_rawArgs size mismatch");
        if (@alignOf(AudioGen_tone_rawArgs) != 4) @compileError("AudioGen_tone_rawArgs alignment mismatch");
    }
}

/// Arguments for Audio.play_raw!
/// Roc signature: U64 => {}
/// Refcounted fields are owned by the hosted function.
pub const AudioPlay_rawArgs = extern struct {
    arg0: u64,
};

/// Arguments for Draw.circle_gradient!
/// Roc signature: { center : { x : F32, y : F32 }, color_inner : Color, color_outer : Color, radius : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawCircle_gradientArgs = extern struct {
    @"center": __AnonStruct11,
    @"radius": f32,
    @"color_inner": Color,
    @"color_outer": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawCircle_gradientArgs) != 20) @compileError("DrawCircle_gradientArgs size mismatch");
        if (@alignOf(DrawCircle_gradientArgs) != 4) @compileError("DrawCircle_gradientArgs alignment mismatch");
    }
}

/// Arguments for Draw.circle_lines_raw!
/// Roc signature: { center : { x : F32, y : F32 }, color : Color, radius : F32, thickness : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawCircle_lines_rawArgs = extern struct {
    @"center": __AnonStruct11,
    @"radius": f32,
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawCircle_lines_rawArgs) != 20) @compileError("DrawCircle_lines_rawArgs size mismatch");
        if (@alignOf(DrawCircle_lines_rawArgs) != 4) @compileError("DrawCircle_lines_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.circle_raw!
/// Roc signature: { center : { x : F32, y : F32 }, color : Color, radius : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawCircle_rawArgs = extern struct {
    @"center": __AnonStruct11,
    @"radius": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawCircle_rawArgs) != 16) @compileError("DrawCircle_rawArgs size mismatch");
        if (@alignOf(DrawCircle_rawArgs) != 4) @compileError("DrawCircle_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.clear!
/// Roc signature: Color => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawClearArgs = extern struct {
    @"a": u8,
    @"b": u8,
    @"g": u8,
    @"r": u8,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawClearArgs) != 4) @compileError("DrawClearArgs size mismatch");
        if (@alignOf(DrawClearArgs) != 1) @compileError("DrawClearArgs alignment mismatch");
    }
}

/// Arguments for Draw.draw_texture_raw!
/// Roc signature: { dest : { height : F32, width : F32, x : F32, y : F32 }, origin : { x : F32, y : F32 }, rotation : F32, source : { height : F32, width : F32, x : F32, y : F32 }, texture : U64, tint : Color } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawDraw_texture_rawArgs = extern struct {
    @"texture": u64,
    @"dest": __AnonStruct36,
    @"origin": __AnonStruct37,
    @"rotation": f32,
    @"source": __AnonStruct36,
    @"tint": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawDraw_texture_rawArgs) != 56) @compileError("DrawDraw_texture_rawArgs size mismatch");
        if (@alignOf(DrawDraw_texture_rawArgs) != 8) @compileError("DrawDraw_texture_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.fps!
/// Roc signature: { color : Color, pos : { x : F32, y : F32 }, size : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawFpsArgs = extern struct {
    @"pos": __AnonStruct11,
    @"size": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawFpsArgs) != 16) @compileError("DrawFpsArgs size mismatch");
        if (@alignOf(DrawFpsArgs) != 4) @compileError("DrawFpsArgs alignment mismatch");
    }
}

/// Arguments for Draw.line_raw!
/// Roc signature: { color : Color, end : { x : F32, y : F32 }, start : { x : F32, y : F32 }, thickness : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawLine_rawArgs = extern struct {
    @"end": __AnonStruct11,
    @"start": __AnonStruct11,
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawLine_rawArgs) != 24) @compileError("DrawLine_rawArgs size mismatch");
        if (@alignOf(DrawLine_rawArgs) != 4) @compileError("DrawLine_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.load_font_raw!
/// Roc signature: { path : Str, size : I32 } => U64
/// Refcounted fields are owned by the hosted function.
pub const DrawLoad_font_rawArgs = extern struct {
    @"path": RocStr,
    @"size": i32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawLoad_font_rawArgs) != 32) @compileError("DrawLoad_font_rawArgs size mismatch");
        if (@alignOf(DrawLoad_font_rawArgs) != 8) @compileError("DrawLoad_font_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.measure_text_raw!
/// Roc signature: { font : U64, size : F32, spacing : F32, text : Str } => { height : F32, width : F32 }
/// Refcounted fields are owned by the hosted function.
pub const DrawMeasure_text_rawArgs = extern struct {
    @"font": u64,
    @"text": RocStr,
    @"size": f32,
    @"spacing": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawMeasure_text_rawArgs) != 40) @compileError("DrawMeasure_text_rawArgs size mismatch");
        if (@alignOf(DrawMeasure_text_rawArgs) != 8) @compileError("DrawMeasure_text_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.polygon_lines_raw!
/// Roc signature: { color : Color, points : List({ x : F32, y : F32 }), thickness : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawPolygon_lines_rawArgs = extern struct {
    @"points": RocListWith(__AnonStruct11, false),
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawPolygon_lines_rawArgs) != 32) @compileError("DrawPolygon_lines_rawArgs size mismatch");
        if (@alignOf(DrawPolygon_lines_rawArgs) != 8) @compileError("DrawPolygon_lines_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.polygon_raw!
/// Roc signature: { color : Color, points : List({ x : F32, y : F32 }) } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawPolygon_rawArgs = extern struct {
    @"points": RocListWith(__AnonStruct11, false),
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawPolygon_rawArgs) != 32) @compileError("DrawPolygon_rawArgs size mismatch");
        if (@alignOf(DrawPolygon_rawArgs) != 8) @compileError("DrawPolygon_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.rectangle_gradient_h!
/// Roc signature: { color_left : Color, color_right : Color, height : F32, width : F32, x : F32, y : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawRectangle_gradient_hArgs = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color_left": Color,
    @"color_right": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawRectangle_gradient_hArgs) != 24) @compileError("DrawRectangle_gradient_hArgs size mismatch");
        if (@alignOf(DrawRectangle_gradient_hArgs) != 4) @compileError("DrawRectangle_gradient_hArgs alignment mismatch");
    }
}

/// Arguments for Draw.rectangle_gradient_v!
/// Roc signature: { color_bottom : Color, color_top : Color, height : F32, width : F32, x : F32, y : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawRectangle_gradient_vArgs = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color_bottom": Color,
    @"color_top": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawRectangle_gradient_vArgs) != 24) @compileError("DrawRectangle_gradient_vArgs size mismatch");
        if (@alignOf(DrawRectangle_gradient_vArgs) != 4) @compileError("DrawRectangle_gradient_vArgs alignment mismatch");
    }
}

/// Arguments for Draw.rectangle_lines_raw!
/// Roc signature: { color : Color, height : F32, thickness : F32, width : F32, x : F32, y : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawRectangle_lines_rawArgs = extern struct {
    @"height": f32,
    @"thickness": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawRectangle_lines_rawArgs) != 24) @compileError("DrawRectangle_lines_rawArgs size mismatch");
        if (@alignOf(DrawRectangle_lines_rawArgs) != 4) @compileError("DrawRectangle_lines_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.rectangle_raw!
/// Roc signature: { color : Color, height : F32, width : F32, x : F32, y : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawRectangle_rawArgs = extern struct {
    @"height": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawRectangle_rawArgs) != 20) @compileError("DrawRectangle_rawArgs size mismatch");
        if (@alignOf(DrawRectangle_rawArgs) != 4) @compileError("DrawRectangle_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.rounded_rectangle_lines_raw!
/// Roc signature: { color : Color, height : F32, radius : F32, segments : I32, thickness : F32, width : F32, x : F32, y : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawRounded_rectangle_lines_rawArgs = extern struct {
    @"height": f32,
    @"radius": f32,
    @"segments": i32,
    @"thickness": f32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawRounded_rectangle_lines_rawArgs) != 32) @compileError("DrawRounded_rectangle_lines_rawArgs size mismatch");
        if (@alignOf(DrawRounded_rectangle_lines_rawArgs) != 4) @compileError("DrawRounded_rectangle_lines_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.rounded_rectangle_raw!
/// Roc signature: { color : Color, height : F32, radius : F32, segments : I32, width : F32, x : F32, y : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawRounded_rectangle_rawArgs = extern struct {
    @"height": f32,
    @"radius": f32,
    @"segments": i32,
    @"width": f32,
    @"x": f32,
    @"y": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawRounded_rectangle_rawArgs) != 28) @compileError("DrawRounded_rectangle_rawArgs size mismatch");
        if (@alignOf(DrawRounded_rectangle_rawArgs) != 4) @compileError("DrawRounded_rectangle_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.text_raw!
/// Roc signature: { color : Color, font : U64, pos : { x : F32, y : F32 }, size : F32, spacing : F32, text : Str } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawText_rawArgs = extern struct {
    @"font": u64,
    @"text": RocStr,
    @"pos": __AnonStruct11,
    @"size": f32,
    @"spacing": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawText_rawArgs) != 56) @compileError("DrawText_rawArgs size mismatch");
        if (@alignOf(DrawText_rawArgs) != 8) @compileError("DrawText_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.triangle_lines_raw!
/// Roc signature: { a : { x : F32, y : F32 }, b : { x : F32, y : F32 }, c : { x : F32, y : F32 }, color : Color, thickness : F32 } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawTriangle_lines_rawArgs = extern struct {
    @"a": __AnonStruct11,
    @"b": __AnonStruct11,
    @"c": __AnonStruct11,
    @"thickness": f32,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawTriangle_lines_rawArgs) != 32) @compileError("DrawTriangle_lines_rawArgs size mismatch");
        if (@alignOf(DrawTriangle_lines_rawArgs) != 4) @compileError("DrawTriangle_lines_rawArgs alignment mismatch");
    }
}

/// Arguments for Draw.triangle_raw!
/// Roc signature: { a : { x : F32, y : F32 }, b : { x : F32, y : F32 }, c : { x : F32, y : F32 }, color : Color } => {}
/// Refcounted fields are owned by the hosted function.
pub const DrawTriangle_rawArgs = extern struct {
    @"a": __AnonStruct11,
    @"b": __AnonStruct11,
    @"c": __AnonStruct11,
    @"color": Color,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(DrawTriangle_rawArgs) != 28) @compileError("DrawTriangle_rawArgs size mismatch");
        if (@alignOf(DrawTriangle_rawArgs) != 4) @compileError("DrawTriangle_rawArgs alignment mismatch");
    }
}

/// Arguments for Host.exit!
/// Roc signature: I32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostExitArgs = extern struct {
    arg0: i32,
};

/// Arguments for Host.random_i32!
/// Roc signature: I32, I32 => I32
/// Refcounted fields are owned by the hosted function.
pub const HostRandom_i32Args = extern struct {
    arg0: i32,
    arg1: i32,
};

/// Arguments for Host.read_env!
/// Roc signature: Host, Str => Try(Str, [NotFound])
/// Refcounted fields are owned by the hosted function.
pub const HostRead_envArgs = extern struct {
    arg0: Host,
    arg1: RocStr,
};

/// Arguments for Host.set_screen_size!
/// Roc signature: { height : F32, width : F32 } => Try({}, [NotSupported])
/// Refcounted fields are owned by the hosted function.
pub const HostSet_screen_sizeArgs = extern struct {
    @"height": f32,
    @"width": f32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostSet_screen_sizeArgs) != 8) @compileError("HostSet_screen_sizeArgs size mismatch");
        if (@alignOf(HostSet_screen_sizeArgs) != 4) @compileError("HostSet_screen_sizeArgs alignment mismatch");
    }
}

/// Arguments for Host.set_target_fps!
/// Roc signature: I32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_target_fpsArgs = extern struct {
    arg0: i32,
};

/// Implement this struct with your hosted function implementations.
/// Refcounted hosted arguments are owned by the hosted function.
/// Pass it to hostedFunctions() to create the dispatch table.
pub const PlatformHostedFns = struct {
    assets_load_texture_raw: *const fn (roc_ops: *RocOps, arg0: RocStr) callconv(.c) __AnonStruct0, // Assets.load_texture_raw!
    audio_gen_tone_raw: *const fn (arg0: __AnonStruct5) callconv(.c) u64, // Audio.gen_tone_raw!
    audio_play_raw: *const fn (arg0: u64) callconv(.c) void, // Audio.play_raw!
    draw_begin_frame: *const fn () callconv(.c) void, // Draw.begin_frame!
    draw_circle_gradient: *const fn (arg0: __AnonStruct15) callconv(.c) void, // Draw.circle_gradient!
    draw_circle_lines_raw: *const fn (arg0: __AnonStruct16) callconv(.c) void, // Draw.circle_lines_raw!
    draw_circle_raw: *const fn (arg0: __AnonStruct10) callconv(.c) void, // Draw.circle_raw!
    draw_clear: *const fn (arg0: Color) callconv(.c) void, // Draw.clear!
    draw_draw_texture_raw: *const fn (arg0: __AnonStruct35) callconv(.c) void, // Draw.draw_texture_raw!
    draw_end_frame: *const fn () callconv(.c) void, // Draw.end_frame!
    draw_fps: *const fn (arg0: __AnonStruct17) callconv(.c) void, // Draw.fps!
    draw_line_raw: *const fn (arg0: __AnonStruct18) callconv(.c) void, // Draw.line_raw!
    draw_load_font_raw: *const fn (roc_ops: *RocOps, arg0: __AnonStruct20) callconv(.c) u64, // Draw.load_font_raw!
    draw_measure_text_raw: *const fn (roc_ops: *RocOps, arg0: __AnonStruct24) callconv(.c) __AnonStruct23, // Draw.measure_text_raw!
    draw_polygon_lines_raw: *const fn (roc_ops: *RocOps, arg0: __AnonStruct27) callconv(.c) void, // Draw.polygon_lines_raw!
    draw_polygon_raw: *const fn (roc_ops: *RocOps, arg0: __AnonStruct25) callconv(.c) void, // Draw.polygon_raw!
    draw_rectangle_gradient_h: *const fn (arg0: __AnonStruct29) callconv(.c) void, // Draw.rectangle_gradient_h!
    draw_rectangle_gradient_v: *const fn (arg0: __AnonStruct30) callconv(.c) void, // Draw.rectangle_gradient_v!
    draw_rectangle_lines_raw: *const fn (arg0: __AnonStruct31) callconv(.c) void, // Draw.rectangle_lines_raw!
    draw_rectangle_raw: *const fn (arg0: __AnonStruct28) callconv(.c) void, // Draw.rectangle_raw!
    draw_rounded_rectangle_lines_raw: *const fn (arg0: __AnonStruct33) callconv(.c) void, // Draw.rounded_rectangle_lines_raw!
    draw_rounded_rectangle_raw: *const fn (arg0: __AnonStruct32) callconv(.c) void, // Draw.rounded_rectangle_raw!
    draw_text_raw: *const fn (roc_ops: *RocOps, arg0: __AnonStruct34) callconv(.c) void, // Draw.text_raw!
    draw_triangle_lines_raw: *const fn (arg0: __AnonStruct39) callconv(.c) void, // Draw.triangle_lines_raw!
    draw_triangle_raw: *const fn (arg0: __AnonStruct38) callconv(.c) void, // Draw.triangle_raw!
    host_exit: *const fn (arg0: i32) callconv(.c) void, // Host.exit!
    host_get_screen_size: *const fn () callconv(.c) __AnonStruct42, // Host.get_screen_size!
    host_random_i32: *const fn (arg0: i32, arg1: i32) callconv(.c) i32, // Host.random_i32!
    host_read_env: *const fn (roc_ops: *RocOps, arg0: Host, arg1: RocStr) callconv(.c) Try, // Host.read_env!
    host_set_screen_size: *const fn (arg0: __AnonStruct55) callconv(.c) Try, // Host.set_screen_size!
    host_set_target_fps: *const fn (arg0: i32) callconv(.c) void, // Host.set_target_fps!
};

/// Create a HostedFunctions dispatch table from your implementations.
/// The comptime parameter + nested struct ensures the function pointer array
/// lives in static memory, not on the stack.
pub fn hostedFunctions(comptime fns: PlatformHostedFns) HostedFunctions {
    const Static = struct {
        const ptrs = [_]HostedFn{
            hostedFn(fns.assets_load_texture_raw), // Assets.load_texture_raw! (index 0)
            hostedFn(fns.audio_gen_tone_raw), // Audio.gen_tone_raw! (index 1)
            hostedFn(fns.audio_play_raw), // Audio.play_raw! (index 2)
            hostedFn(fns.draw_begin_frame), // Draw.begin_frame! (index 3)
            hostedFn(fns.draw_circle_gradient), // Draw.circle_gradient! (index 4)
            hostedFn(fns.draw_circle_lines_raw), // Draw.circle_lines_raw! (index 5)
            hostedFn(fns.draw_circle_raw), // Draw.circle_raw! (index 6)
            hostedFn(fns.draw_clear), // Draw.clear! (index 7)
            hostedFn(fns.draw_draw_texture_raw), // Draw.draw_texture_raw! (index 8)
            hostedFn(fns.draw_end_frame), // Draw.end_frame! (index 9)
            hostedFn(fns.draw_fps), // Draw.fps! (index 10)
            hostedFn(fns.draw_line_raw), // Draw.line_raw! (index 11)
            hostedFn(fns.draw_load_font_raw), // Draw.load_font_raw! (index 12)
            hostedFn(fns.draw_measure_text_raw), // Draw.measure_text_raw! (index 13)
            hostedFn(fns.draw_polygon_lines_raw), // Draw.polygon_lines_raw! (index 14)
            hostedFn(fns.draw_polygon_raw), // Draw.polygon_raw! (index 15)
            hostedFn(fns.draw_rectangle_gradient_h), // Draw.rectangle_gradient_h! (index 16)
            hostedFn(fns.draw_rectangle_gradient_v), // Draw.rectangle_gradient_v! (index 17)
            hostedFn(fns.draw_rectangle_lines_raw), // Draw.rectangle_lines_raw! (index 18)
            hostedFn(fns.draw_rectangle_raw), // Draw.rectangle_raw! (index 19)
            hostedFn(fns.draw_rounded_rectangle_lines_raw), // Draw.rounded_rectangle_lines_raw! (index 20)
            hostedFn(fns.draw_rounded_rectangle_raw), // Draw.rounded_rectangle_raw! (index 21)
            hostedFn(fns.draw_text_raw), // Draw.text_raw! (index 22)
            hostedFn(fns.draw_triangle_lines_raw), // Draw.triangle_lines_raw! (index 23)
            hostedFn(fns.draw_triangle_raw), // Draw.triangle_raw! (index 24)
            hostedFn(fns.host_exit), // Host.exit! (index 25)
            hostedFn(fns.host_get_screen_size), // Host.get_screen_size! (index 26)
            hostedFn(fns.host_random_i32), // Host.random_i32! (index 27)
            hostedFn(fns.host_read_env), // Host.read_env! (index 28)
            hostedFn(fns.host_set_screen_size), // Host.set_screen_size! (index 29)
            hostedFn(fns.host_set_target_fps), // Host.set_target_fps! (index 30)
        };
    };
    return .{
        .count = Static.ptrs.len,
        .fns = @constCast(&Static.ptrs),
    };
}

/// Default memory management functions for Roc platforms.
///
/// Uses `RocEnv.allocator` for allocation. Each allocation prepends
/// size metadata so that dealloc/realloc can recover the original
/// allocation size (required because `roc_dealloc` receives no length).
pub const DefaultAllocators = struct {
    /// Allocate memory for the Roc runtime.
    pub fn rocAlloc(roc_ops: *RocOps, length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_ops.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;
        const total_size = length + size_storage_bytes;

        const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_alloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Store total size immediately before the user data pointer
        const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
        size_ptr.* = total_size;

        return @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
    }

    /// Free memory previously allocated by `rocAlloc`.
    pub fn rocDealloc(roc_ops: *RocOps, ptr: *anyopaque, alignment: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_ops.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        const size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const total_size = size_ptr.*;

        const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);
        const slice = base_ptr[0..total_size];
        allocator.rawFree(slice, align_enum, @returnAddress());
    }

    /// Reallocate memory, copying existing data to the new allocation.
    pub fn rocRealloc(roc_ops: *RocOps, ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_ops.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        // Read old size from metadata
        const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const old_total_size = old_size_ptr.*;
        const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);

        // Allocate new block
        const new_total_size = new_length + size_storage_bytes;
        const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_realloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Copy old user data to new location
        const old_user_data_size = old_total_size - size_storage_bytes;
        const copy_size = @min(old_user_data_size, new_length);
        const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
        const old_user_ptr: [*]const u8 = @ptrCast(ptr);
        @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

        // Free old allocation
        allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

        // Store new size and return user pointer
        const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
        new_size_ptr.* = new_total_size;
        return new_user_ptr;
    }
};

/// Default handlers for dbg, expect-failed, and crash.
///
/// Routes output through `RocEnv.roc_io` for platform portability.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(roc_ops: *RocOps, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_ops.env));
        env.roc_io.writeStderr("[ROC DBG] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(roc_ops: *RocOps, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_ops.env));
        env.roc_io.writeStderr("[ROC EXPECT] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a `crash` message to stderr and terminate.
    pub fn rocCrashed(roc_ops: *RocOps, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_ops.env));
        env.roc_io.writeStderr("[ROC CRASHED] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
        env.roc_io.onFatal();
    }
};

/// Create a RocOps struct with default memory management and error handlers.
///
/// Wires `DefaultAllocators`, `DefaultHandlers`, and the provided hosted
/// functions into a ready-to-use `RocOps`.
///
/// Example:
/// ```zig
/// var env = RocEnv{ .allocator = gpa.allocator(), .roc_io = RocIo.default() };
/// var roc_ops = makeRocOps(&env, hostedFunctions(.{ ... }));
/// ```
pub fn makeRocOps(env: *RocEnv, hosted_fns: HostedFunctions) RocOps {
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &DefaultAllocators.rocAlloc,
        .roc_dealloc = &DefaultAllocators.rocDealloc,
        .roc_realloc = &DefaultAllocators.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
        .hosted_fns = hosted_fns,
    };
}

// =============================================================================
// Entrypoint Declarations
//
// Extern declarations for Roc entrypoints. Call these from your platform host
// to invoke Roc application functions.
// =============================================================================

/// Arguments for entrypoint: render_for_host!
pub const Render_for_hostArgs = extern struct {
    arg0: **anyopaque,
    arg1: __AnonStruct79,
};

/// Entrypoint: app_config_for_host!
pub extern fn app_config_for_host(ops: *RocOps, ret_ptr: *__AnonStruct77, arg_ptr: ?*anyopaque) callconv(.c) void;

/// Entrypoint: init_for_host!
pub extern fn init_for_host(ops: *RocOps, ret_ptr: *Try, arg_ptr: ?*const __AnonStruct79) callconv(.c) void;

/// Entrypoint: render_for_host!
pub extern fn render_for_host(ops: *RocOps, ret_ptr: *Try, arg_ptr: ?*const Render_for_hostArgs) callconv(.c) void;

/// Entrypoint: drop_model_for_host!
pub extern fn drop_model_for_host(ops: *RocOps, ret_ptr: *anyopaque, arg_ptr: ?*const **anyopaque) callconv(.c) void;
