//! Stable names layered over the generated Roc platform ABI.
//!
//! `roc_platform_abi.zig` is regenerated by `roc glue` and uses anonymous
//! struct names for hosted symbol arguments. This module keeps handwritten host
//! code readable without hand-editing generated glue output.

const raw = @import("roc_platform_abi.zig");

pub const __AnonStruct0 = raw.__AnonStruct0;
pub const __AnonStruct82 = raw.__AnonStruct82;
pub const __AnonStruct84 = raw.__AnonStruct84;
pub const Color = raw.Color;
pub const DefaultAllocators = raw.DefaultAllocators;
pub const DrawMeasure_text_rawRetRecord = raw.DrawMeasure_text_rawRetRecord;
pub const Host = raw.Host;
pub const HostGet_screen_sizeRetRecord = raw.HostGet_screen_sizeRetRecord;
pub const RocEnv = raw.RocEnv;
pub const RocHost = raw.RocHost;
pub const RocIo = raw.RocIo;
pub const RocStr = raw.RocStr;
pub const Try = raw.Try;
pub const AudioGen_sound_rawArgs = raw.__AnonStruct8;
pub const AudioGen_tone_rawArgs = raw.__AnonStruct5;
pub const DrawBegin_cameraArgs = raw.__AnonStruct14;
pub const DrawCircle_gradientArgs = raw.__AnonStruct21;
pub const DrawCircle_lines_rawArgs = raw.__AnonStruct22;
pub const DrawCircle_rawArgs = raw.__AnonStruct17;
pub const DrawDraw_texture_rawArgs = raw.__AnonStruct41;
pub const DrawFpsArgs = raw.__AnonStruct23;
pub const DrawLine_rawArgs = raw.__AnonStruct24;
pub const DrawLoad_font_rawArgs = raw.__AnonStruct26;
pub const DrawMeasure_text_rawArgs = raw.__AnonStruct30;
pub const DrawPolygon_lines_rawArgs = raw.__AnonStruct33;
pub const DrawPolygon_rawArgs = raw.__AnonStruct31;
pub const DrawRectangle_gradient_hArgs = raw.__AnonStruct35;
pub const DrawRectangle_gradient_vArgs = raw.__AnonStruct36;
pub const DrawRectangle_lines_rawArgs = raw.__AnonStruct37;
pub const DrawRectangle_rawArgs = raw.__AnonStruct34;
pub const DrawRounded_rectangle_lines_rawArgs = raw.__AnonStruct39;
pub const DrawRounded_rectangle_rawArgs = raw.__AnonStruct38;
pub const DrawText_rawArgs = raw.__AnonStruct40;
pub const DrawTriangle_lines_rawArgs = raw.__AnonStruct44;
pub const DrawTriangle_rawArgs = raw.__AnonStruct43;
pub const HostSet_screen_sizeArgs = raw.__AnonStruct60;

/// List type using the generated Roc ABI layout.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return raw.RocListWith(T, elements_refcounted);
}
